package fr.cg95.cvq.service.military;

import fr.cg95.cvq.business.request.MeansOfContact;
import fr.cg95.cvq.business.request.MeansOfContactEnum;
import fr.cg95.cvq.business.request.Request;
import fr.cg95.cvq.business.request.RequestState;
import fr.cg95.cvq.business.users.*;
import fr.cg95.cvq.business.authority.*;
import fr.cg95.cvq.business.document.DepositOrigin;
import fr.cg95.cvq.business.document.DepositType;
import fr.cg95.cvq.business.document.Document;
import fr.cg95.cvq.business.military.*;
import fr.cg95.cvq.exception.*;
import fr.cg95.cvq.security.SecurityContext;
import fr.cg95.cvq.service.request.IRequestService;
import fr.cg95.cvq.service.document.IDocumentService;
import fr.cg95.cvq.service.military.IMilitaryCensusRequestService;
import fr.cg95.cvq.util.Critere;

import fr.cg95.cvq.testtool.ServiceTestCase;
import fr.cg95.cvq.testtool.TestUtils;
import fr.cg95.cvq.testtool.BusinessObjectsFactory;

import fr.cg95.cvq.xml.military.MilitaryCensusRequestDocument;

import org.apache.commons.lang.StringUtils;
import org.springframework.context.ConfigurableApplicationContext;

import junit.framework.Assert;

import java.util.*;
import java.io.File;
import java.io.FileOutputStream;
import java.math.BigInteger;

/**
 * Generated by Velocity if not present, can be edited safely !
 */
public class MilitaryCensusRequestServiceTest extends ServiceTestCase {

    protected IMilitaryCensusRequestService iMilitaryCensusRequestService;

    protected void onSetUp() throws Exception {
    	super.onSetUp();
        ConfigurableApplicationContext cac = getContext(getConfigLocations());
        iMilitaryCensusRequestService = 
            (IMilitaryCensusRequestService) cac.getBean(StringUtils.uncapitalize("MilitaryCensusRequest") + "Service");
    }

    protected MilitaryCensusRequest fillMeARequest() throws CvqException {

        MilitaryCensusRequest request = new MilitaryCensusRequest();
            request.setFatherBirthDepartment(InseeDepartementCodeType.NONE);
                    request.setChildProfession("ChildProfession");
                    request.setChildSpeciality("ChildSpeciality");
                  request.setChildOtherCountry(FullNationalityType.NONE);
                  request.setChildStatus(FamilyStatusType.MARRIED);
                request.setAliveChildren(BigInteger.valueOf(1));
            request.setChildrenInCharge(BigInteger.valueOf(1));
            request.setAffectionOrDisease(Boolean.valueOf(true));
            request.setJapdExemption(Boolean.valueOf(true));
              request.setChildSituation(ChildSituationType.COLLEGE);
                  if ("MaidenName".length() > 38)
        request.setMaidenName("MaidenName".substring(0, 38));
      else
        request.setMaidenName("MaidenName");
                request.setStatePupil(Boolean.valueOf(true));
              request.setChildTitle(TitleType.MISTER);
                  if ("ChildPhone".length() > 10)
        request.setChildPhone("ChildPhone".substring(0, 10));
      else
        request.setChildPhone("ChildPhone");
                  if ("MotherLastName".length() > 38)
        request.setMotherLastName("MotherLastName".substring(0, 38));
      else
        request.setMotherLastName("MotherLastName");
                    request.setChildMail("ChildMail");
                  request.setChildDiploma(ChildDiplomaType.B_A_C);
                  request.setMotherBirthCountry(CountryType.UNKNOWN);
                  if ("FatherLastName".length() > 38)
        request.setFatherLastName("FatherLastName".substring(0, 38));
      else
        request.setFatherLastName("FatherLastName");
                  request.setPrefectPupilDepartment(InseeDepartementCodeType.NONE);
                  request.setMotherBirthDepartment(InseeDepartementCodeType.NONE);
                  request.setChildResidenceCountry(CountryType.UNKNOWN);
                    request.setFatherBirthCity("FatherBirthCity");
                request.setFatherBirthDate(new Date());
              if ("FatherFirstName".length() > 38)
        request.setFatherFirstName("FatherFirstName".substring(0, 38));
      else
        request.setFatherFirstName("FatherFirstName");
                    request.setOtherSituation("OtherSituation");
                    request.setMotherBirthCity("MotherBirthCity");
                  request.setFatherNationality(FullNationalityType.NONE);
                request.setMotherBirthDate(new Date());
            request.setPrefectPupil(Boolean.valueOf(true));
              request.setChildCountry(FullNationalityType.NONE);
                  if ("MotherFirstName".length() > 38)
        request.setMotherFirstName("MotherFirstName".substring(0, 38));
      else
        request.setMotherFirstName("MotherFirstName");
                    request.setChildConvention("ChildConvention");
                  request.setChildBirthCountry(CountryType.UNKNOWN);
                  request.setMotherNationality(FullNationalityType.NONE);
                  request.setFatherBirthCountry(CountryType.UNKNOWN);
                request.setHighlyInfirm(Boolean.valueOf(true));
  
        // Means Of Contact
        MeansOfContact meansOfContact = iMeansOfContactService.getMeansOfContactByType(
                    MeansOfContactEnum.EMAIL);
        request.setMeansOfContact(meansOfContact);
        
        MilitaryCensusRequestFeeder.feed(request);
        
        return request;
    }
        	
    protected void completeValidateAndDelete(MilitaryCensusRequest request) 
    	throws CvqException, java.io.IOException {
    	
        // add a document to the request
        ///////////////////////////////

        Document doc = new Document();
        doc.setEcitizenNote("Ma carte d'identité !");
        doc.setDepositOrigin(DepositOrigin.ECITIZEN);
        doc.setDepositType(DepositType.PC);
        doc.setDocumentType(iDocumentService.getDocumentTypeById(IDocumentService.IDENTITY_RECEIPT_TYPE));
        Long documentId = iDocumentService.create(doc, request.getHomeFolder().getId(), 
        					  request.getRequester().getId());
        iMilitaryCensusRequestService.addDocument(request.getId(), documentId);
        Set documentsSet =
            iMilitaryCensusRequestService.getAssociatedDocuments(request.getId());
        Assert.assertEquals(documentsSet.size(), 1);

        // FIXME : test list of pending / in-progress registrations
        Critere testCrit = new Critere();
        testCrit.setAttribut(Request.SEARCH_BY_REQUESTER_LASTNAME);
        testCrit.setComparatif(Critere.EQUALS);
        testCrit.setValue(request.getRequester().getLastName());
        Set testCritSet = new HashSet();
        testCritSet.add(testCrit);
        Set allRequests = iRequestService.get(testCritSet, null, false);
        Assert.assertNotNull(allRequests);

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        SecurityContext.setCurrentSite(localAuthorityName,
                                        SecurityContext.BACK_OFFICE_CONTEXT);
        SecurityContext.setCurrentAgent(agentNameWithCategoriesRoles);
        iMilitaryCensusRequestService.complete(request.getId());
        iMilitaryCensusRequestService.validate(request.getId());

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        byte[] generatedCertificate = iRequestService.getCertificate(request.getId(),
                                                                     RequestState.PENDING);

        if (generatedCertificate == null)
            fail("No certificate found");
            
        //     Write tele-service xml data file
        File xmlFile = File.createTempFile("tmp" + request.getId(), ".xml");
        FileOutputStream xmlFos = new FileOutputStream(xmlFile);
        xmlFos.write(iRequestService.getById(request.getId()).modelToXmlString().getBytes());

        File file = File.createTempFile("tmp" + request.getId(), ".pdf");
        FileOutputStream fos = new FileOutputStream(file);
        fos.write(generatedCertificate);

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        // delete request
        iMilitaryCensusRequestService.delete(request.getId());
    }


    public void testWithHomeFolderXml() throws CvqException,
			CvqObjectNotFoundException, java.io.FileNotFoundException,
			java.io.IOException {

        startTransaction();
        
	SecurityContext.setCurrentSite(localAuthorityName,
					SecurityContext.FRONT_OFFICE_CONTEXT);

	// create a vo card request (to create home folder and associates)
	CreationBean cb = gimmeAnHomeFolder();

	Long voCardRequestId = cb.getRequestId();
	String proposedLogin = cb.getLogin();

        // close current session and re-open a new one
        continueWithNewTransaction();
        
	SecurityContext.setCurrentEcitizen(proposedLogin);

	// get the home folder id
	HomeFolder homeFolder = iHomeFolderService.getByRequestId(voCardRequestId);
	Assert.assertNotNull(homeFolder);
	Long homeFolderId = homeFolder.getId();
	Assert.assertNotNull(homeFolderId);

	// fill and create the request
	// ////////////////////////////

	MilitaryCensusRequest request = fillMeARequest();
	request.setRequester(homeFolder.getHomeFolderResponsible());
        MilitaryCensusRequestFeeder.setSubject(request, homeFolder);

        Set authorizedSubjects = iMilitaryCensusRequestService.getAuthorizedSubjects(homeFolderId).keySet();

	MilitaryCensusRequestDocument requestDoc =
		(MilitaryCensusRequestDocument) request.modelToXml();
	Long requestId = iMilitaryCensusRequestService.create(requestDoc.getDomNode());

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        Map newAuthorizedSubjectsMap = iMilitaryCensusRequestService.getAuthorizedSubjects(homeFolderId);
        if (newAuthorizedSubjectsMap == null) 
            Assert.assertEquals(authorizedSubjects.size(), 1);
        else
            Assert.assertEquals(newAuthorizedSubjectsMap.size(), authorizedSubjects.size() - 1);

	MilitaryCensusRequest requestFromDb = 
		(MilitaryCensusRequest) iMilitaryCensusRequestService.getById(requestId);
	Assert.assertEquals(requestId, requestFromDb.getId());
	Adult requester = requestFromDb.getRequester();
	Assert.assertNotNull(requester);
	Assert.assertNotNull(requestFromDb.getMeansOfContact());
    Assert.assertEquals(requestFromDb.getMeansOfContact().getType(), MeansOfContactEnum.EMAIL);

        // close current session and re-open a new one
        continueWithNewTransaction();
        
	completeValidateAndDelete(requestFromDb);

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        HomeFolder homeFolderAfterDelete = iHomeFolderService.getById(homeFolderId);
        Assert.assertNotNull(homeFolderAfterDelete);
        Assert.assertNotNull(homeFolderAfterDelete.getHomeFolderResponsible());
    }

    public void testWithoutHomeFolder()
        throws CvqException, CvqObjectNotFoundException,
               java.io.FileNotFoundException, java.io.IOException {

	if (!iMilitaryCensusRequestService.supportUnregisteredCreation())
	    return;

	startTransaction();
	
        SecurityContext.setCurrentSite(localAuthorityName,
                                        SecurityContext.FRONT_OFFICE_CONTEXT);
        
        MilitaryCensusRequest request = fillMeARequest();

        Address address = BusinessObjectsFactory.gimmeAdress("12", "Rue d'Aligre", "Paris", "75012");
        Adult requester =
            BusinessObjectsFactory.gimmeAdult(TitleType.MISTER, "LASTNAME", "requester", address,
                                              FamilyStatusType.MARRIED);
        requester.setPassword("requester");
        request.setRequester(requester);
        requester.setAdress(address);
        MilitaryCensusRequestFeeder.setSubject(request, null);

        MilitaryCensusRequestDocument requestDoc = 
            (MilitaryCensusRequestDocument) request.modelToXml();
        Long requestId =
             iMilitaryCensusRequestService.create(requestDoc.getDomNode());
        
        // close current session and re-open a new one
        continueWithNewTransaction();
        
        // start testing request creation
        /////////////////////////////////

        MilitaryCensusRequest requestFromDb =
            (MilitaryCensusRequest) iMilitaryCensusRequestService.getById(requestId);
        Assert.assertEquals(requestId, requestFromDb.getId());
        requester = requestFromDb.getRequester();
        Assert.assertNotNull(requester);
        
        Long homeFolderId = requestFromDb.getHomeFolder().getId();
        Long requesterId = requestFromDb.getRequester().getId();

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        completeValidateAndDelete(requestFromDb);
        
        // close current session and re-open a new one
        continueWithNewTransaction();
        
        try {
            iHomeFolderService.getById(homeFolderId);
            fail("should not have found home folder");
        } catch (CvqObjectNotFoundException confe) {
            // great, that was expected
        }
        try {
            iAdultService.getById(requesterId);
            fail("should not have found requester");
        } catch (CvqObjectNotFoundException confe) {
            // great, that was expected
        }

        SecurityContext.resetCurrentSite();
        
        commitTransaction();
    }
}
