<%@ page contentType="text/html; charset=UTF-8" %>
<%@ taglib uri="/cvq-forms" prefix="cvqf" %>

	<cvqf:form name="Inscription" action="#" >
      <fieldset class="fieldset_zone">
        <ul class="insert_list">
          <li class="text_row">
			<label for="subjectChildLastName" class="label">Nom</label>
            <cvqf:text name="subjectChildLastName" mode="disabled" maxlength="38"/>
          </li>
          <li class="text_row">
			<label for="subjectChildFirstName" class="label">Prénom</label>
            <cvqf:text name="subjectChildFirstName" mode="disabled" maxlength="38"/>
          </li>
          <li class="select_row">
			<label for="childCountry" class="label">Nationalité<span class="required">*</span></label>
            <cvqf:select name="childCountry" mode="">
              <option value="">Choisissez un nationalité</option>
              <option value="None">Aucune</option>
              <option value="af">Afghan(e)</option>
              <option value="za">Sud-africain(e)</option>
              <option value="al">Albanais(e)</option>
              <option value="dz">Algérien(ne)</option>
              <option value="de">Allemand(e)</option>
              <option value="ad">Andorran(e)</option>
              <option value="ao">Angolais(e)</option>
              <option value="ai">d'Anguilla</option>
              <option value="aq">d'Antarctique</option>
              <option value="ag">d'Antigua-et-Barbuda</option>
              <option value="an">des Antilles néerlandaises</option>
              <option value="sa">Saoudien(nne)</option>
              <option value="ar">Argentin(e)</option>
              <option value="am">Arménien(ne)</option>
              <option value="aw">d'Aruba</option>
              <option value="au">Australien(ne)</option>
              <option value="at">Autrichien(ne)</option>
              <option value="az">Azerbaïdjanais(e)</option>
              <option value="bs">Bahamien(ne)</option>
              <option value="bh">Bahreïnien(ne)</option>
              <option value="bd">Bangladais(e)</option>
              <option value="bb">Barbadien(ne)</option>
              <option value="be">Belge</option>
              <option value="bz">Belizien(ne)</option>
              <option value="bj">Béninois(e)</option>
              <option value="bm">des Bermudes</option>
              <option value="bt">Bhoutanais(e)</option>
              <option value="by">Biélorusse</option>
              <option value="mm">Birman(e)</option>
              <option value="bo">Bolivien(ne)</option>
              <option value="ba">de Bosnie-et-Herzégovine</option>
              <option value="bw">Botswanais(e)</option>
              <option value="br">Brésilien(ne)</option>
              <option value="bn">du Brunei</option>
              <option value="bg">Bulgare</option>
              <option value="bf">Burkinabè</option>
              <option value="bi">Burundais(e)</option>
              <option value="kh">Cambodgien(ne)</option>
              <option value="cm">Camerounais(e)</option>
              <option value="ca">Canadien(ne)</option>
              <option value="cv">Cap-Verdien(ne)</option>
              <option value="cl">Chilien(ne)</option>
              <option value="cn">Chinois(e)</option>
              <option value="cy">Chypriote</option>
              <option value="co">Colombien(ne)</option>
              <option value="km">Comorien(ne)</option>
              <option value="cg">Congolais(e)</option>
              <option value="kp">Nord-Coréen(ne)</option>
              <option value="kr">Sud-Coréen(ne)</option>
              <option value="cr">Costaricien(ne)</option>
              <option value="hr">Croate</option>
              <option value="cu">Cubain(e)</option>
              <option value="dk">Danois(e)</option>
              <option value="dj">Djiboutien(ne)</option>
              <option value="dm">Dominiquais(e)</option>
              <option value="eg">Égyptien(ne)</option>
              <option value="ae">des Émirats arabes unis</option>
              <option value="ec">Équatorien(ne)</option>
              <option value="er">Érythréen(ne)</option>
              <option value="es">Espagnol(e)</option>
              <option value="ee">Estonien(ne)</option>
              <option value="us">Américain(e)</option>
              <option value="et">Éthiopien(ne)</option>
              <option value="fi">Finlandais(e)</option>
              <option value="fr">Français(e)</option>
              <option value="ge">Géorgien(ne)</option>
              <option value="ga">Gabonais(e)</option>
              <option value="gm">Gambien(ne)</option>
              <option value="gh">Ghanéen(ne)</option>
              <option value="gi">de Gibraltar</option>
              <option value="gr">Grec(que)</option>
              <option value="gd">Grenadin(e)</option>
              <option value="gl">du Groenland</option>
              <option value="gu">du Guam</option>
              <option value="gt">Guatemaltèque</option>
              <option value="gn">Guinéen(ne)</option>
              <option value="gq">Equato-guinéen(ne)</option>
              <option value="gw">de Guinée-Bissao</option>
              <option value="ht">Haïtien(ne)</option>
              <option value="hn">Hondurien(ne)</option>
              <option value="hk">de Hong Kong</option>
              <option value="hu">Hongrois(e)</option>
              <option value="ck">des Iles Cook (CK)</option>
              <option value="fj">des Iles Fidji</option>
              <option value="mh">Marshallais(e)</option>
              <option value="sb">Salomonais(e)</option>
              <option value="in">Indien(ne)</option>
              <option value="id">Indonésien(ne)</option>
              <option value="ir">Iranien(ne)</option>
              <option value="iq">Iraquien(ne)</option>
              <option value="ie">Irlandais(e)</option>
              <option value="is">Islandais(e)</option>
              <option value="il">Israëlien(ne)</option>
              <option value="it">Italien(ne)</option>
              <option value="ci">Ivoirien(ne)</option>
              <option value="jm">Jamaïquain(e)</option>
              <option value="jp">Japonais(e)</option>
              <option value="jo">Jordanien(ne)</option>
              <option value="kz">Kazakh(e)</option>
              <option value="ke">Kényan(e)</option>
              <option value="kg">Kirghize</option>
              <option value="ki">Kiribatien(ne)</option>
              <option value="kw">Koweïtien(ne)</option>
              <option value="la">Laotien(ne)</option>
              <option value="ls">du Lesotho</option>
              <option value="lv">Lettonien(ne)</option>
              <option value="lb">Libanais(e)</option>
              <option value="lr">Liberien(ne)</option>
              <option value="ly">Libyen(ne)</option>
              <option value="li">Liechtensteinois(e)</option>
              <option value="lt">Lituanien(ne)</option>
              <option value="lu">Luxembourgeois(e)</option>
              <option value="mg">Malgache</option>
              <option value="my">Malaisien(ne)</option>
              <option value="mw">Malawien(ne)</option>
              <option value="mv">Maldivien(ne)</option>
              <option value="ml">Malien(ne)</option>
              <option value="mt">Maltais(e)</option>
              <option value="ma">Marocain(e)</option>
              <option value="mu">Mauricien(ne)</option>
              <option value="mr">Mauritanien(ne)</option>
              <option value="mx">Mexicain(e)</option>
              <option value="fm">Micronésien(ne)</option>
              <option value="md">Moldove</option>
              <option value="mc">Monégasque</option>
              <option value="mn">Mongolien(ne)</option>
              <option value="mz">Mozambicain(e)</option>
              <option value="np">Népalais(e)</option>
              <option value="na">Namibien(ne)</option>
              <option value="nr">Nauruan(e)</option>
              <option value="ni">Nicaraguayen(ne)</option>
              <option value="ne">Nigérien(ne)</option>
              <option value="ng">Nigérian(ne)</option>
              <option value="nu">Niuéan(e)</option>
              <option value="no">Norvégien(ne)</option>
              <option value="nz">Néo-Zélandais(e)</option>
              <option value="om">Omanais(e)</option>
              <option value="ug">Ougandais(e)</option>
              <option value="uz">Ouzbèk(e)</option>
              <option value="pe">Péruvien(ne)</option>
              <option value="pk">Pakistanais(e)</option>
              <option value="pa">Panaméen(ne)</option>
              <option value="pg">de Papouasie-Nouvelle-Guinée</option>
              <option value="py">Paraguayen(ne)</option>
              <option value="nl">Néerlandais(e)</option>
              <option value="ph">Philippin(e)</option>
              <option value="pl">Polonais(e)</option>
              <option value="pt">Portugais(e)</option>
              <option value="qa">Qatarien(ne)</option>
              <option value="cf">Centrafricain(e)</option>
              <option value="cd">Congolais(e)</option>
              <option value="do">Dominicain(e)</option>
              <option value="cz">Tchèque</option>
              <option value="ro">Roumain(e)</option>
              <option value="gb">Britannique</option>
              <option value="ru">Russe</option>
              <option value="rw">Rwandais(e)</option>
              <option value="sn">Sénégalais(e)</option>
              <option value="kn">de Saint-Christophe-et-Niévès</option>
              <option value="sm">Saint-Marinais(e)</option>
              <option value="va">du Saint-Siège</option>
              <option value="vc">de Saint-Vincent-et-les-Grenadines</option>
              <option value="lc">Saint-Lucien(ne)</option>
              <option value="sv">Salvadorien(ne)</option>
              <option value="ws">Samoan(e)</option>
              <option value="st">de Sao Tomé-et-Principe</option>
              <option value="sc">Seychellois(e)</option>
              <option value="sl">de Sierra Leone</option>
              <option value="sg">Singapourien(ne)</option>
              <option value="si">Slovénien(ne)</option>
              <option value="sk">Slovaque</option>
              <option value="so">Somalien(ne)</option>
              <option value="sd">Soudanais(e)</option>
              <option value="lk">Sri Lankais(e)</option>
              <option value="se">Suèdois(e)</option>
              <option value="ch">Suisse</option>
              <option value="sr">Surinamais(e)</option>
              <option value="sz">Swazi(e)</option>
              <option value="sy">Syrien(ne)</option>
              <option value="tw">Taïwanais(e)</option>
              <option value="tj">Tadjik(e)</option>
              <option value="tz">Tanzanien(ne)</option>
              <option value="td">Tchadien(ne)</option>
              <option value="th">Thaïlandais(e)</option>
              <option value="tl">Est-Timorais(e)</option>
              <option value="tg">Togolais(e)</option>
              <option value="to">Tongan(e)</option>
              <option value="vt">Trinidadien(ne)</option>
              <option value="tn">Tunisien(ne)</option>
              <option value="tm">Turkmène</option>
              <option value="tr">Turc(que)</option>
              <option value="tv">Tuvaluan(e)</option>
              <option value="ua">Ukrainien(ne)</option>
              <option value="uy">Uruguayen(ne)</option>
              <option value="vu">Vanuatuan(e)</option>
              <option value="ve">Venezuelien(ne)</option>
              <option value="vn">Viêtnamien(ne)</option>
              <option value="ye">Yéménite</option>
              <option value="zm">Zambien(ne)</option>
              <option value="zw">Zimbabwéen(ne)</option>
              <option value="mk">de l'ancienne République yougoslave de Macédoine</option>
            </cvqf:select>
          </li>
          <li class="select_row">
			<label for="childOtherCountry" class="label">Deuxième nationalité</label>
            <cvqf:select name="childOtherCountry" mode="">
              <option value="">Choisissez une deuxième nationalité</option>
              <option value="None">Aucune</option>
              <option value="af">Afghan(e)</option>
              <option value="za">Sud-africain(e)</option>
              <option value="al">Albanais(e)</option>
              <option value="dz">Algérien(ne)</option>
              <option value="de">Allemand(e)</option>
              <option value="ad">Andorran(e)</option>
              <option value="ao">Angolais(e)</option>
              <option value="ai">d'Anguilla</option>
              <option value="aq">d'Antarctique</option>
              <option value="ag">d'Antigua-et-Barbuda</option>
              <option value="an">des Antilles néerlandaises</option>
              <option value="sa">Saoudien(nne)</option>
              <option value="ar">Argentin(e)</option>
              <option value="am">Arménien(ne)</option>
              <option value="aw">d'Aruba</option>
              <option value="au">Australien(ne)</option>
              <option value="at">Autrichien(ne)</option>
              <option value="az">Azerbaïdjanais(e)</option>
              <option value="bs">Bahamien(ne)</option>
              <option value="bh">Bahreïnien(ne)</option>
              <option value="bd">Bangladais(e)</option>
              <option value="bb">Barbadien(ne)</option>
              <option value="be">Belge</option>
              <option value="bz">Belizien(ne)</option>
              <option value="bj">Béninois(e)</option>
              <option value="bm">des Bermudes</option>
              <option value="bt">Bhoutanais(e)</option>
              <option value="by">Biélorusse</option>
              <option value="mm">Birman(e)</option>
              <option value="bo">Bolivien(ne)</option>
              <option value="ba">de Bosnie-et-Herzégovine</option>
              <option value="bw">Botswanais(e)</option>
              <option value="br">Brésilien(ne)</option>
              <option value="bn">du Brunei</option>
              <option value="bg">Bulgare</option>
              <option value="bf">Burkinabè</option>
              <option value="bi">Burundais(e)</option>
              <option value="kh">Cambodgien(ne)</option>
              <option value="cm">Camerounais(e)</option>
              <option value="ca">Canadien(ne)</option>
              <option value="cv">Cap-Verdien(ne)</option>
              <option value="cl">Chilien(ne)</option>
              <option value="cn">Chinois(e)</option>
              <option value="cy">Chypriote</option>
              <option value="co">Colombien(ne)</option>
              <option value="km">Comorien(ne)</option>
              <option value="cg">Congolais(e)</option>
              <option value="kp">Nord-Coréen(ne)</option>
              <option value="kr">Sud-Coréen(ne)</option>
              <option value="cr">Costaricien(ne)</option>
              <option value="hr">Croate</option>
              <option value="cu">Cubain(e)</option>
              <option value="dk">Danois(e)</option>
              <option value="dj">Djiboutien(ne)</option>
              <option value="dm">Dominiquais(e)</option>
              <option value="eg">Égyptien(ne)</option>
              <option value="ae">des Émirats arabes unis</option>
              <option value="ec">Équatorien(ne)</option>
              <option value="er">Érythréen(ne)</option>
              <option value="es">Espagnol(e)</option>
              <option value="ee">Estonien(ne)</option>
              <option value="us">Américain(e)</option>
              <option value="et">Éthiopien(ne)</option>
              <option value="fi">Finlandais(e)</option>
              <option value="fr">Français(e)</option>
              <option value="ge">Géorgien(ne)</option>
              <option value="ga">Gabonais(e)</option>
              <option value="gm">Gambien(ne)</option>
              <option value="gh">Ghanéen(ne)</option>
              <option value="gi">de Gibraltar</option>
              <option value="gr">Grec(que)</option>
              <option value="gd">Grenadin(e)</option>
              <option value="gl">du Groenland</option>
              <option value="gu">du Guam</option>
              <option value="gt">Guatemaltèque</option>
              <option value="gn">Guinéen(ne)</option>
              <option value="gq">Equato-guinéen(ne)</option>
              <option value="gw">de Guinée-Bissao</option>
              <option value="ht">Haïtien(ne)</option>
              <option value="hn">Hondurien(ne)</option>
              <option value="hk">de Hong Kong</option>
              <option value="hu">Hongrois(e)</option>
              <option value="ck">des Iles Cook (CK)</option>
              <option value="fj">des Iles Fidji</option>
              <option value="mh">Marshallais(e)</option>
              <option value="sb">Salomonais(e)</option>
              <option value="in">Indien(ne)</option>
              <option value="id">Indonésien(ne)</option>
              <option value="ir">Iranien(ne)</option>
              <option value="iq">Iraquien(ne)</option>
              <option value="ie">Irlandais(e)</option>
              <option value="is">Islandais(e)</option>
              <option value="il">Israëlien(ne)</option>
              <option value="it">Italien(ne)</option>
              <option value="ci">Ivoirien(ne)</option>
              <option value="jm">Jamaïquain(e)</option>
              <option value="jp">Japonais(e)</option>
              <option value="jo">Jordanien(ne)</option>
              <option value="kz">Kazakh(e)</option>
              <option value="ke">Kényan(e)</option>
              <option value="kg">Kirghize</option>
              <option value="ki">Kiribatien(ne)</option>
              <option value="kw">Koweïtien(ne)</option>
              <option value="la">Laotien(ne)</option>
              <option value="ls">du Lesotho</option>
              <option value="lv">Lettonien(ne)</option>
              <option value="lb">Libanais(e)</option>
              <option value="lr">Liberien(ne)</option>
              <option value="ly">Libyen(ne)</option>
              <option value="li">Liechtensteinois(e)</option>
              <option value="lt">Lituanien(ne)</option>
              <option value="lu">Luxembourgeois(e)</option>
              <option value="mg">Malgache</option>
              <option value="my">Malaisien(ne)</option>
              <option value="mw">Malawien(ne)</option>
              <option value="mv">Maldivien(ne)</option>
              <option value="ml">Malien(ne)</option>
              <option value="mt">Maltais(e)</option>
              <option value="ma">Marocain(e)</option>
              <option value="mu">Mauricien(ne)</option>
              <option value="mr">Mauritanien(ne)</option>
              <option value="mx">Mexicain(e)</option>
              <option value="fm">Micronésien(ne)</option>
              <option value="md">Moldove</option>
              <option value="mc">Monégasque</option>
              <option value="mn">Mongolien(ne)</option>
              <option value="mz">Mozambicain(e)</option>
              <option value="np">Népalais(e)</option>
              <option value="na">Namibien(ne)</option>
              <option value="nr">Nauruan(e)</option>
              <option value="ni">Nicaraguayen(ne)</option>
              <option value="ne">Nigérien(ne)</option>
              <option value="ng">Nigérian(ne)</option>
              <option value="nu">Niuéan(e)</option>
              <option value="no">Norvégien(ne)</option>
              <option value="nz">Néo-Zélandais(e)</option>
              <option value="om">Omanais(e)</option>
              <option value="ug">Ougandais(e)</option>
              <option value="uz">Ouzbèk(e)</option>
              <option value="pe">Péruvien(ne)</option>
              <option value="pk">Pakistanais(e)</option>
              <option value="pa">Panaméen(ne)</option>
              <option value="pg">de Papouasie-Nouvelle-Guinée</option>
              <option value="py">Paraguayen(ne)</option>
              <option value="nl">Néerlandais(e)</option>
              <option value="ph">Philippin(e)</option>
              <option value="pl">Polonais(e)</option>
              <option value="pt">Portugais(e)</option>
              <option value="qa">Qatarien(ne)</option>
              <option value="cf">Centrafricain(e)</option>
              <option value="cd">Congolais(e)</option>
              <option value="do">Dominicain(e)</option>
              <option value="cz">Tchèque</option>
              <option value="ro">Roumain(e)</option>
              <option value="gb">Britannique</option>
              <option value="ru">Russe</option>
              <option value="rw">Rwandais(e)</option>
              <option value="sn">Sénégalais(e)</option>
              <option value="kn">de Saint-Christophe-et-Niévès</option>
              <option value="sm">Saint-Marinais(e)</option>
              <option value="va">du Saint-Siège</option>
              <option value="vc">de Saint-Vincent-et-les-Grenadines</option>
              <option value="lc">Saint-Lucien(ne)</option>
              <option value="sv">Salvadorien(ne)</option>
              <option value="ws">Samoan(e)</option>
              <option value="st">de Sao Tomé-et-Principe</option>
              <option value="sc">Seychellois(e)</option>
              <option value="sl">de Sierra Leone</option>
              <option value="sg">Singapourien(ne)</option>
              <option value="si">Slovénien(ne)</option>
              <option value="sk">Slovaque</option>
              <option value="so">Somalien(ne)</option>
              <option value="sd">Soudanais(e)</option>
              <option value="lk">Sri Lankais(e)</option>
              <option value="se">Suèdois(e)</option>
              <option value="ch">Suisse</option>
              <option value="sr">Surinamais(e)</option>
              <option value="sz">Swazi(e)</option>
              <option value="sy">Syrien(ne)</option>
              <option value="tw">Taïwanais(e)</option>
              <option value="tj">Tadjik(e)</option>
              <option value="tz">Tanzanien(ne)</option>
              <option value="td">Tchadien(ne)</option>
              <option value="th">Thaïlandais(e)</option>
              <option value="tl">Est-Timorais(e)</option>
              <option value="tg">Togolais(e)</option>
              <option value="to">Tongan(e)</option>
              <option value="vt">Trinidadien(ne)</option>
              <option value="tn">Tunisien(ne)</option>
              <option value="tm">Turkmène</option>
              <option value="tr">Turc(que)</option>
              <option value="tv">Tuvaluan(e)</option>
              <option value="ua">Ukrainien(ne)</option>
              <option value="uy">Uruguayen(ne)</option>
              <option value="vu">Vanuatuan(e)</option>
              <option value="ve">Venezuelien(ne)</option>
              <option value="vn">Viêtnamien(ne)</option>
              <option value="ye">Yéménite</option>
              <option value="zm">Zambien(ne)</option>
              <option value="zw">Zimbabwéen(ne)</option>
              <option value="mk">de l'ancienne République yougoslave de Macédoine</option>
            </cvqf:select>
          </li>
          <li class="text_row">
			<label for="childConvention" class="label">Convention internationale</label>
            <cvqf:text name="childConvention" mode="" rows="6"/>
          </li>
        </ul>
      </fieldset>
	</cvqf:form>
	<script type="text/javascript">
		function validationData() {
   		  this.childCountry = new Function("key","this.label='Nationalité'; this.msg=null; this.required=true; this.minlength=0; this.maxlength=0; this.type=null; return this[key];");
     		  this.childOtherCountry = new Function("key","this.label='Deuxième nationalité'; this.msg=null; this.required=false; this.minlength=0; this.maxlength=0; this.type=null; return this[key];");
     		  this.childConvention = new Function("key","this.label='Convention internationale'; this.msg=null; this.required=false; this.minlength=0; this.maxlength=0; this.type=null; return this[key];");
  		}
        updateDisplay("childCountry");
        updateDisplay("childOtherCountry");
  		setFocus("Inscription");
	</script>
