<rule-set name="Regles d'acces portlet CVQ"
  xmlns="http://drools.org/rules"
  xmlns:groovy="http://drools.org/semantics/groovy"
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:schemaLocation="http://drools.org/rules rules.xsd
    http://drools.org/semantics/groovy groovy.xsd">

  <rule name="Montrer la portlet de tâches aux utilisateurs CVQ" salience="100">
    <parameter identifier="portlet"><groovy:class>com.zenexity.pict.portal.om.entity.PictPortletEntity</groovy:class></parameter>
    <parameter identifier="permission"><groovy:class>java.lang.String</groovy:class></parameter>
    <parameter identifier="principal"><groovy:class>com.zenexity.pict.portal.security.PictPrincipal</groovy:class></parameter>
    <parameter identifier="rulesSession"><groovy:class>com.zenexity.pict.portal.rules.RulesSession</groovy:class></parameter>
    <parameter identifier="access"><groovy:class>com.zenexity.pict.portal.rules.Access</groovy:class></parameter>
    <groovy:condition>permission == 'read'</groovy:condition>
    <groovy:condition>portlet.portletDefinition.id == 'com.zenexity.pict.cvq.bo-tasks'</groovy:condition>
    <groovy:consequence>
                
      if(principal.guest) {
        access.deny()
        return
      }

      if( rulesSession['cvqContributor'] == null ) {
        exist = com.zenexity.pict.portal.rules.PortalAPI.invokeMBean("com.zenexity.pict.cvq:name=portlets", "agentExists", [principal.name])
        rulesSession['cvqContributor'] = exist
      } else {
        exist = rulesSession['cvqContributor']
      }

      if(exist)
        access.grant()
      else
        access.deny()
    </groovy:consequence>
  </rule>

</rule-set>
