//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 04:10:50 PM CEST 
//


package fr.capwebct.capdemat.plugins.externalservices.interconnexiondila.message;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdressePostaleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdressePostaleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PointRemise" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}LigneAdresseType" minOccurs="0"/>
 *         &lt;element name="NumeroVoie" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}NumeroVoieType" minOccurs="0"/>
 *         &lt;element name="ExtensionIndiceRepetition" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}LigneAdresseType" minOccurs="0"/>
 *         &lt;element name="Voie" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}VoieType" minOccurs="0"/>
 *         &lt;element name="LigneAdresse" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}LigneAdresseType" minOccurs="0"/>
 *         &lt;element name="MentionsAdresseParticulieres" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}LigneAdresseType" minOccurs="0"/>
 *         &lt;element name="CodePostal" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}CodePostalType" minOccurs="0"/>
 *         &lt;element name="CodeCedex" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}CodeCedexType" minOccurs="0"/>
 *         &lt;element name="Ville" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}VilleType" minOccurs="0"/>
 *         &lt;element name="Pays" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}LigneAdresseType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdressePostaleType", propOrder = {
    "pointRemise",
    "numeroVoie",
    "extensionIndiceRepetition",
    "etage",
    "batiment",
    "voie",
    "ligneAdresse",
    "mentionsAdresseParticulieres",
    "boitePostale",
    "codePostal",
    "codeCedex",
    "ville",
    "pays"
})
public class AdressePostaleType {

    @XmlElement(name = "PointRemise")
    protected String pointRemise;
    @XmlElement(name = "NumeroVoie")
    protected String numeroVoie;
    @XmlElement(name = "ExtensionIndiceRepetition")
    protected String extensionIndiceRepetition;
    @XmlElement(name = "Voie")
    protected String voie = "";
    @XmlElement(name = "LigneAdresse")
    protected String ligneAdresse;
    @XmlElement(name = "MentionsAdresseParticulieres")
    protected String mentionsAdresseParticulieres;
    @XmlElement(name = "CodePostal")
    protected String codePostal;
    @XmlElement(name = "CodeCedex")
    protected BigInteger codeCedex;
    @XmlElement(name = "Ville")
    protected String ville;
    @XmlElement(name = "Pays")
    protected String pays;
    @XmlElement(name = "Batiment")
    protected String batiment = "";
    @XmlElement(name = "Etage")
    protected String etage = "";
    @XmlElement(name = "BoitePostale")
    protected String boitePostale = "";

    /**
     * Gets the value of the pointRemise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointRemise() {
        return pointRemise;
    }

    /**
     * Sets the value of the pointRemise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointRemise(String value) {
        this.pointRemise = value;
    }

    /**
     * Gets the value of the numeroVoie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroVoie() {
        return numeroVoie;
    }

    /**
     * Sets the value of the numeroVoie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroVoie(String value) {
        this.numeroVoie = value;
    }

    /**
     * Gets the value of the extensionIndiceRepetition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtensionIndiceRepetition() {
        return extensionIndiceRepetition;
    }

    /**
     * Sets the value of the extensionIndiceRepetition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtensionIndiceRepetition(String value) {
        this.extensionIndiceRepetition = value;
    }

    /**
     * Gets the value of the voie property.
     * 
     * @return
     *     possible object is
     *     {@link VoieType }
     *     
     */
    public String getVoie() {
        return voie;
    }

    /**
     * Sets the value of the voie property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoieType }
     *     
     */
    public void setVoie(String value) {
        this.voie = value;
    }

    /**
     * Gets the value of the ligneAdresse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLigneAdresse() {
        return ligneAdresse;
    }

    /**
     * Sets the value of the ligneAdresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLigneAdresse(String value) {
        this.ligneAdresse = value;
    }

    /**
     * Gets the value of the mentionsAdresseParticulieres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMentionsAdresseParticulieres() {
        return mentionsAdresseParticulieres;
    }

    /**
     * Sets the value of the mentionsAdresseParticulieres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMentionsAdresseParticulieres(String value) {
        this.mentionsAdresseParticulieres = value;
    }

    /**
     * Gets the value of the codePostal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getCodePostal() {
        return codePostal;
    }

    /**
     * Sets the value of the codePostal property.
     * 
     * @param string
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodePostal(String string) {
        this.codePostal = string;
    }

    /**
     * Gets the value of the codeCedex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodeCedex() {
        return codeCedex;
    }

    /**
     * Sets the value of the codeCedex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodeCedex(BigInteger value) {
        this.codeCedex = value;
    }

    /**
     * Gets the value of the ville property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVille() {
        return ville;
    }

    /**
     * Sets the value of the ville property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVille(String value) {
        this.ville = value;
    }

    /**
     * Gets the value of the pays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPays() {
        return pays;
    }

    /**
     * Sets the value of the pays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPays(String value) {
        this.pays = value;
    }

    public String getBatiment() {
        return batiment;
    }
    public void setBatiment(String value) {
        this.batiment = value;
    }
    public String getEtage() {
        return etage;
    }
    public void setEtage(String value) {
        this.etage= value;
    }

    public String getBoitePostale() {
        return boitePostale;
    }
    public void setBoitePostale(String value) {
        this.boitePostale= value;
    }

}
