//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 04:10:50 PM CEST 
//


package fr.capwebct.capdemat.plugins.externalservices.interconnexiondila.message;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Definition de l'enveloppe des envois de mail
 * 
 * <p>Java class for BatchMailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BatchMailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateBatchMail" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="NombreDemandesEnAttente" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="UrlBackOffice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Commentaire" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatchMailType", propOrder = {
    "dateBatchMail",
    "nombreDemandesEnAttente",
    "urlBackOffice",
    "commentaire"
})
public class BatchMailType {

    @XmlElement(name = "DateBatchMail", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar dateBatchMail;
    @XmlElement(name = "NombreDemandesEnAttente", required = true)
    protected BigInteger nombreDemandesEnAttente;
    @XmlElement(name = "UrlBackOffice", required = true)
    protected String urlBackOffice;
    @XmlElement(name = "Commentaire", required = true)
    protected String commentaire;

    /**
     * Gets the value of the dateBatchMail property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateBatchMail() {
        return dateBatchMail;
    }

    /**
     * Sets the value of the dateBatchMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateBatchMail(XMLGregorianCalendar value) {
        this.dateBatchMail = value;
    }

    /**
     * Gets the value of the nombreDemandesEnAttente property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNombreDemandesEnAttente() {
        return nombreDemandesEnAttente;
    }

    /**
     * Sets the value of the nombreDemandesEnAttente property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNombreDemandesEnAttente(BigInteger value) {
        this.nombreDemandesEnAttente = value;
    }

    /**
     * Gets the value of the urlBackOffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlBackOffice() {
        return urlBackOffice;
    }

    /**
     * Sets the value of the urlBackOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlBackOffice(String value) {
        this.urlBackOffice = value;
    }

    /**
     * Gets the value of the commentaire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommentaire() {
        return commentaire;
    }

    /**
     * Sets the value of the commentaire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommentaire(String value) {
        this.commentaire = value;
    }

}
