//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 04:10:50 PM CEST 
//


package fr.capwebct.capdemat.plugins.externalservices.interconnexiondila.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Lieu de naissance d'un individu (Departement + Commune + Code Postal)
 * 
 * <p>Java class for LieuNaissanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LieuNaissanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Commune" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}VilleType"/>
 *         &lt;element name="Adresse" type="{http://www.message.interconnexiondila.externalservices.plugins.capdemat.capwebct.fr}AdressePostaleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LieuNaissanceType", propOrder = {
    "commune",
    "adresse"
})
public class LieuNaissanceType {

    @XmlElement(name = "Commune", required = true)
    protected String commune;
    @XmlElement(name = "Adresse", required = true)
    protected AdressePostaleType adresse;

    /**
     * Gets the value of the commune property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommune() {
        return commune;
    }

    /**
     * Sets the value of the commune property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommune(String value) {
        this.commune = value;
    }

    /**
     * Gets the value of the adresse property.
     * 
     * @return
     *     possible object is
     *     {@link AdressePostaleType }
     *     
     */
    public AdressePostaleType getAdresse() {
        return adresse;
    }

    /**
     * Sets the value of the adresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdressePostaleType }
     *     
     */
    public void setAdresse(AdressePostaleType value) {
        this.adresse = value;
    }

}
