//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 04:10:50 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
	namespace = "http://www.tempuri.org/ec#", 
    xmlns = {
            @javax.xml.bind.annotation.XmlNs( prefix = "xsi",
                     namespaceURI="http://www.w3.org/2001/XMLSchema-instance")
           }, 
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.capwebct.capdemat.plugins.externalservices.interconnexiondila.message;
