function checkAllConditions() {
	checkStage2()
	checkStage1();
}


function checkStage1() {
	checkRequesterProfileAdult();
	checkAdultLegalAccess();
	checkRequesterProfileLessThan20();
	checkLessThan18();	
	checkAdultLegalPrecision();
	checkLessThan20FatherReductionRatio();
	checkLessThan20MotherReductionRatio();
}

function checkStage2() {
	checkDwellingPrecision();
	checkDwellingEstablishmentReception();
	checkDwellingSocialReception();
}

function checkRequesterProfileAdult() {
	// value "har.requestInformationRequesterProfile == 'Adult'"
	labels=document.getElementById('tab1').getElementsByTagName("label");
	if (document.forms[0].requestInformationRequesterProfile.value == "Adult") {
		// On affiche les conditionSubscribers
		document.getElementById('adultRequester').style.display = "block";
		document.getElementById('adultLegalAccessPresence').style.display = "block";
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "adultLegalAccessPresence")  {
				labels[i].style.display = "block";
			}	
		}
	} else {
		// On affiche pas les conditionSubscribers
		document.getElementById('adultRequester').style.display = "none";
		// Don't display a yesno
		document.getElementById('adultLegalAccessPresence').style.display = "none";
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "adultLegalAccessPresence")  {
				labels[i].style.display = "none";
			}	
		}
	}
}

function checkRequesterProfileLessThan20() {
	// value "har.requestInformationRequesterProfile == 'LessThan20'"
	if (document.forms[0].requestInformationRequesterProfile.value == "LessThan20") {
		// On affiche les conditionSubscribers
		document.getElementById('lessThan20Requester').style.display = "block";
		document.getElementById('lessThan20Referent').style.display = "block";
	} else {
		// On affiche pas les conditionSubscribers
		document.getElementById('lessThan20Requester').style.display = "none";
		document.getElementById('lessThan20Referent').style.display = "none";
	}
}

function checkAdultLegalAccess() {
	// value har.requestInformationRequesterProfile == 'Adult' && har.adultLegalAccessPresence == true"
	if ((document.forms[0].requestInformationRequesterProfile.value == 'Adult')  
		&& (document.forms[0].adultLegalAccessPresence[0].checked))	{
		document.getElementById('adultLegalAccess').style.display = "block";
	} else {
		document.getElementById('adultLegalAccess').style.display = "none";
	}
}

function checkLessThan18 () {
	var display = false;
	var lessThan20RequesterBirthDate = document.forms[0].lessThan20RequesterBirthDate.value;	
	if (document.forms[0].requestInformationRequesterProfile.value == 'LessThan20' && lessThan20RequesterBirthDate != null) {	
		date = lessThan20RequesterBirthDate.split("/");
		var d = new Date();
		d.setDate(date[0]);
		d.setMonth(date[1] - 1);
		d.setFullYear(date[2]);
		dateLessY18 = getNowLessY18();
		if (d.getTime() > dateLessY18.getTime()) display = true;
	}
	if (display == true) {
		document.getElementById('lessThan20Father').style.display = "block";
		document.getElementById('lessThan20Mother').style.display = "block";
		document.getElementById('lessThan20LegalRepresentative').style.display = "block";
		document.getElementById('lessThan20LegalParentalAuthority').style.display = "block";
	} else {
		document.getElementById('lessThan20Father').style.display = "none";
		document.getElementById('lessThan20Mother').style.display = "none";
		document.getElementById('lessThan20LegalRepresentative').style.display = "none";
		document.getElementById('lessThan20LegalParentalAuthority').style.display = "none";
	}
}

function getNowLessY18 () {
	// generated by now - D0M0Y18 ou Y18
	y = 18;
	date = new Date();
	var dateLessY18 = new Date();
	dateLessY18.setFullYear(date.getFullYear() - y);
	return dateLessY18;
}

function checkAdultLegalPrecision () {
	labels=document.getElementById('tab1').getElementsByTagName("label");
	if (document.forms[0].requestInformationRequesterProfile.value == "Adult" && document.forms[0].adultLegalAccessPresence[0].checked == true 
		&& document.forms[0].adultLegalAccessRepresentativeKind.value == "Other"){
		document.forms[0].adultLegalAccessRepresentativePrecision.style.display = "block"
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "adultLegalAccessRepresentativePrecision")  {
				labels[i].style.display = "block";
			}	
		}
	} else {
		document.forms[0].adultLegalAccessRepresentativePrecision.style.display = "none"
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "adultLegalAccessRepresentativePrecision")  {
				labels[i].style.display = "none";
			}	
		}
	}
}

function checkLessThan20FatherReductionRatio() {
	var display = false;
	labels=document.getElementById('tab1').getElementsByTagName("label");
	var lessThan20RequesterBirthDate = document.forms[0].lessThan20RequesterBirthDate.value;
	if (document.forms[0].requestInformationRequesterProfile.value == 'LessThan20' && lessThan20RequesterBirthDate != null 
		&& document.forms[0].lessThan20FatherActivityReduction[0].checked == true) {	
		date = lessThan20RequesterBirthDate.split("/");
		var d = new Date();
		d.setDate(date[0]);
		d.setMonth(date[1] - 1);
		d.setFullYear(date[2]);
		dateLessY18 = getNowLessY18();
		if (d.getTime() > dateLessY18.getTime()) display = true;
	}
	if (display == true) {
		document.forms[0].lessThan20FatherReductionRatio.style.display = "block";
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "lessThan20FatherReductionRatio")  {
				labels[i].style.display = "block";
			}	
		}
	} else {
		document.forms[0].lessThan20FatherReductionRatio.style.display = "none";
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "lessThan20FatherReductionRatio")  {
				labels[i].style.display = "none";
			}	
		}
	}
}

function checkLessThan20MotherReductionRatio() {
	var display = false;
	labels=document.getElementById('tab1').getElementsByTagName("label");
	var lessThan20RequesterBirthDate = document.forms[0].lessThan20RequesterBirthDate.value;
	if (document.forms[0].requestInformationRequesterProfile.value == 'LessThan20' && lessThan20RequesterBirthDate != null 
		&& document.forms[0].lessThan20MotherActivityReduction[0].checked == true) {	
		date = lessThan20RequesterBirthDate.split("/");
		var d = new Date();
		d.setDate(date[0]);
		d.setMonth(date[1] - 1);
		d.setFullYear(date[2]);
		dateLessY18 = getNowLessY18();
		if (d.getTime() > dateLessY18.getTime()) display = true;
	}
	if (display == true) {
		document.forms[0].lessThan20MotherReductionRatio.style.display = "block";
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "lessThan20MotherReductionRatio")  {
				labels[i].style.display = "block";
			}	
		}
	} else {
		document.forms[0].lessThan20MotherReductionRatio.style.display = "none";
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "lessThan20MotherReductionRatio")  {
				labels[i].style.display = "none";
			}	
		}
	}
}

function checkDwellingPrecision() {
	labels=document.getElementById('tab2').getElementsByTagName("label");
	if (document.forms[1].dwellingKind.value == "Other") {
		document.forms[1].dwellingPrecision.style.display = "block"
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "dwellingPrecision")  {
				labels[i].style.display = "block";
			}	
		}
	} else {
		document.forms[1].dwellingPrecision.style.display = "none"
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "dwellingPrecision")  {
				labels[i].style.display = "none";
			}	
		}
	}
}

function checkDwellingEstablishmentReception() {
	labels=document.getElementById('tab2').getElementsByTagName("label");
	if (document.forms[1].dwellingEstablishmentReception[0].checked == true) {
		document.forms[1].dwellingReceptionType.style.display = "block"
		document.forms[1].dwellingReceptionNaming.style.display = "block"
		document.getElementById('dwellingReceptionAddress').style.display = "block";
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "dwellingReceptionType" || labelFor == "dwellingReceptionNaming")  {
				labels[i].style.display = "block";
			}	
		}
	} else {
		document.forms[1].dwellingReceptionType.style.display = "none"
		document.forms[1].dwellingReceptionNaming.style.display = "none"
		document.getElementById('dwellingReceptionAddress').style.display = "none";
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "dwellingReceptionType" || labelFor == "dwellingReceptionNaming")  {
				labels[i].style.display = "none";
			}	
		}
	}
}

function checkDwellingSocialReception() {
	labels=document.getElementById('tab2').getElementsByTagName("label");
	if (document.forms[1].dwellingSocialReception[0].checked == true) {
		document.forms[1].dwellingSocialReceptionNaming.style.display = "block"
		document.getElementById('dwellingSocialReceptionAddress').style.display = "block";
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "dwellingSocialReceptionNaming")  {
				labels[i].style.display = "block";
			}	
		}
	} else {
		document.forms[1].dwellingSocialReceptionNaming.style.display = "none"
		document.getElementById('dwellingSocialReceptionAddress').style.display = "none";
		for (var i=0; i<labels.length; i++)
		{
			labelFor = labels[i].htmlFor;
			if (labelFor == "dwellingSocialReceptionNaming")  {
				labels[i].style.display = "none";
			}	
		}
	}
}


// **********************************************************************************
YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-requestInformationRequesterProfile", "select" ),
        "change", 
        checkRequesterProfileAdult
    );
    
YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-requestInformationRequesterProfile", "select" ),
        "change", 
        checkRequesterProfileLessThan20
    );

YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-adultLegalAccessPresence", "input" ),
        "change", 
        checkAdultLegalAccess
    );
 
YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-requestInformationRequesterProfile", "select" ),
        "change", 
        checkAdultLegalAccess
    );
     
YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-lessThan20RequesterBirthDate", "input" ),
        "change", 
        checkLessThan18
    );
    
YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-requestInformationRequesterProfile", "select" ),
        "change", 
        checkLessThan18
    );
    
YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-adultLegalAccessRepresentativeKind", "select" ),
        "change", 
        checkAdultLegalPrecision
    );
    
YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-lessThan20FatherActivityReduction", "input" ),
        "change", 
        checkLessThan20FatherReductionRatio
    );
    
YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-lessThan20MotherActivityReduction", "input" ),
        "change", 
        checkLessThan20MotherReductionRatio
    );
    
YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-dwellingKind", "select" ),
        "change", 
        checkDwellingPrecision
    );

YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-dwellingEstablishmentReception", "input" ),
        "change", 
        checkDwellingEstablishmentReception
    );

YAHOO.util.Event.addListener(
        YAHOO.util.Dom.getElementsByClassName("condition-dwellingSocialReception", "input" ),
        "change", 
        checkDwellingSocialReception
    );
    

    
YAHOO.util.Event.onDOMReady(checkAllConditions); 
