<rule-set name="Régles de navigation des portlets standard"
          	xmlns="http://drools.org/rules"
          	xmlns:groovy="http://drools.org/semantics/groovy"
          	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          	xs:schemaLocation="http://drools.org/rules rules.xsd http://drools.org/semantics/groovy groovy.xsd">
          	
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Local Login JAAS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

	<rule name="Connexion">
		<parameter identifier="url">
			<groovy:class>com.zenexity.pict.portal.PictURL</groovy:class>
		</parameter>
		<parameter identifier="portalAPI">
			<groovy:class>com.zenexity.pict.portal.rules.PortalAPI</groovy:class>
		</parameter>
		<groovy:condition>url.semantic</groovy:condition>
		<groovy:condition>url.semanticURL ==~ "/cvq/fo-login"</groovy:condition>
		<groovy:consequence>
			try {
			    portalAPI.login(url.semanticParams['username'], url.semanticParams['password']);
			} catch(Exception e) {
				e.printStackTrace();
				def params = ['error':e.message, 'username':url.semanticParams['username']];
				
				for( entity in portalAPI.searchEntities("com.zenexity.pict.cvq.fo-login") ) {
					authenticationWindows = portalAPI.searchWindows(entity);
					for(window in authenticationWindows) {
						portalAPI.processAction(window, params);
						portalAPI.changePage(window.page);
					}
				}
				
				return
			}

			def params = ['init':'init', 'username':url.semanticParams['username']];
			for( entity in portalAPI.searchEntities("com.zenexity.pict.cvq.fo-login") ) {
				authenticationWindows = portalAPI.searchWindows(entity);
				for(window in authenticationWindows) {
					portalAPI.processAction(window, params);
				}
			}

		    portalAPI.redirect('/foyer');
		</groovy:consequence>
	</rule>

	<rule name="Deconnexion">
		<parameter identifier="url">
			<groovy:class>com.zenexity.pict.portal.PictURL</groovy:class>
		</parameter>
		<parameter identifier="portalAPI">
			<groovy:class>com.zenexity.pict.portal.rules.PortalAPI</groovy:class>
		</parameter>
	    <parameter identifier="principal"><groovy:class>com.zenexity.pict.portal.security.PictPrincipal</groovy:class></parameter>
		<groovy:condition>url.semantic</groovy:condition>
		<groovy:condition>url.semanticURL ==~ "/cvq/fo-logout"</groovy:condition>
		<groovy:consequence>
			def params = ['release':'release'];
				
			for( entity in portalAPI.searchEntities("com.zenexity.pict.cvq.fo-login") ) {
				authenticationWindows = portalAPI.searchWindows(entity);
				for(window in authenticationWindows) {
					portalAPI.processAction(window, params);
				}
			}
				
			portalAPI.logout();
			portalAPI.redirect('/accueil');
		</groovy:consequence>
	</rule>

  	<rule name="Navigation categories de demandes">
    		<parameter identifier="url">
      			<groovy:class>com.zenexity.pict.portal.PictURL</groovy:class>
    		</parameter>
    		<parameter identifier="portalAPI">
      			<groovy:class>com.zenexity.pict.portal.rules.PortalAPI</groovy:class>
    		</parameter>
    		<parameter identifier="rulesSession">
    	  		<groovy:class>com.zenexity.pict.portal.rules.RulesSession</groovy:class>
    		</parameter>
    		<groovy:condition>url.semantic</groovy:condition>
    		<groovy:condition>url.semanticURL ==~ "/cvq/requests/category.*"</groovy:condition>
    		<groovy:consequence>
    	  		rulesSession['requestCreationMode'] = null;

    	 		requestedState = url.semanticParams['requestedState']
	  
      			for(portlet in portalAPI.searchEntities('com.zenexity.pict.cvq.fo-requests-syn')) {
          			for(window in portalAPI.searchWindows(portlet)) {
            				params = ['requestedState':requestedState ]
            				portalAPI.processAction(window, params)
          			}
      			}
	  
      			for(portlet in portalAPI.searchEntities('com.zenexity.pict.cvq.fo-requests-list')) {
            			for(window in portalAPI.searchWindows(portlet)) {
                			params = ['requestedState':requestedState ]
                			portalAPI.processAction(window, params)
                			portalAPI.changePage(window.page)
            			}
      			}
    		</groovy:consequence>
  	</rule>
  
  	<rule name="Navigation detail adultes et enfants">
    		<parameter identifier="url">
      			<groovy:class>com.zenexity.pict.portal.PictURL</groovy:class>
    		</parameter>
    		<parameter identifier="portalAPI">
      			<groovy:class>com.zenexity.pict.portal.rules.PortalAPI</groovy:class>
    		</parameter>
    		<parameter identifier="rulesSession">
    	  		<groovy:class>com.zenexity.pict.portal.rules.RulesSession</groovy:class>
    		</parameter>
    		<groovy:condition>url.semantic</groovy:condition>
    		<groovy:condition>url.semanticURL ==~ "/cvq/individu/details.*"</groovy:condition>
    
    		<groovy:consequence>
    	  		idAdult      = url.semanticParams['idAdult']
    	  		idChild      = url.semanticParams['idChild']
    	  		homeFolderId = url.semanticParams['homeFolderId']
    	  		

      			for(portlet in portalAPI.searchEntities('com.zenexity.pict.cvq.fo-individuals-detail')) {
      
            			for(window in portalAPI.searchWindows(portlet)) {
               				params = ['homeFolderId':homeFolderId]
               				if(idAdult != null){
                
                				params = ['idAdult':idAdult]
                
                			}else if(idChild != null){
               
               					params = ['idChild':idChild]
                			}
                
                			portalAPI.processAction(window, params)
                			portalAPI.changePage(window.page)
            			}
      			}
      			for(portlet in portalAPI.searchEntities('com.zenexity.pict.cvq.fo-folder-document-syn')) {
      
            			for(window in portalAPI.searchWindows(portlet)) {
               
               				if(idAdult != null){
                
                				params = ['idAdult':idAdult]
                
                			}else if(idChild != null){
               
               					params = ['idChild':idChild]
                			}
                			portalAPI.processAction(window, params)
                			portalAPI.changePage(window.page)
            			}
      			}
			for(portlet in portalAPI.searchEntities('com.zenexity.pict.cvq.fo-document-display-syn')) {
      
            			for(window in portalAPI.searchWindows(portlet)) {
               
                				params = ['homeFolderId':homeFolderId]
                
                			portalAPI.processAction(window, params)
                			portalAPI.changePage(window.page)
            			}
      			}
      
    		</groovy:consequence>
  	</rule>

   <rule name="Suppresion d'un individu">
    		<parameter identifier="url">
      			<groovy:class>com.zenexity.pict.portal.PictURL</groovy:class>
    		</parameter>
    		<parameter identifier="portalAPI">
      			<groovy:class>com.zenexity.pict.portal.rules.PortalAPI</groovy:class>
    		</parameter>
    		<parameter identifier="rulesSession">
    	  		<groovy:class>com.zenexity.pict.portal.rules.RulesSession</groovy:class>
    		</parameter>
    		<groovy:condition>url.semantic</groovy:condition>
    		<groovy:condition>url.semanticURL ==~ "/cvq/individu/deletion.*"</groovy:condition>
    
    		<groovy:consequence>
    	  		idAdult      = url.semanticParams['idAdult']
    	  		idChild		 = url.semanticParams['idChild']
    	  		supprim      = url.semanticParams['supprim']
    	  		homeFolderId = url.semanticParams['homeFolderId']
    	  		
      			for(portlet in portalAPI.searchEntities('com.zenexity.pict.cvq.fo-individuals-detail')) {
      
            			for(window in portalAPI.searchWindows(portlet)) {
               				params = ['supprim':supprim,'homeFolderId':homeFolderId]
               				if(idAdult != null){
                
                				params.put("idAdult",idAdult); 
                
                			}else if(idChild != null){
               
               					params.put("idChild",idChild);
                			}
                
                			portalAPI.processAction(window, params)
                			portalAPI.changePage(window.page)
            			}
      			}
      			for(portlet in portalAPI.searchEntities('com.zenexity.pict.cvq.fo-folder-document-syn')) {
      
            			for(window in portalAPI.searchWindows(portlet)) {
               
               				if(idAdult != null){
                
                				params = ['idAdult':idAdult]
                
                			}else if(idChild != null){
               
               					params = ['idChild':idChild]
                			}
                			portalAPI.processAction(window, params)
                			portalAPI.changePage(window.page)
            			}
      			}
			for(portlet in portalAPI.searchEntities('com.zenexity.pict.cvq.fo-document-display-syn')) {
      
            			for(window in portalAPI.searchWindows(portlet)) {
               
                				params = ['homeFolderId':homeFolderId]
                
                			portalAPI.processAction(window, params)
                			portalAPI.changePage(window.page)
            			}
      			}
    		</groovy:consequence>
  	</rule>
  	<rule name="Affichage justificatifs">
    		<parameter identifier="url">
      			<groovy:class>com.zenexity.pict.portal.PictURL</groovy:class>
    		</parameter>
    		<parameter identifier="portalAPI">
     	 		<groovy:class>com.zenexity.pict.portal.rules.PortalAPI</groovy:class>
    		</parameter>
    		<parameter identifier="rulesSession">
    	  		<groovy:class>com.zenexity.pict.portal.rules.RulesSession</groovy:class>
    		</parameter>
    		<groovy:condition>url.semantic</groovy:condition>
    		<groovy:condition>url.semanticURL ==~ "/cvq/documents.*"</groovy:condition>
    
    		<groovy:consequence>
    	  		documentId = url.semanticParams['documentId']
    	  		name = url.semanticParams['name']

      			for(portlet in portalAPI.searchEntities('com.zenexity.pict.cvq.fo-document-display-syn')) {
      
            			for(window in portalAPI.searchWindows(portlet)) {
                
                			params = ['documentId':documentId,'name':name]
              		
                			portalAPI.processAction(window, params)
                			portalAPI.changePage(window.page)
            			}
      			}
    		</groovy:consequence>
  	</rule>
  
  	<rule name="Navigation modification adultes et enfants">
    		<parameter identifier="url">
      			<groovy:class>com.zenexity.pict.portal.PictURL</groovy:class>
    		</parameter>
    		<parameter identifier="portalAPI">
      			<groovy:class>com.zenexity.pict.portal.rules.PortalAPI</groovy:class>
    		</parameter>
    		<parameter identifier="rulesSession">
    	  		<groovy:class>com.zenexity.pict.portal.rules.RulesSession</groovy:class>
    		</parameter>
    	
    		<groovy:condition>url.semantic</groovy:condition>
    		<groovy:condition>url.semanticURL ==~ "/cvq/individu/modif.*"</groovy:condition>
    
    		<groovy:consequence>
    
    	  		isAdult = url.semanticParams['isAdult']
    	  		id = url.semanticParams['id']
    	  		lastName = url.semanticParams['lastname']
    	  		firstname1= url.semanticParams['firstname1']
    	  		firstname2= url.semanticParams['firstname2']
    	  		firstname3= url.semanticParams['firstname3']
    	  		birthDate = url.semanticParams['birthDate']
    	  		birthCity = url.semanticParams['birthCity']
    	  		birthPostalCode = url.semanticParams['birthPostalCode']
    	  		sex = url.semanticParams['sex']
    	  		adress = url.semanticParams['adress']
    	  		city = url.semanticParams['city']
    	  		postalCode = url.semanticParams['postalCode']

      			for(portlet in portalAPI.searchEntities('com.zenexity.pict.cvq.fo-individuals-modif')) {
      
            			for(window in portalAPI.searchWindows(portlet)) {
                
                			params = ['isAdult':isAdult,'id':id,'lastname':lastName,'firstname1':firstname1,'firstname2':firstname2,'sex':sex,
                		  		  'firstname3':firstname3,'birthDate':birthDate,'birthCity':birthCity,'birthPostalCode':birthPostalCode,
                		  		  'adress':adress,'city':city,'postalCode':postalCode] ;

                			portalAPI.processAction(window, params) ;
                			portalAPI.changePage(window.page)       ;
            			}
      			}
    		</groovy:consequence>
  	</rule>
  
  	<rule name="Passage en mode remplissage de formulaire">
    		<parameter identifier="url">
      			<groovy:class>com.zenexity.pict.portal.PictURL</groovy:class>
    		</parameter>
    		<parameter identifier="portalAPI">
      			<groovy:class>com.zenexity.pict.portal.rules.PortalAPI</groovy:class>
    		</parameter>
    		<parameter identifier="rulesSession">
    	  		<groovy:class>com.zenexity.pict.portal.rules.RulesSession</groovy:class>
    		</parameter>
    		<groovy:condition>url.semantic</groovy:condition>
    		<groovy:condition>url.semanticURL ==~ "/cvq/requests/create"</groovy:condition>
    		<groovy:consequence>
    	  		rulesSession['requestCreationMode'] = true;

      			for(portlet in portalAPI.searchEntities('com.zenexity.pict.cvq.fo-requests-create')) {
            			for(window in portalAPI.searchWindows(portlet)) {
                			portalAPI.processAction(window, [:])
                			portalAPI.changePage(window.page)
            			}
      			}
    		</groovy:consequence>
  	</rule>
	
</rule-set>
