<gestionCompte>
  <compteExtranet>
    <msNom></msNom>
    <msPrenom></msPrenom>
    <msFonction/>
    <mdtDateEntree></mdtDateEntree>
    <msTitre/>
    <msQualite></msQualite>
    <moAdresse/>
    <login></login>
    <password></password>
  </compteExtranet>
  <tiers>
    <msNom>${lastName.encodeAsXML()}</msNom>
    <msLib>${lastName.encodeAsXML()}</msLib>
    <msSiret/>
    <mbActivationSeuil>true</mbActivationSeuil>
    <mvAdresses>
      <CTierAdresseVO>
        <msVoie>${address.streetNumber.encodeAsXML()} ${address.streetName.encodeAsXML()}</msVoie>
        <msComplement>${address.additionalDeliveryInformation.encodeAsXML()}</msComplement>
        <miBoitePostale/>
        <msCodePostal>${address.postalCode.encodeAsXML()}</msCodePostal>
        <msVille>${address.city.encodeAsXML()}</msVille>
        <miCedex/>
        <msPays>${address.countryName.encodeAsXML()}</msPays>
        <msTel>${phone.encodeAsXML()}</msTel>
        <msFax/>
        <msMail>${email.encodeAsXML()}</msMail>
        <mbUsuel>true</mbUsuel>
      </CTierAdresseVO>
    </mvAdresses>
    <mvReferencesBancaires>
      <CTierReferenceBancaireVO>
        <moModePaiement>
          <msDescription>Virement bancaire</msDescription>
        </moModePaiement>
        <moAgence>
          <miBanque>${bankCode.encodeAsXML()}</miBanque>
          <miAgence>${counterCode.encodeAsXML()}</miAgence>
          <msLibelle></msLibelle>
        </moAgence>
        <msCompte>${accountNumber.encodeAsXML()}</msCompte>
        <miCleRib>${accountKey.encodeAsXML()}</miCleRib>
        <mbEtranger>false</mbEtranger>
        <mbIban>false</mbIban>
        <mbUsuel>true</mbUsuel>
        <msIntitule/>
      </CTierReferenceBancaireVO>
    </mvReferencesBancaires>
    <PersonnePhysique>
      <msQualite>${title.encodeAsXML()}</msQualite>
      <msPrenom>${firstName.encodeAsXML()}</msPrenom>
      <msJeuneFille/>
      <msLieuNaissance>${birthPlace.encodeAsXML()}</msLieuNaissance>
      <mdtDateNaissance>${birthDate.encodeAsXML()}</mdtDateNaissance>
    </PersonnePhysique>
  </tiers>
  <traitement>C</traitement>
</gestionCompte>