<rechercheTiers>
<nom>${lastName}</nom>
<prenom>${firstName}</prenom>
<codeTiers></codeTiers>
<codePostal>${postalCode}</codePostal>
<ville></ville>
<infosSIRETCODIC>
 <type></type>
 <numero></numero>
</infosSIRETCODIC>
<infoRIB>
  <type>${type}</type>
  <numero>${numero}</numero>
</infoRIB>
<typeTiers></typeTiers>
</rechercheTiers>