
    alter table account 
        drop constraint FKB9D38A2D1EC32CFC;

    alter table account 
        drop constraint FKB9D38A2D3575AFD6;

    alter table account_detail 
        drop constraint FK196C2EA35EA1AD4A;

    alter table account_detail 
        drop constraint FK196C2EA3F624C47E;

    alter table capwebct_association_summary 
        drop constraint FKF44375DC338E0F2C;

    alter table capwebct_individual 
        drop constraint FKB084425A4B95144;

    alter table contract 
        drop constraint FKDE351112674D4DEA;

    alter table contract 
        drop constraint FKDE3511121EC32CFC;

    alter table contract 
        drop constraint FKDE3511123575AFD6;

    alter table contract_detail 
        drop constraint FK3FD50C1E28AA4E0;

    alter table contract_detail 
        drop constraint FK3FD50C1EF624C47E;

    alter table external_application_broker 
        drop constraint FK839CD69CC0CF33BD;

    alter table external_family_account 
        drop constraint FKAB778346C0CF3367;

    alter table external_family_account 
        drop constraint FKAB778346338E0ED6;

    alter table external_import_audit 
        drop constraint FK94EB2AB54F731E9E;

    alter table external_individual 
        drop constraint FKC1D4D78D3575AFD6;

    alter table external_individual 
        drop constraint FKC1D4D78D4B60FB31;

    alter table invoice 
        drop constraint FK74D6432D1EC32CFC;

    alter table invoice 
        drop constraint FK74D6432D3575AFD6;

    alter table invoice 
        drop constraint FK74D6432DF624C47E;

    alter table invoice_detail 
        drop constraint FK119755A36BF85F4A;

    drop table account if exists;

    drop table account_detail if exists;

    drop table agent if exists;

    drop table capwebct_association_summary if exists;

    drop table capwebct_family_account if exists;

    drop table capwebct_individual if exists;

    drop table contract if exists;

    drop table contract_detail if exists;

    drop table external_application if exists;

    drop table external_application_broker if exists;

    drop table external_family_account if exists;

    drop table external_import_audit if exists;

    drop table external_individual if exists;

    drop table invoice if exists;

    drop table invoice_detail if exists;

    drop table payment if exists;

    create table account (
        id bigint generated by default as identity (start with 1),
        account_id varchar(255),
        account_value integer,
        account_label varchar(255),
        account_date timestamp,
        broker varchar(255),
        efa_fk bigint not null,
        external_family_account_fk bigint not null,
        primary key (id)
    );

    create table account_detail (
        id bigint generated by default as identity (start with 1),
        holder_name varchar(255),
        holder_surname varchar(255),
        value integer,
        payment_fk bigint,
        account_fk_id bigint,
        account_detail_index integer,
        primary key (id)
    );

    create table agent (
        id bigint generated by default as identity (start with 1),
        login varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        is_admin bit,
        primary key (id),
        unique (login)
    );

    create table capwebct_association_summary (
        capwebct_family_account_id bigint not null,
        external_application_id bigint not null,
        state varchar(255) not null,
        primary key (capwebct_family_account_id, external_application_id, state)
    );

    create table capwebct_family_account (
        id bigint generated by default as identity (start with 1),
        capwebct_family_account_id bigint,
        address varchar(255),
        responsible_full_name varchar(255),
        primary key (id)
    );

    create table capwebct_individual (
        id bigint generated by default as identity (start with 1),
        capwebct_individual_id bigint,
        first_name varchar(255),
        last_name varchar(255),
        child bit,
        responsible bit,
        capwebct_family_account_fk_id bigint not null,
        primary key (id)
    );

    create table contract (
        id bigint generated by default as identity (start with 1),
        contract_id varchar(255),
        contract_label varchar(255),
        contract_value integer,
        contract_date timestamp,
        buy_price integer,
        buy_min integer,
        buy_max integer,
        broker varchar(255),
        efa_fk bigint not null,
        ei_fk bigint,
        external_family_account_fk bigint not null,
        primary key (id)
    );

    create table contract_detail (
        id bigint generated by default as identity (start with 1),
        quantity integer,
        price integer,
        amount integer,
        payment_fk bigint,
        contract_fk_id bigint,
        contract_detail_index integer,
        primary key (id)
    );

    create table external_application (
        id bigint generated by default as identity (start with 1),
        label varchar(255) not null,
        description varchar(255),
        primary key (id)
    );

    create table external_application_broker (
        external_application_id bigint not null,
        broker varchar(255) not null,
        primary key (external_application_id, broker)
    );

    create table external_family_account (
        id bigint generated by default as identity (start with 1),
        external_family_account_id varchar(255),
        address varchar(255),
        external_application_fk bigint not null,
        capwebct_family_account_fk bigint,
        primary key (id)
    );

    create table external_import_audit (
        id bigint generated by default as identity (start with 1),
        import_type varchar(255),
        external_data_type varbinary(255),
        external_application_label varchar(255),
        date timestamp,
        agent_fk bigint,
        primary key (id)
    );

    create table external_individual (
        id bigint generated by default as identity (start with 1),
        external_individual_id varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        responsible bit,
        capwebct_individual_fk bigint,
        external_family_account_fk bigint not null,
        primary key (id)
    );

    create table invoice (
        id bigint generated by default as identity (start with 1),
        invoice_id varchar(255),
        invoice_value integer,
        invoice_label varchar(255),
        invoice_date timestamp,
        invoice_expiration_date timestamp,
        invoice_payment_date timestamp,
        invoice_payed bit,
        broker varchar(255),
        efa_fk bigint not null,
        payment_fk bigint,
        external_family_account_fk bigint not null,
        primary key (id)
    );

    create table invoice_detail (
        id bigint generated by default as identity (start with 1),
        child_name varchar(255),
        child_surname varchar(255),
        label varchar(255),
        unit_price integer,
        quantity integer,
        value integer,
        invoice_fk_id bigint,
        invoice_detail_index integer,
        primary key (id)
    );

    create table payment (
        id bigint generated by default as identity (start with 1),
        payment_type varchar(255),
        payment_date timestamp,
        payment_amount integer,
        payment_ack varchar(255),
        cvq_ack varchar(255),
        cfa_id bigint,
        broker varchar(255),
        primary key (id)
    );

    alter table account 
        add constraint FKB9D38A2D1EC32CFC 
        foreign key (efa_fk) 
        references external_family_account;

    alter table account 
        add constraint FKB9D38A2D3575AFD6 
        foreign key (external_family_account_fk) 
        references external_family_account;

    alter table account_detail 
        add constraint FK196C2EA35EA1AD4A 
        foreign key (account_fk_id) 
        references account;

    alter table account_detail 
        add constraint FK196C2EA3F624C47E 
        foreign key (payment_fk) 
        references payment;

    alter table capwebct_association_summary 
        add constraint FKF44375DC338E0F2C 
        foreign key (capwebct_family_account_id) 
        references capwebct_family_account;

    alter table capwebct_individual 
        add constraint FKB084425A4B95144 
        foreign key (capwebct_family_account_fk_id) 
        references capwebct_family_account;

    alter table contract 
        add constraint FKDE351112674D4DEA 
        foreign key (ei_fk) 
        references external_individual;

    alter table contract 
        add constraint FKDE3511121EC32CFC 
        foreign key (efa_fk) 
        references external_family_account;

    alter table contract 
        add constraint FKDE3511123575AFD6 
        foreign key (external_family_account_fk) 
        references external_family_account;

    alter table contract_detail 
        add constraint FK3FD50C1E28AA4E0 
        foreign key (contract_fk_id) 
        references contract;

    alter table contract_detail 
        add constraint FK3FD50C1EF624C47E 
        foreign key (payment_fk) 
        references payment;

    alter table external_application_broker 
        add constraint FK839CD69CC0CF33BD 
        foreign key (external_application_id) 
        references external_application;

    alter table external_family_account 
        add constraint FKAB778346C0CF3367 
        foreign key (external_application_fk) 
        references external_application;

    alter table external_family_account 
        add constraint FKAB778346338E0ED6 
        foreign key (capwebct_family_account_fk) 
        references capwebct_family_account;

    alter table external_import_audit 
        add constraint FK94EB2AB54F731E9E 
        foreign key (agent_fk) 
        references agent;

    alter table external_individual 
        add constraint FKC1D4D78D3575AFD6 
        foreign key (external_family_account_fk) 
        references external_family_account;

    alter table external_individual 
        add constraint FKC1D4D78D4B60FB31 
        foreign key (capwebct_individual_fk) 
        references capwebct_individual;

    alter table invoice 
        add constraint FK74D6432D1EC32CFC 
        foreign key (efa_fk) 
        references external_family_account;

    alter table invoice 
        add constraint FK74D6432D3575AFD6 
        foreign key (external_family_account_fk) 
        references external_family_account;

    alter table invoice 
        add constraint FK74D6432DF624C47E 
        foreign key (payment_fk) 
        references payment;

    alter table invoice_detail 
        add constraint FK119755A36BF85F4A 
        foreign key (invoice_fk_id) 
        references invoice;
