-------------------
-- SQL OUTPUT FILE :
---------------------
-----------------;
-- UserSecurityProfile;
-----------------;
UPDATE user_security_rule SET profile = 'READ'  Where profile = 'Read';
UPDATE user_security_rule SET profile = 'WRITE'  Where profile = 'Write';
UPDATE user_security_rule SET profile = 'MANAGE'  Where profile = 'Manage';
-----------------;
-- UserAction;
-----------------;
UPDATE user_action SET type = 'CREATION'  Where type = 'Creation';
UPDATE user_action SET type = 'MODIFICATION'  Where type = 'Modification';
UPDATE user_action SET type = 'STATE_CHANGE'  Where type = 'StateChange';
UPDATE user_action SET type = 'QoS'  Where type = 'QoS';
UPDATE user_action SET type = 'CONTACT'  Where type = 'Contact';
UPDATE user_action SET type = 'DELETION'  Where type = 'Deletion';
-----------------;
-- DeathCertificateFormatType;
-----------------;
UPDATE death_details_request SET format = 'FULL_COPY'  Where format = 'FullCopy';
UPDATE death_details_request SET format = 'MULTILINGUAL_EXTRACT'  Where format = 'MultilingualExtract';
-----------------;
-- MarriageCertificateMotiveType;
-----------------;
UPDATE marriage_details_request SET motive = 'NOTARY_ACT'  Where motive = 'NotaryAct';
UPDATE marriage_details_request SET motive = 'FRENCH_NATIONALITY_CERTIFICATE'  Where motive = 'FrenchNationalityCertificate';
UPDATE marriage_details_request SET motive = 'MARITAL_REGIME_CHANGE'  Where motive = 'MaritalRegimeChange';
UPDATE marriage_details_request SET motive = 'FRENCH_NATIONALITY_ACQUISITION_DECLARATION'  Where motive = 'FrenchNationalityAcquisitionDeclaration';
UPDATE marriage_details_request SET motive = 'DIVORCE_SEPARATION'  Where motive = 'DivorceSeparation';
UPDATE marriage_details_request SET motive = 'PASSPORT'  Where motive = 'Passport';
UPDATE marriage_details_request SET motive = 'PENSION'  Where motive = 'Pension';
UPDATE marriage_details_request SET motive = 'OTHER'  Where motive = 'Other';
-----------------;
-- RsrContactKindType;
-----------------;
UPDATE remote_support_request SET contact_kind = 'REQUESTER'  Where contact_kind = 'Requester';
UPDATE remote_support_request SET contact_kind = 'OTHER'  Where contact_kind = 'Other';
-----------------;
-- MarriageCertificateFormatType;
-----------------;
UPDATE marriage_details_request SET format = 'FULL_COPY'  Where format = 'FullCopy';
UPDATE marriage_details_request SET format = 'EXTRACT_WITH_RELATIONSHIP'  Where format = 'ExtractWithRelationship';
UPDATE marriage_details_request SET format = 'EXTRACT_WITHOUT_RELATIONSHIP'  Where format = 'ExtractWithoutRelationship';
UPDATE marriage_details_request SET format = 'MULTILINGUAL_EXTRACT'  Where format = 'MultilingualExtract';
-----------------;
-- DepositType;
-----------------;
UPDATE document SET deposit_type = 'P_C'  Where deposit_type = 'PC';
UPDATE document SET deposit_type = 'TERMINAL'  Where deposit_type = 'Terminal';
UPDATE document SET deposit_type = 'MAILED_PAPER'  Where deposit_type = 'Mailed Paper';
UPDATE document SET deposit_type = 'BROUGHT_PAPER'  Where deposit_type = 'Brought Paper';
-----------------;
-- TrusteeType;
-----------------;
-----------------;
-- HccrSchoolingKindType;
-----------------;
UPDATE handicap_compensation_child_request SET schooling_schooling_kind = 'FULL_TIME'  Where schooling_schooling_kind = 'FullTime';
UPDATE handicap_compensation_child_request SET schooling_schooling_kind = 'PART_TIME'  Where schooling_schooling_kind = 'PartTime';
-----------------;
-- NationalityType;
-----------------;
UPDATE domestic_help_request SET dhr_spouse_nationality = 'FRENCH'  Where dhr_spouse_nationality = 'French';
UPDATE domestic_help_request SET dhr_spouse_nationality = 'EUROPEAN_UNION'  Where dhr_spouse_nationality = 'EuropeanUnion';
UPDATE domestic_help_request SET dhr_spouse_nationality = 'OUTSIDE_EUROPEAN_UNION'  Where dhr_spouse_nationality = 'OutsideEuropeanUnion';
-----------------;
-- ChoixSituationActuelle;
-----------------;
UPDATE day_care_center_registration_request SET situation_actuelle_mere = 'PLEIN'  Where situation_actuelle_mere = 'Plein';
UPDATE day_care_center_registration_request SET situation_actuelle_mere = 'PARTIEL'  Where situation_actuelle_mere = 'Partiel';
UPDATE day_care_center_registration_request SET situation_actuelle_mere = 'INTERIM'  Where situation_actuelle_mere = 'Interim';
UPDATE day_care_center_registration_request SET situation_actuelle_mere = 'ETUDIANT'  Where situation_actuelle_mere = 'Etudiant';
UPDATE day_care_center_registration_request SET situation_actuelle_mere = 'STAGE'  Where situation_actuelle_mere = 'Stage';
UPDATE day_care_center_registration_request SET situation_actuelle_mere = 'RECHERCHE'  Where situation_actuelle_mere = 'Recherche';
UPDATE day_care_center_registration_request SET situation_actuelle_mere = 'PARENT'  Where situation_actuelle_mere = 'Parent';
UPDATE day_care_center_registration_request SET situation_actuelle_mere = 'LIBRE'  Where situation_actuelle_mere = 'Libre';
UPDATE day_care_center_registration_request SET situation_actuelle_mere = 'CONGE'  Where situation_actuelle_mere = 'Conge';
UPDATE day_care_center_registration_request SET situation_actuelle_mere = 'RETRAITE'  Where situation_actuelle_mere = 'Retraite';
UPDATE day_care_center_registration_request SET situation_actuelle_mere = 'AUTRE'  Where situation_actuelle_mere = 'Autre';
-----------------;
-- ChoixSituationActuelle;
-----------------;
UPDATE day_care_center_registration_request SET situation_actuelle_pere = 'PLEIN'  Where situation_actuelle_pere = 'Plein';
UPDATE day_care_center_registration_request SET situation_actuelle_pere = 'PARTIEL'  Where situation_actuelle_pere = 'Partiel';
UPDATE day_care_center_registration_request SET situation_actuelle_pere = 'INTERIM'  Where situation_actuelle_pere = 'Interim';
UPDATE day_care_center_registration_request SET situation_actuelle_pere = 'ETUDIANT'  Where situation_actuelle_pere = 'Etudiant';
UPDATE day_care_center_registration_request SET situation_actuelle_pere = 'STAGE'  Where situation_actuelle_pere = 'Stage';
UPDATE day_care_center_registration_request SET situation_actuelle_pere = 'RECHERCHE'  Where situation_actuelle_pere = 'Recherche';
UPDATE day_care_center_registration_request SET situation_actuelle_pere = 'PARENT'  Where situation_actuelle_pere = 'Parent';
UPDATE day_care_center_registration_request SET situation_actuelle_pere = 'LIBRE'  Where situation_actuelle_pere = 'Libre';
UPDATE day_care_center_registration_request SET situation_actuelle_pere = 'CONGE'  Where situation_actuelle_pere = 'Conge';
UPDATE day_care_center_registration_request SET situation_actuelle_pere = 'RETRAITE'  Where situation_actuelle_pere = 'Retraite';
UPDATE day_care_center_registration_request SET situation_actuelle_pere = 'AUTRE'  Where situation_actuelle_pere = 'Autre';
-----------------;
-- MarriageRequesterQualityType;
-----------------;
UPDATE marriage_details_request SET requester_quality = 'REQUESTER'  Where requester_quality = 'Requester';
UPDATE marriage_details_request SET requester_quality = 'SPOUSE'  Where requester_quality = 'Spouse';
UPDATE marriage_details_request SET requester_quality = 'PARENT'  Where requester_quality = 'Parent';
UPDATE marriage_details_request SET requester_quality = 'GRAND_PARENT'  Where requester_quality = 'GrandParent';
UPDATE marriage_details_request SET requester_quality = 'CHILD'  Where requester_quality = 'Child';
UPDATE marriage_details_request SET requester_quality = 'LEGAL_REPRESENTANT'  Where requester_quality = 'LegalRepresentant';
UPDATE marriage_details_request SET requester_quality = 'AGENT'  Where requester_quality = 'Agent';
UPDATE marriage_details_request SET requester_quality = 'HEIR_FAMILY'  Where requester_quality = 'HeirFamily';
UPDATE marriage_details_request SET requester_quality = 'HEIR'  Where requester_quality = 'Heir';
UPDATE marriage_details_request SET requester_quality = 'AUTHORIZED'  Where requester_quality = 'Authorized';
UPDATE marriage_details_request SET requester_quality = 'LAWYER_NOTARY'  Where requester_quality = 'LawyerNotary';
UPDATE marriage_details_request SET requester_quality = 'OTHER'  Where requester_quality = 'Other';
-----------------;
-- ChildDiplomaType;
-----------------;
UPDATE military_census_request SET child_diploma = 'B_A_C'  Where child_diploma = 'BAC';
UPDATE military_census_request SET child_diploma = 'B_E_P'  Where child_diploma = 'BEP';
UPDATE military_census_request SET child_diploma = 'B_E_P_C'  Where child_diploma = 'BEPC';
UPDATE military_census_request SET child_diploma = 'BREVET'  Where child_diploma = 'Brevet';
UPDATE military_census_request SET child_diploma = 'C_F_G'  Where child_diploma = 'CFG';
UPDATE military_census_request SET child_diploma = 'C_A_P'  Where child_diploma = 'CAP';
UPDATE military_census_request SET child_diploma = 'D_A_E_U'  Where child_diploma = 'DAEU';
UPDATE military_census_request SET child_diploma = 'D_E_A'  Where child_diploma = 'DEA';
UPDATE military_census_request SET child_diploma = 'D_E_U_G'  Where child_diploma = 'DEUG';
UPDATE military_census_request SET child_diploma = 'LICENCE'  Where child_diploma = 'Licence';
UPDATE military_census_request SET child_diploma = 'MAITRISE'  Where child_diploma = 'Maitrise';
UPDATE military_census_request SET child_diploma = 'UNKNOWN'  Where child_diploma = 'Unknown';
-----------------;
-- DataState;
-----------------;
UPDATE request SET data_state = 'PENDING'  Where data_state = 'Pending';
UPDATE request SET data_state = 'VALID'  Where data_state = 'Valid';
UPDATE request SET data_state = 'INVALID'  Where data_state = 'Invalid';
-----------------;
-- ModeAccueilType;
-----------------;
UPDATE day_care_center_registration_request SET mode_accueil_choix_un = 'COLLECTIF'  Where mode_accueil_choix_un = 'Collectif';
UPDATE day_care_center_registration_request SET mode_accueil_choix_un = 'FAMILIAL'  Where mode_accueil_choix_un = 'Familial';
-----------------;
-- ChildSituationType;
-----------------;
UPDATE military_census_request SET child_situation = 'COLLEGE'  Where child_situation = 'College';
UPDATE military_census_request SET child_situation = 'HIGHSCHOOL'  Where child_situation = 'Highschool';
UPDATE military_census_request SET child_situation = 'STUDENT'  Where child_situation = 'Student';
UPDATE military_census_request SET child_situation = 'EMPLOYEE'  Where child_situation = 'Employee';
UPDATE military_census_request SET child_situation = 'APPRENTICE'  Where child_situation = 'Apprentice';
UPDATE military_census_request SET child_situation = 'OTHER'  Where child_situation = 'Other';
UPDATE military_census_request SET child_situation = 'UNKNOWN'  Where child_situation = 'Unknown';
-----------------;
-- HccrHomeSchoolingKindType;
-----------------;
UPDATE handicap_compensation_child_request SET schooling_home_schooling_kind = 'ALONE'  Where schooling_home_schooling_kind = 'Alone';
UPDATE handicap_compensation_child_request SET schooling_home_schooling_kind = 'ACCOMPANIED'  Where schooling_home_schooling_kind = 'Accompanied';
-----------------;
-- HcarDwellingReceptionKindType;
-----------------;
UPDATE handicap_compensation_adult_request SET dwelling_reception_type = 'INTERNSHIP'  Where dwelling_reception_type = 'Internship';
UPDATE handicap_compensation_adult_request SET dwelling_reception_type = 'CLERKSHIP'  Where dwelling_reception_type = 'Clerkship';
-----------------;
-- DepositOrigin;
-----------------;
UPDATE document SET deposit_origin = 'AGENT'  Where deposit_origin = 'Agent';
UPDATE document SET deposit_origin = 'E_CITIZEN'  Where deposit_origin = 'ECitizen';
-----------------;
-- DistanceType;
-----------------;
UPDATE study_grant_request SET distance = 'LESS_THAN30KMS'  Where distance = 'lessThan30kms';
UPDATE study_grant_request SET distance = 'BETWEEN30AND250KMS'  Where distance = 'between30and250kms';
UPDATE study_grant_request SET distance = 'MORE_THAN250KMS_AND_ABROAD'  Where distance = 'moreThan250kmsAndAbroad';
-----------------;
-- Version;
-----------------;
-----------------;
-- DhrRequestKindType;
-----------------;
UPDATE domestic_help_request SET dhr_request_kind = 'INDIVIDUAL'  Where dhr_request_kind = 'Individual';
UPDATE domestic_help_request SET dhr_request_kind = 'COUPLE'  Where dhr_request_kind = 'Couple';
-----------------;
-- HcarProfessionalStatusEnvironmentType;
-----------------;
UPDATE handicap_compensation_adult_request SET professional_status_environment = 'ORDINARY'  Where professional_status_environment = 'Ordinary';
UPDATE handicap_compensation_adult_request SET professional_status_environment = 'ADAPTED'  Where professional_status_environment = 'Adapted';
UPDATE handicap_compensation_adult_request SET professional_status_environment = 'PROTECTED'  Where professional_status_environment = 'Protected';
-----------------;
-- MappingState;
-----------------;
UPDATE external_home_folder SET mapping_state = 'FREE'  Where mapping_state = 'Free';
UPDATE external_home_folder SET mapping_state = 'BINDED'  Where mapping_state = 'Binded';
UPDATE external_home_folder SET mapping_state = 'IGNORED'  Where mapping_state = 'Ignored';
-----------------;
-- DhrGuardianMeasureType;
-----------------;
UPDATE domestic_help_request SET dhr_guardian_measure = 'SAFEGUARDING_JUSTICE'  Where dhr_guardian_measure = 'safeguardingJustice';
UPDATE domestic_help_request SET dhr_guardian_measure = 'GUARDIANSHIP'  Where dhr_guardian_measure = 'guardianship';
UPDATE domestic_help_request SET dhr_guardian_measure = 'CURATORSHIP'  Where dhr_guardian_measure = 'curatorship';
-----------------;
-- BirthCertificateMotiveType;
-----------------;
UPDATE birth_details_request SET motive = 'NOTARY_ACT'  Where motive = 'NotaryAct';
UPDATE birth_details_request SET motive = 'NATIONAL_IDENTITY_CARD'  Where motive = 'NationalIdentityCard';
UPDATE birth_details_request SET motive = 'FRENCH_NATIONALITY_CERTIFICATE'  Where motive = 'FrenchNationalityCertificate';
UPDATE birth_details_request SET motive = 'MARRIAGE'  Where motive = 'Marriage';
UPDATE birth_details_request SET motive = 'PACS'  Where motive = 'Pacs';
UPDATE birth_details_request SET motive = 'PASSPORT'  Where motive = 'Passport';
UPDATE birth_details_request SET motive = 'PENSION'  Where motive = 'Pension';
UPDATE birth_details_request SET motive = 'LEGAL_PROCEEDINGS'  Where motive = 'LegalProceedings';
UPDATE birth_details_request SET motive = 'OTHER'  Where motive = 'Other';
-----------------;
-- TitleType;
-----------------;
UPDATE adult SET title = 'MISTER'  Where title = 'Mister';
UPDATE adult SET title = 'MADAM'  Where title = 'Madam';
UPDATE adult SET title = 'MISS'  Where title = 'Miss';
UPDATE adult SET title = 'AGENCY'  Where title = 'Agency';
UPDATE adult SET title = 'UNKNOWN'  Where title = 'Unknown';
-----------------;
-- AncrRequesterQualityType;
-----------------;
UPDATE alignment_numbering_connection_request SET requester_quality = 'OWNER'  Where requester_quality = 'Owner';
UPDATE alignment_numbering_connection_request SET requester_quality = 'TENANT'  Where requester_quality = 'Tenant';
UPDATE alignment_numbering_connection_request SET requester_quality = 'CABINET'  Where requester_quality = 'Cabinet';
-----------------;
-- HccrPaymentAgencyBeneficiaryType;
-----------------;
UPDATE handicap_compensation_child_request SET payment_agency_beneficiary = 'C_A_F'  Where payment_agency_beneficiary = 'CAF';
UPDATE handicap_compensation_child_request SET payment_agency_beneficiary = 'M_S_A'  Where payment_agency_beneficiary = 'MSA';
UPDATE handicap_compensation_child_request SET payment_agency_beneficiary = 'OTHER'  Where payment_agency_beneficiary = 'Other';
UPDATE handicap_compensation_child_request SET payment_agency_beneficiary = 'NO_MEMBER_SHIP'  Where payment_agency_beneficiary = 'NoMemberShip';
-----------------;
-- ChoixDatePlacement;
-----------------;
UPDATE day_care_center_registration_request SET choix_type_date_placement_accueil_regulier = 'CONNUE'  Where choix_type_date_placement_accueil_regulier = 'Connue';
UPDATE day_care_center_registration_request SET choix_type_date_placement_accueil_regulier = 'POSSIBLE'  Where choix_type_date_placement_accueil_regulier = 'Possible';
-----------------;
-- MarriageRelationshipType;
-----------------;
UPDATE marriage_details_request SET relationship = 'HUSBAND'  Where relationship = 'Husband';
UPDATE marriage_details_request SET relationship = 'WIFE'  Where relationship = 'Wife';
-----------------;
-- MeansOfContactEnum;
-----------------;
UPDATE means_of_contact SET type = 'MAIL'  Where type = 'Mail';
UPDATE means_of_contact SET type = 'EMAIL'  Where type = 'Email';
UPDATE means_of_contact SET type = 'HOME_PHONE'  Where type = 'HomePhone';
UPDATE means_of_contact SET type = 'OFFICE_PHONE'  Where type = 'OfficePhone';
UPDATE means_of_contact SET type = 'MOBILE_PHONE'  Where type = 'MobilePhone';
UPDATE means_of_contact SET type = 'SMS'  Where type = 'Sms';
UPDATE means_of_contact SET type = 'LOCAL_AUTHORITY_OFFICE'  Where type = 'LocalAuthorityOffice';
-----------------;
-- PaymentMode;
-----------------;
UPDATE payment SET payment_mode = 'INTERNET'  Where payment_mode = 'Internet';
UPDATE payment SET payment_mode = 'CARD'  Where payment_mode = 'Card';
-----------------;
-- PaymentState;
-----------------;
UPDATE payment SET state = 'INITIALIZED'  Where state = 'Initialized';
UPDATE payment SET state = 'VALIDATED'  Where state = 'Validated';
UPDATE payment SET state = 'REFUSED'  Where state = 'Refused';
UPDATE payment SET state = 'CANCELLED'  Where state = 'Cancelled';
-----------------;
-- HcarHomeIntervenantKindType;
-----------------;
UPDATE hcar_home_intervenant SET home_intervenant_kind = 'CARER'  Where home_intervenant_kind = 'Carer';
UPDATE hcar_home_intervenant SET home_intervenant_kind = 'HOME_HELP'  Where home_intervenant_kind = 'HomeHelp';
UPDATE hcar_home_intervenant SET home_intervenant_kind = 'OTHER'  Where home_intervenant_kind = 'Other';
-----------------;
-- DeathCertificateMotiveType;
-----------------;
UPDATE death_details_request SET motive = 'NOTARY_ACT'  Where motive = 'NotaryAct';
UPDATE death_details_request SET motive = 'MARRIAGE'  Where motive = 'Marriage';
UPDATE death_details_request SET motive = 'PASSPORT'  Where motive = 'Passport';
UPDATE death_details_request SET motive = 'PENSION'  Where motive = 'Pension';
UPDATE death_details_request SET motive = 'OTHER'  Where motive = 'Other';
-----------------;
-- DocumentTypeValidity;
-----------------;
UPDATE document_type SET validity_duration_type = 'UNLIMITED'  Where validity_duration_type = 'Unlimited';
UPDATE document_type SET validity_duration_type = 'YEAR'  Where validity_duration_type = 'Year';
UPDATE document_type SET validity_duration_type = 'MONTH'  Where validity_duration_type = 'Month';
UPDATE document_type SET validity_duration_type = 'END_YEAR'  Where validity_duration_type = 'End Year';
UPDATE document_type SET validity_duration_type = 'END_SCHOOL_YEAR'  Where validity_duration_type = 'End School Year';
-----------------;
-- DocumentUsageType;
-----------------;
UPDATE document_type SET usage_type = 'REUSABLE'  Where usage_type = 'Reusable';
UPDATE document_type SET usage_type = 'SINGLE_USE'  Where usage_type = 'Single Use';
-----------------;
-- ChoixHorairesAccueilType;
-----------------;
UPDATE day_care_center_registration_request SET choix_horaires_accueil = 'INDIFFERENT'  Where choix_horaires_accueil = 'Indifferent';
UPDATE day_care_center_registration_request SET choix_horaires_accueil = 'REGULIER'  Where choix_horaires_accueil = 'Regulier';
UPDATE day_care_center_registration_request SET choix_horaires_accueil = 'IRREGULIER'  Where choix_horaires_accueil = 'Irregulier';
-----------------;
-- SectionType;
-----------------;
UPDATE perischool_activity_registration_request SET section = 'BEFORE_FIRST_SECTION'  Where section = 'BeforeFirstSection';
UPDATE perischool_activity_registration_request SET section = 'FIRST_SECTION'  Where section = 'FirstSection';
UPDATE perischool_activity_registration_request SET section = 'SECOND_SECTION'  Where section = 'SecondSection';
UPDATE perischool_activity_registration_request SET section = 'THIRD_SECTION'  Where section = 'ThirdSection';
UPDATE perischool_activity_registration_request SET section = 'C_P'  Where section = 'CP';
UPDATE perischool_activity_registration_request SET section = 'C_E1'  Where section = 'CE1';
UPDATE perischool_activity_registration_request SET section = 'C_E2'  Where section = 'CE2';
UPDATE perischool_activity_registration_request SET section = 'C_M1'  Where section = 'CM1';
UPDATE perischool_activity_registration_request SET section = 'C_M2'  Where section = 'CM2';
UPDATE perischool_activity_registration_request SET section = 'C_L_I_S_S'  Where section = 'CLISS';
UPDATE perischool_activity_registration_request SET section = 'UNKNOWN'  Where section = 'Unknown';
-----------------;
-- HccrDwellingReceptionKindType;
-----------------;
UPDATE handicap_compensation_child_request SET dwelling_reception_type = 'INTERNSHIP'  Where dwelling_reception_type = 'Internship';
UPDATE handicap_compensation_child_request SET dwelling_reception_type = 'CLERKSHIP'  Where dwelling_reception_type = 'Clerkship';
-----------------;
-- CurrentStudiesType;
-----------------;
UPDATE study_grant_request SET current_studies_diploma = 'LICENCE'  Where current_studies_diploma = 'licence';
UPDATE study_grant_request SET current_studies_diploma = 'LICENCE_PRO'  Where current_studies_diploma = 'licencePro';
UPDATE study_grant_request SET current_studies_diploma = 'MASTER'  Where current_studies_diploma = 'master';
UPDATE study_grant_request SET current_studies_diploma = 'BTS'  Where current_studies_diploma = 'bts';
UPDATE study_grant_request SET current_studies_diploma = 'DUT'  Where current_studies_diploma = 'dut';
UPDATE study_grant_request SET current_studies_diploma = 'OTHER_STUDIES'  Where current_studies_diploma = 'otherStudies';
-----------------;
-- SexType;
-----------------;
update child set sex = 'FEMALE' where sex = 'Female';
update child set sex = 'MALE' where sex = 'Male';
update child set sex = 'UNKNOWN' where sex = 'Unknown';
-----------------;
-- ScrRequesterQualityType;
-----------------;
UPDATE sewer_connection_request SET requester_quality = 'OWNER'  Where requester_quality = 'Owner';
UPDATE sewer_connection_request SET requester_quality = 'TENANT'  Where requester_quality = 'Tenant';
-----------------;
-- AcrRequesterQualityType;
-----------------;
UPDATE alignment_certificate_request SET requester_quality = 'OWNER'  Where requester_quality = 'Owner';
UPDATE alignment_certificate_request SET requester_quality = 'TENANT'  Where requester_quality = 'Tenant';
-----------------;
-- BirthCertificateFormatType;
-----------------;
UPDATE birth_details_request SET format = 'FULL_COPY'  Where format = 'FullCopy';
UPDATE birth_details_request SET format = 'EXTRACT_WITH_RELATIONSHIP'  Where format = 'ExtractWithRelationship';
UPDATE birth_details_request SET format = 'EXTRACT_WITHOUT_RELATIONSHIP'  Where format = 'ExtractWithoutRelationship';
UPDATE birth_details_request SET format = 'MULTILINGUAL_EXTRACT'  Where format = 'MultilingualExtract';
-----------------;
-- RsrSubjectResideWithType;
-----------------;
UPDATE remote_support_request SET subject_reside_with = 'ALONE'  Where subject_reside_with = 'Alone';
UPDATE remote_support_request SET subject_reside_with = 'COUPLE'  Where subject_reside_with = 'Couple';
UPDATE remote_support_request SET subject_reside_with = 'FAMILY'  Where subject_reside_with = 'Family';
-----------------;
-- HcarLegalAccessKindType;
-----------------;
UPDATE handicap_compensation_adult_request SET legal_access_kind = 'SAFEGUARDING_JUSTICE'  Where legal_access_kind = 'safeguardingJustice';
UPDATE handicap_compensation_adult_request SET legal_access_kind = 'GUARDIANSHIP'  Where legal_access_kind = 'guardianship';
UPDATE handicap_compensation_adult_request SET legal_access_kind = 'CURATORSHIP'  Where legal_access_kind = 'curatorship';
-----------------;
-- HccrReferentFamilyDependentActualSituationType;
-----------------;
UPDATE hccr_family_dependent SET referent_family_dependent_actual_situation = 'SCHOOLING'  Where referent_family_dependent_actual_situation = 'Schooling';
UPDATE hccr_family_dependent SET referent_family_dependent_actual_situation = 'LEARNING'  Where referent_family_dependent_actual_situation = 'Learning';
UPDATE hccr_family_dependent SET referent_family_dependent_actual_situation = 'MEDICO_SOCIAL'  Where referent_family_dependent_actual_situation = 'MedicoSocial';
-----------------;
-- HccrSocialSecurityMemberShipKindType;
-----------------;
UPDATE handicap_compensation_child_request SET social_security_member_ship_kind = 'INSURED'  Where social_security_member_ship_kind = 'Insured';
UPDATE handicap_compensation_child_request SET social_security_member_ship_kind = 'CLAIMANT'  Where social_security_member_ship_kind = 'Claimant';
UPDATE handicap_compensation_child_request SET social_security_member_ship_kind = 'NO_MEMBER_SHIP'  Where social_security_member_ship_kind = 'NoMemberShip';
-----------------;
-- RequestState;
-----------------;
UPDATE request_action SET resulting_state = 'DRAFT'  Where resulting_state = 'Draft';
UPDATE request_action SET resulting_state = 'PENDING'  Where resulting_state = 'Pending';
UPDATE request_action SET resulting_state = 'COMPLETE'  Where resulting_state = 'Complete';
UPDATE request_action SET resulting_state = 'UNCOMPLETE'  Where resulting_state = 'Uncomplete';
UPDATE request_action SET resulting_state = 'VALIDATED'  Where resulting_state = 'Validated';
UPDATE request_action SET resulting_state = 'NOTIFIED'  Where resulting_state = 'Notified';
UPDATE request_action SET resulting_state = 'CLOSED'  Where resulting_state = 'Closed';
UPDATE request_action SET resulting_state = 'REJECTED'  Where resulting_state = 'Rejected';
UPDATE request_action SET resulting_state = 'CANCELLED'  Where resulting_state = 'Cancelled';
UPDATE request_action SET resulting_state = 'ARCHIVED'  Where resulting_state = 'Archived';

update request_action set type = 'DRAFT_DELETE_NOTIFICATION' where type = 'DraftDeleteNotification';
update request_action set type = 'CREATION_NOTIFICATION' where type = 'CreationNotification';
update request_action set type = 'ORANGE_ALERT_NOTIFICATION' where type = 'OrangeAlertNotification';
update request_action set type = 'RED_ALERT_NOTIFICATION' where type = 'RedAlertNotification';
update request_action set type = 'CREATION' where type = 'Creation';
update request_action set type = 'STATE_CHANGE' where type = 'StateChange';
update request_action set type = 'CONTACT_CITIZEN' where type = 'ContactCitizen';

-----------------;
-- Type;
-----------------;
UPDATE document_action SET type = 'CREATION'  Where type = 'Creation';
UPDATE document_action SET type = 'STATE_CHANGE'  Where type = 'StateChange';
UPDATE document_action SET type = 'PAGE_ADDITION'  Where type = 'PageAddition';
UPDATE document_action SET type = 'PAGE_EDITION'  Where type = 'PageEdition';
UPDATE document_action SET type = 'PAGE_DELETION'  Where type = 'PageDeletion';
UPDATE document_action SET type = 'MERGE'  Where type = 'Merge';
-----------------;
-- BirthRequesterQualityType;
-----------------;
UPDATE birth_details_request SET requester_quality = 'REQUESTER'  Where requester_quality = 'Requester';
UPDATE birth_details_request SET requester_quality = 'SPOUSE'  Where requester_quality = 'Spouse';
UPDATE birth_details_request SET requester_quality = 'PARENT'  Where requester_quality = 'Parent';
UPDATE birth_details_request SET requester_quality = 'GRAND_PARENT'  Where requester_quality = 'GrandParent';
UPDATE birth_details_request SET requester_quality = 'CHILD'  Where requester_quality = 'Child';
UPDATE birth_details_request SET requester_quality = 'LEGAL_REPRESENTANT'  Where requester_quality = 'LegalRepresentant';
UPDATE birth_details_request SET requester_quality = 'AGENT'  Where requester_quality = 'Agent';
UPDATE birth_details_request SET requester_quality = 'HEIR_FAMILY'  Where requester_quality = 'HeirFamily';
UPDATE birth_details_request SET requester_quality = 'HEIR'  Where requester_quality = 'Heir';
UPDATE birth_details_request SET requester_quality = 'AUTHORIZED'  Where requester_quality = 'Authorized';
UPDATE birth_details_request SET requester_quality = 'LAWYER_NOTARY'  Where requester_quality = 'LawyerNotary';
UPDATE birth_details_request SET requester_quality = 'OTHER'  Where requester_quality = 'Other';
-----------------;
-- FamilyStatusType;
-----------------;
UPDATE adult SET family_status = 'SINGLE'  Where family_status = 'Single';
UPDATE adult SET family_status = 'DIVORCED'  Where family_status = 'Divorced';
UPDATE adult SET family_status = 'WIDOW'  Where family_status = 'Widow';
UPDATE adult SET family_status = 'MARRIED'  Where family_status = 'Married';
UPDATE adult SET family_status = 'COMMON_LAW_MARRIAGE'  Where family_status = 'CommonLawMarriage';
UPDATE adult SET family_status = 'PACS'  Where family_status = 'PACS';
UPDATE adult SET family_status = 'OTHER'  Where family_status = 'Other';
UPDATE adult SET family_status = 'SEPARATED'  Where family_status = 'Separated';
-----------------;
-- RequestStep;
-----------------;
UPDATE request SET request_step = 'INSTRUCTION'  Where request_step = 'Instruction';
UPDATE request SET request_step = 'DELIVERY'  Where request_step = 'Delivery';
-----------------;
-- HccrDwellingKindType;
-----------------;
UPDATE handicap_compensation_child_request SET dwelling_kind = 'PLACE_OF_RESIDENCE'  Where dwelling_kind = 'PlaceOfResidence';
UPDATE handicap_compensation_child_request SET dwelling_kind = 'THIRD_PARTY_PLACE_OF_RESIDENCE'  Where dwelling_kind = 'ThirdPartyPlaceOfResidence';
UPDATE handicap_compensation_child_request SET dwelling_kind = 'OTHER'  Where dwelling_kind = 'Other';
-----------------;
-- DhrPrincipalPensionPlanType;
-----------------;
UPDATE domestic_help_request SET dhr_principal_pension_plan = 'C_N_A_V'  Where dhr_principal_pension_plan = 'CNAV';
UPDATE domestic_help_request SET dhr_principal_pension_plan = 'M_S_A'  Where dhr_principal_pension_plan = 'MSA';
UPDATE domestic_help_request SET dhr_principal_pension_plan = 'C_R_A_M'  Where dhr_principal_pension_plan = 'CRAM';
UPDATE domestic_help_request SET dhr_principal_pension_plan = 'M_G_E_N'  Where dhr_principal_pension_plan = 'MGEN';
UPDATE domestic_help_request SET dhr_principal_pension_plan = 'S_N_C_F'  Where dhr_principal_pension_plan = 'SNCF';
UPDATE domestic_help_request SET dhr_principal_pension_plan = 'OTHER'  Where dhr_principal_pension_plan = 'Other';
-----------------;
-- DhrAssetTypeType;
-----------------;
UPDATE dhr_not_real_asset SET dhr_not_real_asset_type = 'SHARE'  Where dhr_not_real_asset_type = 'Share';
UPDATE dhr_not_real_asset SET dhr_not_real_asset_type = 'GIFT'  Where dhr_not_real_asset_type = 'Gift';
UPDATE dhr_not_real_asset SET dhr_not_real_asset_type = 'SALE'  Where dhr_not_real_asset_type = 'Sale';
-----------------;
-- CategoryProfile;
-----------------;
UPDATE agent_category_roles SET profile = 'MANAGER'  Where profile = 'Manager';
UPDATE agent_category_roles SET profile = 'READ_ONLY'  Where profile = 'R/O';
UPDATE agent_category_roles SET profile = 'READ_WRITE'  Where profile = 'R/W';
-----------------;
-- CurrentStudiesLevelType;
-----------------;
UPDATE study_grant_request SET current_studies_level = 'FIRST_YEAR'  Where current_studies_level = 'firstYear';
UPDATE study_grant_request SET current_studies_level = 'SECOND_YEAR'  Where current_studies_level = 'secondYear';
UPDATE study_grant_request SET current_studies_level = 'THIRD_YEAR'  Where current_studies_level = 'thirdYear';
-----------------;
-- HcarPaymentAgencyBeneficiaryType;
-----------------;
UPDATE handicap_compensation_adult_request SET payment_agency_beneficiary = 'C_A_F'  Where payment_agency_beneficiary = 'CAF';
UPDATE handicap_compensation_adult_request SET payment_agency_beneficiary = 'M_S_A'  Where payment_agency_beneficiary = 'MSA';
UPDATE handicap_compensation_adult_request SET payment_agency_beneficiary = 'OTHER'  Where payment_agency_beneficiary = 'Other';
UPDATE handicap_compensation_adult_request SET payment_agency_beneficiary = 'NO_MEMBER_SHIP'  Where payment_agency_beneficiary = 'NoMemberShip';
-----------------;
-- DhrDwellingKindType;
-----------------;
UPDATE domestic_help_request SET dhr_current_dwelling_kind = 'PLACE_OF_RESIDENCE'  Where dhr_current_dwelling_kind = 'placeOfResidence';
UPDATE domestic_help_request SET dhr_current_dwelling_kind = 'RETIREMENT_HOME'  Where dhr_current_dwelling_kind = 'retirementHome';
UPDATE domestic_help_request SET dhr_current_dwelling_kind = 'OTHER'  Where dhr_current_dwelling_kind = 'other';
-----------------;
-- HccrHomeIntervenantKindType;
-----------------;
UPDATE hccr_home_intervenant SET home_intervenant_kind = 'CARER'  Where home_intervenant_kind = 'Carer';
UPDATE hccr_home_intervenant SET home_intervenant_kind = 'HOME_HELP'  Where home_intervenant_kind = 'HomeHelp';
UPDATE hccr_home_intervenant SET home_intervenant_kind = 'OTHER'  Where home_intervenant_kind = 'Other';
-----------------;
-- HcarProfessionalStatusKindType;
-----------------;
UPDATE handicap_compensation_adult_request SET professional_status_kind = 'EMPLOYEE'  Where professional_status_kind = 'Employee';
UPDATE handicap_compensation_adult_request SET professional_status_kind = 'UNEMPLOYED'  Where professional_status_kind = 'Unemployed';
UPDATE handicap_compensation_adult_request SET professional_status_kind = 'JOBLESS'  Where professional_status_kind = 'Jobless';
UPDATE handicap_compensation_adult_request SET professional_status_kind = 'STUDENT'  Where professional_status_kind = 'Student';
UPDATE handicap_compensation_adult_request SET professional_status_kind = 'RETIRED'  Where professional_status_kind = 'Retired';
-----------------;
-- PlageHoraireContactType;
-----------------;
UPDATE day_care_center_registration_request SET plage_horaire_contact = 'MATIN'  Where plage_horaire_contact = 'Matin';
UPDATE day_care_center_registration_request SET plage_horaire_contact = 'APREM'  Where plage_horaire_contact = 'Aprem';
UPDATE day_care_center_registration_request SET plage_horaire_contact = 'SOIR'  Where plage_horaire_contact = 'Soir';
UPDATE day_care_center_registration_request SET plage_horaire_contact = 'INDIFFERENT'  Where plage_horaire_contact = 'Indifferent';
-----------------;
-- UserState;
-----------------;
UPDATE individual SET state = 'NEW'  Where state = 'New';
UPDATE individual SET state = 'VALID'  Where state = 'Valid';
UPDATE individual SET state = 'MODIFIED'  Where state = 'Modified';
UPDATE individual SET state = 'INVALID'  Where state = 'Invalid';
UPDATE individual SET state = 'ARCHIVED'  Where state = 'Archived';
-----------------;
-- FullNationalityType;
-----------------;
UPDATE military_census_request SET child_country = 'NONE'  Where child_country = 'None';
UPDATE military_census_request SET child_country = 'AF'  Where child_country = 'af';
UPDATE military_census_request SET child_country = 'ZA'  Where child_country = 'za';
UPDATE military_census_request SET child_country = 'AL'  Where child_country = 'al';
UPDATE military_census_request SET child_country = 'DZ'  Where child_country = 'dz';
UPDATE military_census_request SET child_country = 'DE'  Where child_country = 'de';
UPDATE military_census_request SET child_country = 'AD'  Where child_country = 'ad';
UPDATE military_census_request SET child_country = 'AO'  Where child_country = 'ao';
UPDATE military_census_request SET child_country = 'AI'  Where child_country = 'ai';
UPDATE military_census_request SET child_country = 'AQ'  Where child_country = 'aq';
UPDATE military_census_request SET child_country = 'AG'  Where child_country = 'ag';
UPDATE military_census_request SET child_country = 'AN'  Where child_country = 'an';
UPDATE military_census_request SET child_country = 'SA'  Where child_country = 'sa';
UPDATE military_census_request SET child_country = 'AR'  Where child_country = 'ar';
UPDATE military_census_request SET child_country = 'AM'  Where child_country = 'am';
UPDATE military_census_request SET child_country = 'AW'  Where child_country = 'aw';
UPDATE military_census_request SET child_country = 'AU'  Where child_country = 'au';
UPDATE military_census_request SET child_country = 'AT'  Where child_country = 'at';
UPDATE military_census_request SET child_country = 'AZ'  Where child_country = 'az';
UPDATE military_census_request SET child_country = 'BS'  Where child_country = 'bs';
UPDATE military_census_request SET child_country = 'BH'  Where child_country = 'bh';
UPDATE military_census_request SET child_country = 'BD'  Where child_country = 'bd';
UPDATE military_census_request SET child_country = 'BB'  Where child_country = 'bb';
UPDATE military_census_request SET child_country = 'BE'  Where child_country = 'be';
UPDATE military_census_request SET child_country = 'BZ'  Where child_country = 'bz';
UPDATE military_census_request SET child_country = 'BJ'  Where child_country = 'bj';
UPDATE military_census_request SET child_country = 'BM'  Where child_country = 'bm';
UPDATE military_census_request SET child_country = 'BT'  Where child_country = 'bt';
UPDATE military_census_request SET child_country = 'BY'  Where child_country = 'by';
UPDATE military_census_request SET child_country = 'MM'  Where child_country = 'mm';
UPDATE military_census_request SET child_country = 'BO'  Where child_country = 'bo';
UPDATE military_census_request SET child_country = 'BA'  Where child_country = 'ba';
UPDATE military_census_request SET child_country = 'BW'  Where child_country = 'bw';
UPDATE military_census_request SET child_country = 'BR'  Where child_country = 'br';
UPDATE military_census_request SET child_country = 'BN'  Where child_country = 'bn';
UPDATE military_census_request SET child_country = 'BG'  Where child_country = 'bg';
UPDATE military_census_request SET child_country = 'BF'  Where child_country = 'bf';
UPDATE military_census_request SET child_country = 'BI'  Where child_country = 'bi';
UPDATE military_census_request SET child_country = 'KH'  Where child_country = 'kh';
UPDATE military_census_request SET child_country = 'CM'  Where child_country = 'cm';
UPDATE military_census_request SET child_country = 'CA'  Where child_country = 'ca';
UPDATE military_census_request SET child_country = 'CV'  Where child_country = 'cv';
UPDATE military_census_request SET child_country = 'CL'  Where child_country = 'cl';
UPDATE military_census_request SET child_country = 'CN'  Where child_country = 'cn';
UPDATE military_census_request SET child_country = 'CY'  Where child_country = 'cy';
UPDATE military_census_request SET child_country = 'CO'  Where child_country = 'co';
UPDATE military_census_request SET child_country = 'KM'  Where child_country = 'km';
UPDATE military_census_request SET child_country = 'CG'  Where child_country = 'cg';
UPDATE military_census_request SET child_country = 'KP'  Where child_country = 'kp';
UPDATE military_census_request SET child_country = 'KR'  Where child_country = 'kr';
UPDATE military_census_request SET child_country = 'CR'  Where child_country = 'cr';
UPDATE military_census_request SET child_country = 'HR'  Where child_country = 'hr';
UPDATE military_census_request SET child_country = 'CU'  Where child_country = 'cu';
UPDATE military_census_request SET child_country = 'DK'  Where child_country = 'dk';
UPDATE military_census_request SET child_country = 'DJ'  Where child_country = 'dj';
UPDATE military_census_request SET child_country = 'DM'  Where child_country = 'dm';
UPDATE military_census_request SET child_country = 'EG'  Where child_country = 'eg';
UPDATE military_census_request SET child_country = 'AE'  Where child_country = 'ae';
UPDATE military_census_request SET child_country = 'EC'  Where child_country = 'ec';
UPDATE military_census_request SET child_country = 'ER'  Where child_country = 'er';
UPDATE military_census_request SET child_country = 'ES'  Where child_country = 'es';
UPDATE military_census_request SET child_country = 'EE'  Where child_country = 'ee';
UPDATE military_census_request SET child_country = 'US'  Where child_country = 'us';
UPDATE military_census_request SET child_country = 'ET'  Where child_country = 'et';
UPDATE military_census_request SET child_country = 'FI'  Where child_country = 'fi';
UPDATE military_census_request SET child_country = 'FR'  Where child_country = 'fr';
UPDATE military_census_request SET child_country = 'GE'  Where child_country = 'ge';
UPDATE military_census_request SET child_country = 'GA'  Where child_country = 'ga';
UPDATE military_census_request SET child_country = 'GM'  Where child_country = 'gm';
UPDATE military_census_request SET child_country = 'GH'  Where child_country = 'gh';
UPDATE military_census_request SET child_country = 'GI'  Where child_country = 'gi';
UPDATE military_census_request SET child_country = 'GR'  Where child_country = 'gr';
UPDATE military_census_request SET child_country = 'GD'  Where child_country = 'gd';
UPDATE military_census_request SET child_country = 'GL'  Where child_country = 'gl';
UPDATE military_census_request SET child_country = 'GU'  Where child_country = 'gu';
UPDATE military_census_request SET child_country = 'GT'  Where child_country = 'gt';
UPDATE military_census_request SET child_country = 'GN'  Where child_country = 'gn';
UPDATE military_census_request SET child_country = 'GQ'  Where child_country = 'gq';
UPDATE military_census_request SET child_country = 'GW'  Where child_country = 'gw';
UPDATE military_census_request SET child_country = 'HT'  Where child_country = 'ht';
UPDATE military_census_request SET child_country = 'HN'  Where child_country = 'hn';
UPDATE military_census_request SET child_country = 'HK'  Where child_country = 'hk';
UPDATE military_census_request SET child_country = 'HU'  Where child_country = 'hu';
UPDATE military_census_request SET child_country = 'CK'  Where child_country = 'ck';
UPDATE military_census_request SET child_country = 'FJ'  Where child_country = 'fj';
UPDATE military_census_request SET child_country = 'MH'  Where child_country = 'mh';
UPDATE military_census_request SET child_country = 'SB'  Where child_country = 'sb';
UPDATE military_census_request SET child_country = 'IN'  Where child_country = 'in';
UPDATE military_census_request SET child_country = 'ID'  Where child_country = 'id';
UPDATE military_census_request SET child_country = 'IR'  Where child_country = 'ir';
UPDATE military_census_request SET child_country = 'IQ'  Where child_country = 'iq';
UPDATE military_census_request SET child_country = 'IE'  Where child_country = 'ie';
UPDATE military_census_request SET child_country = 'IS'  Where child_country = 'is';
UPDATE military_census_request SET child_country = 'IL'  Where child_country = 'il';
UPDATE military_census_request SET child_country = 'IT'  Where child_country = 'it';
UPDATE military_census_request SET child_country = 'CI'  Where child_country = 'ci';
UPDATE military_census_request SET child_country = 'JM'  Where child_country = 'jm';
UPDATE military_census_request SET child_country = 'JP'  Where child_country = 'jp';
UPDATE military_census_request SET child_country = 'JO'  Where child_country = 'jo';
UPDATE military_census_request SET child_country = 'KZ'  Where child_country = 'kz';
UPDATE military_census_request SET child_country = 'KE'  Where child_country = 'ke';
UPDATE military_census_request SET child_country = 'KG'  Where child_country = 'kg';
UPDATE military_census_request SET child_country = 'KI'  Where child_country = 'ki';
UPDATE military_census_request SET child_country = 'KW'  Where child_country = 'kw';
UPDATE military_census_request SET child_country = 'LA'  Where child_country = 'la';
UPDATE military_census_request SET child_country = 'LS'  Where child_country = 'ls';
UPDATE military_census_request SET child_country = 'LV'  Where child_country = 'lv';
UPDATE military_census_request SET child_country = 'LB'  Where child_country = 'lb';
UPDATE military_census_request SET child_country = 'LR'  Where child_country = 'lr';
UPDATE military_census_request SET child_country = 'LY'  Where child_country = 'ly';
UPDATE military_census_request SET child_country = 'LI'  Where child_country = 'li';
UPDATE military_census_request SET child_country = 'LT'  Where child_country = 'lt';
UPDATE military_census_request SET child_country = 'LU'  Where child_country = 'lu';
UPDATE military_census_request SET child_country = 'MG'  Where child_country = 'mg';
UPDATE military_census_request SET child_country = 'MY'  Where child_country = 'my';
UPDATE military_census_request SET child_country = 'MW'  Where child_country = 'mw';
UPDATE military_census_request SET child_country = 'MV'  Where child_country = 'mv';
UPDATE military_census_request SET child_country = 'ML'  Where child_country = 'ml';
UPDATE military_census_request SET child_country = 'MT'  Where child_country = 'mt';
UPDATE military_census_request SET child_country = 'MA'  Where child_country = 'ma';
UPDATE military_census_request SET child_country = 'MU'  Where child_country = 'mu';
UPDATE military_census_request SET child_country = 'MR'  Where child_country = 'mr';
UPDATE military_census_request SET child_country = 'MX'  Where child_country = 'mx';
UPDATE military_census_request SET child_country = 'FM'  Where child_country = 'fm';
UPDATE military_census_request SET child_country = 'MD'  Where child_country = 'md';
UPDATE military_census_request SET child_country = 'MC'  Where child_country = 'mc';
UPDATE military_census_request SET child_country = 'MN'  Where child_country = 'mn';
UPDATE military_census_request SET child_country = 'MZ'  Where child_country = 'mz';
UPDATE military_census_request SET child_country = 'NP'  Where child_country = 'np';
UPDATE military_census_request SET child_country = 'NA'  Where child_country = 'na';
UPDATE military_census_request SET child_country = 'NR'  Where child_country = 'nr';
UPDATE military_census_request SET child_country = 'NI'  Where child_country = 'ni';
UPDATE military_census_request SET child_country = 'NE'  Where child_country = 'ne';
UPDATE military_census_request SET child_country = 'NG'  Where child_country = 'ng';
UPDATE military_census_request SET child_country = 'NU'  Where child_country = 'nu';
UPDATE military_census_request SET child_country = 'NO'  Where child_country = 'no';
UPDATE military_census_request SET child_country = 'NZ'  Where child_country = 'nz';
UPDATE military_census_request SET child_country = 'OM'  Where child_country = 'om';
UPDATE military_census_request SET child_country = 'UG'  Where child_country = 'ug';
UPDATE military_census_request SET child_country = 'UZ'  Where child_country = 'uz';
UPDATE military_census_request SET child_country = 'PE'  Where child_country = 'pe';
UPDATE military_census_request SET child_country = 'PK'  Where child_country = 'pk';
UPDATE military_census_request SET child_country = 'PA'  Where child_country = 'pa';
UPDATE military_census_request SET child_country = 'PG'  Where child_country = 'pg';
UPDATE military_census_request SET child_country = 'PY'  Where child_country = 'py';
UPDATE military_census_request SET child_country = 'NL'  Where child_country = 'nl';
UPDATE military_census_request SET child_country = 'PH'  Where child_country = 'ph';
UPDATE military_census_request SET child_country = 'PL'  Where child_country = 'pl';
UPDATE military_census_request SET child_country = 'PT'  Where child_country = 'pt';
UPDATE military_census_request SET child_country = 'QA'  Where child_country = 'qa';
UPDATE military_census_request SET child_country = 'CF'  Where child_country = 'cf';
UPDATE military_census_request SET child_country = 'CD'  Where child_country = 'cd';
UPDATE military_census_request SET child_country = 'DO'  Where child_country = 'do';
UPDATE military_census_request SET child_country = 'CZ'  Where child_country = 'cz';
UPDATE military_census_request SET child_country = 'RO'  Where child_country = 'ro';
UPDATE military_census_request SET child_country = 'GB'  Where child_country = 'gb';
UPDATE military_census_request SET child_country = 'RU'  Where child_country = 'ru';
UPDATE military_census_request SET child_country = 'RW'  Where child_country = 'rw';
UPDATE military_census_request SET child_country = 'SN'  Where child_country = 'sn';
UPDATE military_census_request SET child_country = 'KN'  Where child_country = 'kn';
UPDATE military_census_request SET child_country = 'SM'  Where child_country = 'sm';
UPDATE military_census_request SET child_country = 'VA'  Where child_country = 'va';
UPDATE military_census_request SET child_country = 'VC'  Where child_country = 'vc';
UPDATE military_census_request SET child_country = 'LC'  Where child_country = 'lc';
UPDATE military_census_request SET child_country = 'SV'  Where child_country = 'sv';
UPDATE military_census_request SET child_country = 'WS'  Where child_country = 'ws';
UPDATE military_census_request SET child_country = 'ST'  Where child_country = 'st';
UPDATE military_census_request SET child_country = 'SC'  Where child_country = 'sc';
UPDATE military_census_request SET child_country = 'SL'  Where child_country = 'sl';
UPDATE military_census_request SET child_country = 'SG'  Where child_country = 'sg';
UPDATE military_census_request SET child_country = 'SI'  Where child_country = 'si';
UPDATE military_census_request SET child_country = 'SK'  Where child_country = 'sk';
UPDATE military_census_request SET child_country = 'SO'  Where child_country = 'so';
UPDATE military_census_request SET child_country = 'SD'  Where child_country = 'sd';
UPDATE military_census_request SET child_country = 'LK'  Where child_country = 'lk';
UPDATE military_census_request SET child_country = 'SE'  Where child_country = 'se';
UPDATE military_census_request SET child_country = 'CH'  Where child_country = 'ch';
UPDATE military_census_request SET child_country = 'SR'  Where child_country = 'sr';
UPDATE military_census_request SET child_country = 'SZ'  Where child_country = 'sz';
UPDATE military_census_request SET child_country = 'SY'  Where child_country = 'sy';
UPDATE military_census_request SET child_country = 'TW'  Where child_country = 'tw';
UPDATE military_census_request SET child_country = 'TJ'  Where child_country = 'tj';
UPDATE military_census_request SET child_country = 'TZ'  Where child_country = 'tz';
UPDATE military_census_request SET child_country = 'TD'  Where child_country = 'td';
UPDATE military_census_request SET child_country = 'TH'  Where child_country = 'th';
UPDATE military_census_request SET child_country = 'TL'  Where child_country = 'tl';
UPDATE military_census_request SET child_country = 'TG'  Where child_country = 'tg';
UPDATE military_census_request SET child_country = 'TO'  Where child_country = 'to';
UPDATE military_census_request SET child_country = 'VT'  Where child_country = 'vt';
UPDATE military_census_request SET child_country = 'TN'  Where child_country = 'tn';
UPDATE military_census_request SET child_country = 'TM'  Where child_country = 'tm';
UPDATE military_census_request SET child_country = 'TR'  Where child_country = 'tr';
UPDATE military_census_request SET child_country = 'TV'  Where child_country = 'tv';
UPDATE military_census_request SET child_country = 'UA'  Where child_country = 'ua';
UPDATE military_census_request SET child_country = 'UY'  Where child_country = 'uy';
UPDATE military_census_request SET child_country = 'VU'  Where child_country = 'vu';
UPDATE military_census_request SET child_country = 'VE'  Where child_country = 've';
UPDATE military_census_request SET child_country = 'VN'  Where child_country = 'vn';
UPDATE military_census_request SET child_country = 'YE'  Where child_country = 'ye';
UPDATE military_census_request SET child_country = 'ZM'  Where child_country = 'zm';
UPDATE military_census_request SET child_country = 'ZW'  Where child_country = 'zw';
UPDATE military_census_request SET child_country = 'MK'  Where child_country = 'mk';
-----------------;
-- QoS;
-----------------;
UPDATE individual SET q_o_s = 'GOOD'  Where q_o_s = 'Good';
UPDATE individual SET q_o_s = 'URGENT'  Where q_o_s = 'Urgent';
UPDATE individual SET q_o_s = 'LATE'  Where q_o_s = 'Late';
-----------------;
-- ALevelsType;
-----------------;
UPDATE study_grant_request SET alevels = 'ES'  Where alevels = 'es';
UPDATE study_grant_request SET alevels = 'L'  Where alevels = 'l';
UPDATE study_grant_request SET alevels = 'S'  Where alevels = 's';
UPDATE study_grant_request SET alevels = 'STG'  Where alevels = 'stg';
UPDATE study_grant_request SET alevels = 'STI'  Where alevels = 'sti';
UPDATE study_grant_request SET alevels = 'STL'  Where alevels = 'stl';
UPDATE study_grant_request SET alevels = 'ST2S'  Where alevels = 'st2s';
UPDATE study_grant_request SET alevels = 'STAV'  Where alevels = 'stav';
UPDATE study_grant_request SET alevels = 'TMD'  Where alevels = 'tmd';
UPDATE study_grant_request SET alevels = 'H'  Where alevels = 'h';
UPDATE study_grant_request SET alevels = 'P'  Where alevels = 'p';
-----------------;
-- SiteProfile;
-----------------;
UPDATE agent_site_roles SET profile = 'AGENT'  Where profile = 'Agent';
UPDATE agent_site_roles SET profile = 'ADMIN'  Where profile = 'Admin';
-----------------;
-- HcarSocialSecurityMemberShipKindType;
-----------------;
UPDATE handicap_compensation_adult_request SET social_security_member_ship_kind = 'INSURED'  Where social_security_member_ship_kind = 'Insured';
UPDATE handicap_compensation_adult_request SET social_security_member_ship_kind = 'CLAIMANT'  Where social_security_member_ship_kind = 'Claimant';
UPDATE handicap_compensation_adult_request SET social_security_member_ship_kind = 'NO_MEMBER_SHIP'  Where social_security_member_ship_kind = 'NoMemberShip';
-----------------;
-- InseeDepartementCodeType;
-----------------;
UPDATE military_census_request SET mother_birth_department = 'NONE'  Where mother_birth_department = 'None';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_01'  Where mother_birth_department = 'DEP_01';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_02'  Where mother_birth_department = 'DEP_02';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_03'  Where mother_birth_department = 'DEP_03';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_04'  Where mother_birth_department = 'DEP_04';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_05'  Where mother_birth_department = 'DEP_05';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_06'  Where mother_birth_department = 'DEP_06';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_07'  Where mother_birth_department = 'DEP_07';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_08'  Where mother_birth_department = 'DEP_08';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_09'  Where mother_birth_department = 'DEP_09';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_10'  Where mother_birth_department = 'DEP_10';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_11'  Where mother_birth_department = 'DEP_11';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_12'  Where mother_birth_department = 'DEP_12';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_13'  Where mother_birth_department = 'DEP_13';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_14'  Where mother_birth_department = 'DEP_14';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_15'  Where mother_birth_department = 'DEP_15';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_16'  Where mother_birth_department = 'DEP_16';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_17'  Where mother_birth_department = 'DEP_17';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_18'  Where mother_birth_department = 'DEP_18';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_19'  Where mother_birth_department = 'DEP_19';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_2_A'  Where mother_birth_department = 'DEP_2A';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_2_B'  Where mother_birth_department = 'DEP_2B';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_21'  Where mother_birth_department = 'DEP_21';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_22'  Where mother_birth_department = 'DEP_22';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_23'  Where mother_birth_department = 'DEP_23';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_24'  Where mother_birth_department = 'DEP_24';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_25'  Where mother_birth_department = 'DEP_25';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_26'  Where mother_birth_department = 'DEP_26';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_27'  Where mother_birth_department = 'DEP_27';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_28'  Where mother_birth_department = 'DEP_28';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_29'  Where mother_birth_department = 'DEP_29';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_30'  Where mother_birth_department = 'DEP_30';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_31'  Where mother_birth_department = 'DEP_31';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_32'  Where mother_birth_department = 'DEP_32';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_33'  Where mother_birth_department = 'DEP_33';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_34'  Where mother_birth_department = 'DEP_34';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_35'  Where mother_birth_department = 'DEP_35';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_36'  Where mother_birth_department = 'DEP_36';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_37'  Where mother_birth_department = 'DEP_37';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_38'  Where mother_birth_department = 'DEP_38';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_39'  Where mother_birth_department = 'DEP_39';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_40'  Where mother_birth_department = 'DEP_40';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_41'  Where mother_birth_department = 'DEP_41';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_42'  Where mother_birth_department = 'DEP_42';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_43'  Where mother_birth_department = 'DEP_43';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_44'  Where mother_birth_department = 'DEP_44';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_45'  Where mother_birth_department = 'DEP_45';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_46'  Where mother_birth_department = 'DEP_46';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_47'  Where mother_birth_department = 'DEP_47';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_48'  Where mother_birth_department = 'DEP_48';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_49'  Where mother_birth_department = 'DEP_49';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_50'  Where mother_birth_department = 'DEP_50';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_51'  Where mother_birth_department = 'DEP_51';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_52'  Where mother_birth_department = 'DEP_52';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_53'  Where mother_birth_department = 'DEP_53';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_54'  Where mother_birth_department = 'DEP_54';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_55'  Where mother_birth_department = 'DEP_55';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_56'  Where mother_birth_department = 'DEP_56';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_57'  Where mother_birth_department = 'DEP_57';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_58'  Where mother_birth_department = 'DEP_58';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_59'  Where mother_birth_department = 'DEP_59';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_60'  Where mother_birth_department = 'DEP_60';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_61'  Where mother_birth_department = 'DEP_61';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_62'  Where mother_birth_department = 'DEP_62';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_63'  Where mother_birth_department = 'DEP_63';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_64'  Where mother_birth_department = 'DEP_64';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_65'  Where mother_birth_department = 'DEP_65';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_66'  Where mother_birth_department = 'DEP_66';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_67'  Where mother_birth_department = 'DEP_67';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_68'  Where mother_birth_department = 'DEP_68';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_69'  Where mother_birth_department = 'DEP_69';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_70'  Where mother_birth_department = 'DEP_70';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_71'  Where mother_birth_department = 'DEP_71';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_72'  Where mother_birth_department = 'DEP_72';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_73'  Where mother_birth_department = 'DEP_73';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_74'  Where mother_birth_department = 'DEP_74';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_75'  Where mother_birth_department = 'DEP_75';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_76'  Where mother_birth_department = 'DEP_76';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_77'  Where mother_birth_department = 'DEP_77';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_78'  Where mother_birth_department = 'DEP_78';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_79'  Where mother_birth_department = 'DEP_79';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_80'  Where mother_birth_department = 'DEP_80';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_81'  Where mother_birth_department = 'DEP_81';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_82'  Where mother_birth_department = 'DEP_82';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_83'  Where mother_birth_department = 'DEP_83';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_84'  Where mother_birth_department = 'DEP_84';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_85'  Where mother_birth_department = 'DEP_85';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_86'  Where mother_birth_department = 'DEP_86';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_87'  Where mother_birth_department = 'DEP_87';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_88'  Where mother_birth_department = 'DEP_88';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_89'  Where mother_birth_department = 'DEP_89';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_90'  Where mother_birth_department = 'DEP_90';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_91'  Where mother_birth_department = 'DEP_91';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_92'  Where mother_birth_department = 'DEP_92';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_93'  Where mother_birth_department = 'DEP_93';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_94'  Where mother_birth_department = 'DEP_94';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_95'  Where mother_birth_department = 'DEP_95';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_971'  Where mother_birth_department = 'DEP_971';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_972'  Where mother_birth_department = 'DEP_972';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_973'  Where mother_birth_department = 'DEP_973';
UPDATE military_census_request SET mother_birth_department = 'D_E_P_974'  Where mother_birth_department = 'DEP_974';
-----------------;
-- HcarLegalAccessRepresentativeKindType;
-----------------;
UPDATE handicap_compensation_adult_request SET legal_access_representative_kind = 'FAMILY_MEMBER'  Where legal_access_representative_kind = 'FamilyMember';
UPDATE handicap_compensation_adult_request SET legal_access_representative_kind = 'AGENCY'  Where legal_access_representative_kind = 'Agency';
UPDATE handicap_compensation_adult_request SET legal_access_representative_kind = 'OTHER'  Where legal_access_representative_kind = 'Other';
-----------------;
-- RendezVousType;
-----------------;
UPDATE day_care_center_registration_request SET choix_type_rendez_vous = 'PHYSIQUE'  Where choix_type_rendez_vous = 'Physique';
UPDATE day_care_center_registration_request SET choix_type_rendez_vous = 'TELEPHONIQUE'  Where choix_type_rendez_vous = 'Telephonique';
-----------------;
-- DocumentState;
-----------------;
UPDATE document_action SET resulting_state = 'DRAFT'  Where resulting_state = 'Draft';
UPDATE document_action SET resulting_state = 'PENDING'  Where resulting_state = 'Pending';
UPDATE document_action SET resulting_state = 'VALIDATED'  Where resulting_state = 'Validated';
UPDATE document_action SET resulting_state = 'CHECKED'  Where resulting_state = 'Checked';
UPDATE document_action SET resulting_state = 'REFUSED'  Where resulting_state = 'Refused';
UPDATE document_action SET resulting_state = 'OUTDATED'  Where resulting_state = 'Outdated';
-----------------;
-----------------;
-- IndividualRole;
-----------------;
UPDATE individual_role set role = 'HOME_FOLDER_RESPONSIBLE' where role = 'HomeFolderResponsible';
UPDATE individual_role set role = 'CLR_MOTHER' where role = 'ClrMother';
UPDATE individual_role set role = 'CLR_FATHER' where role = 'ClrFather';
UPDATE individual_role set role = 'CLR_TUTOR' where role = 'ClrTutor';
UPDATE individual_role set role = 'TUTOR' where role = 'Tutor';

UPDATE home_folder SET state = 'NEW'  Where state = 'New';
UPDATE home_folder SET state = 'VALID'  Where state = 'Valid';
UPDATE home_folder SET state = 'MODIFIED'  Where state = 'Modified';
UPDATE home_folder SET state = 'INVALID'  Where state = 'Invalid';
UPDATE home_folder SET state = 'ARCHIVED'  Where state = 'Archived';

UPDATE request SET state = 'PENDING'  Where state = 'Pending';
UPDATE request SET state = 'DRAFT'  Where state = 'Draft';
UPDATE request SET state = 'INPROGRESS'  Where state = 'Inprogress';
UPDATE request SET state = 'EXTINPROGRESS'  Where state = 'Extinprogress';
UPDATE request SET state = 'COMPLETE'  Where state = 'Complete';
UPDATE request SET state = 'UNCOMPLETE'  Where state = 'Uncomplete';
UPDATE request SET state = 'RECTIFIED'  Where state = 'Rectified';
UPDATE request SET state = 'VALIDATED'  Where state = 'Validated';
UPDATE request SET state = 'NOTIFIED' Where state = 'Notified';
UPDATE request SET state = 'CLOSED'  Where state = 'Closed';
UPDATE request SET state = 'REJECTED'  Where state = 'Rejected';
UPDATE request SET state = 'CANCELLED'  Where state = 'Cancelled';
UPDATE request SET state = 'ARCHIVED'  Where state = 'Archived';

update document set state = 'DRAFT' where state = 'Draft';
update document set state = 'PENDING' where state = 'Pending';
update document set state = 'VALIDATED' where state = 'Validated';
update document set state = 'CHECKED' where state = 'Checked';
update document set state = 'REFUSED' where state = 'Refused';
update document set state = 'OUTDATED' where state = 'Outdated';

update document_binary set content_type = 'BMP' where content_type = 'image/x-ms-bmp';
update document_binary set content_type = 'PDF' where content_type = 'application/pdf';
update document_binary set content_type = 'JPEG' where content_type = 'image/jpeg';
update document_binary set content_type = 'GIF' where content_type = 'image/gif';
update document_binary set content_type = 'PNG' where content_type = 'image/png';
update document_binary set content_type = 'OCTET_STREAM' where content_type = 'application/octet-stream';
update document_binary set content_type = 'TIFF' where content_type = 'image/tiff';

update request_external_action set status = 'SENT' where status = 'Sent';
update request_external_action set status = 'NOT_SENT' where status = 'NotSent';
update request_external_action set status = 'IN_PROGRESS' where status = 'InProgress';
update request_external_action set status = 'ACKNOWLEDGED' where status = 'Acknowledged';
update request_external_action set status = 'ERROR' where status = 'Error';
update request_external_action set status = 'ACCEPTED' where status = 'Accepted';
update request_external_action set status = 'REJECTED' where status = 'Rejected';
update request_external_action set status = 'RETURNED' where status = 'Returned';

update request_note set type = 'INTERNAL' where type = 'Internal';
update request_note set type = 'PUBLIC' where type = 'Public';

update school_transport_registration_request set autorisation = 'SEUL' where autorisation = 'Seul';
update school_transport_registration_request set autorisation = 'AVEC_FRERE_SOEUR' where autorisation = 'AvecFrereSoeur';
update school_transport_registration_request set autorisation = 'AVEC_TIERS' where autorisation = 'AvecTiers';
