package fr.cg95.cvq.service.request.social;

import fr.cg95.cvq.business.request.social.*;
import fr.cg95.cvq.business.users.HomeFolder;
import fr.cg95.cvq.business.users.Adult;
import fr.cg95.cvq.testtool.TestUtils;

/**
 * Generated by Groovy only if not present, can be edited safely !
 */
public class BafaGrantRequestFeeder {

    public static void feed(BafaGrantRequest request) {
    }

	public static void setSubject(BafaGrantRequest request,
	        String subjectPolicy, Adult requester, HomeFolder homeFolder) {
		
		TestUtils.feedRequestSubject(request, subjectPolicy, requester, homeFolder);
	}
}
