
//   &eacute;
//   &egrave;
///////////////////////////////
// Generated by CapDemat v4.0
// har keys
///////////////////////////////

// Request duration 
har.duration.value=X min

// Steps labels

har.step.subject.label = subject
har.step.subject.desc = subject informations.
har.step.subject.submitLabel = Validate this page

har.step.dwelling.label = dwelling
har.step.dwelling.desc = dwelling informations.
har.step.dwelling.submitLabel = Validate this page

har.step.socialSecurity.label = socialSecurity
har.step.socialSecurity.desc = socialSecurity informations.
har.step.socialSecurity.submitLabel = Validate this page

har.step.position.label = position
har.step.position.desc = position informations.
har.step.position.submitLabel = Validate this page

har.step.handicapKind.label = handicapKind
har.step.handicapKind.desc = handicapKind informations.
har.step.handicapKind.submitLabel = Validate this page

har.step.followup.label = followup
har.step.followup.desc = followup informations.
har.step.followup.submitLabel = Validate this page

har.step.project.label = project
har.step.project.desc = project informations.
har.step.project.submitLabel = Validate this page

// documentRef step
har.step.documentRef.label = Document label
har.step.documentRef.desc = Document desc
har.step.documentRef.submitLabel = Validate this page

// validationRef step
har.step.validationRef.label = Validation label
har.step.validationRef.desc = Validation desc
har.step.validationRef.submitLabel = Validate this page


// Elements labels

har.property.harRequestInformationProfile.help= (Help HarRequestInformationProfile)
har.property.harRequestInformationProfile.validationError= HarRequestInformationProfile validation error

har.property.harRequesterTitle.defaultOption = Choose...
har.property.harRequesterTitle.help= (Help HarRequesterTitle)
har.property.harRequesterTitle.validationError= HarRequesterTitle validation error

har.property.harRequesterName.help= (Help HarRequesterName)
har.property.harRequesterName.validationError= HarRequesterName validation error


har.property.harRequesterMaidenName.help= (Help HarRequesterMaidenName)
har.property.harRequesterMaidenName.validationError= HarRequesterMaidenName validation error


har.property.harRequesterFirstName.help= (Help HarRequesterFirstName)
har.property.harRequesterFirstName.validationError= HarRequesterFirstName validation error


har.property.harRequesterStreetName.help= (Help HarRequesterStreetName)
har.property.harRequesterStreetName.validationError= HarRequesterStreetName validation error


har.property.harRequesterPostalCode.help= (Help HarRequesterPostalCode)
har.property.harRequesterPostalCode.validationError= HarRequesterPostalCode validation error


har.property.harRequesterCity.help= (Help HarRequesterCity)
har.property.harRequesterCity.validationError= HarRequesterCity validation error


har.property.harRequesterPhone.help= (Help HarRequesterPhone)
har.property.harRequesterPhone.validationError= HarRequesterPhone validation error


har.property.harRequesterMobilePhone.help= (Help HarRequesterMobilePhone)
har.property.harRequesterMobilePhone.validationError= HarRequesterMobilePhone validation error


har.property.harRequesterEmail.help= (Help HarRequesterEmail)
har.property.harRequesterEmail.validationError= HarRequesterEmail validation error


har.property.harRequesterBirthDate.help= (Help HarRequesterBirthDate)
har.property.harRequesterBirthDate.validationError= HarRequesterBirthDate validation error


har.property.harRequesterBirthCity.help= (Help HarRequesterBirthCity)
har.property.harRequesterBirthCity.validationError= HarRequesterBirthCity validation error


har.property.harRequesterBirthCountry.defaultOption = Choose...
har.property.harRequesterBirthCountry.help= (Help HarRequesterBirthCountry)
har.property.harRequesterBirthCountry.validationError= HarRequesterBirthCountry validation error

har.property.harLegalAccessPresence.help= (Help HarLegalAccessPresence)
har.property.harLegalAccessPresence.validationError= HarLegalAccessPresence validation error


har.property.harLegalAccessKind.defaultOption = Choose...
har.property.harLegalAccessKind.help= (Help HarLegalAccessKind)
har.property.harLegalAccessKind.validationError= HarLegalAccessKind validation error

har.property.harLegalAccessRepresentativeKind.defaultOption = Choose...
har.property.harLegalAccessRepresentativeKind.help= (Help HarLegalAccessRepresentativeKind)
har.property.harLegalAccessRepresentativeKind.validationError= HarLegalAccessRepresentativeKind validation error

har.property.harLegalAccessRepresentativeKindDetail.help= (Help HarLegalAccessRepresentativeKindDetail)
har.property.harLegalAccessRepresentativeKindDetail.validationError= HarLegalAccessRepresentativeKindDetail validation error


har.property.harLegalAccessRepresentativeName.help= (Help HarLegalAccessRepresentativeName)
har.property.harLegalAccessRepresentativeName.validationError= HarLegalAccessRepresentativeName validation error


har.property.harLegalAccessRepresentativeFirstName.help= (Help HarLegalAccessRepresentativeFirstName)
har.property.harLegalAccessRepresentativeFirstName.validationError= HarLegalAccessRepresentativeFirstName validation error


har.property.harLegalAccessRepresentativeStreetName.help= (Help HarLegalAccessRepresentativeStreetName)
har.property.harLegalAccessRepresentativeStreetName.validationError= HarLegalAccessRepresentativeStreetName validation error


har.property.harLegalAccessRepresentativePostalCode.help= (Help HarLegalAccessRepresentativePostalCode)
har.property.harLegalAccessRepresentativePostalCode.validationError= HarLegalAccessRepresentativePostalCode validation error


har.property.harLegalAccessRepresentativeCity.help= (Help HarLegalAccessRepresentativeCity)
har.property.harLegalAccessRepresentativeCity.validationError= HarLegalAccessRepresentativeCity validation error


har.property.harLegalAccessRepresentativePhone.help= (Help HarLegalAccessRepresentativePhone)
har.property.harLegalAccessRepresentativePhone.validationError= HarLegalAccessRepresentativePhone validation error


har.property.harLegalAccessRepresentativeMobilePhone.help= (Help HarLegalAccessRepresentativeMobilePhone)
har.property.harLegalAccessRepresentativeMobilePhone.validationError= HarLegalAccessRepresentativeMobilePhone validation error


har.property.harLegalAccessRepresentativeEmail.help= (Help HarLegalAccessRepresentativeEmail)
har.property.harLegalAccessRepresentativeEmail.validationError= HarLegalAccessRepresentativeEmail validation error


har.property.harRequesterTitle.defaultOption = Choose...
har.property.harRequesterTitle.help= (Help HarRequesterTitle)
har.property.harRequesterTitle.validationError= HarRequesterTitle validation error

har.property.harRequesterName.help= (Help HarRequesterName)
har.property.harRequesterName.validationError= HarRequesterName validation error


har.property.harRequesterMaidenName.help= (Help HarRequesterMaidenName)
har.property.harRequesterMaidenName.validationError= HarRequesterMaidenName validation error


har.property.harRequesterFirstName.help= (Help HarRequesterFirstName)
har.property.harRequesterFirstName.validationError= HarRequesterFirstName validation error


har.property.harRequesterStreetName.help= (Help HarRequesterStreetName)
har.property.harRequesterStreetName.validationError= HarRequesterStreetName validation error


har.property.harRequesterPostalCode.help= (Help HarRequesterPostalCode)
har.property.harRequesterPostalCode.validationError= HarRequesterPostalCode validation error


har.property.harRequesterCity.help= (Help HarRequesterCity)
har.property.harRequesterCity.validationError= HarRequesterCity validation error


har.property.harRequesterPhone.help= (Help HarRequesterPhone)
har.property.harRequesterPhone.validationError= HarRequesterPhone validation error


har.property.harRequesterMobilePhone.help= (Help HarRequesterMobilePhone)
har.property.harRequesterMobilePhone.validationError= HarRequesterMobilePhone validation error


har.property.harRequesterEmail.help= (Help HarRequesterEmail)
har.property.harRequesterEmail.validationError= HarRequesterEmail validation error


har.property.harRequesterBirthDate.help= (Help HarRequesterBirthDate)
har.property.harRequesterBirthDate.validationError= HarRequesterBirthDate validation error


har.property.harRequesterBirthCity.help= (Help HarRequesterBirthCity)
har.property.harRequesterBirthCity.validationError= HarRequesterBirthCity validation error


har.property.harRequesterBirthCountry.defaultOption = Choose...
har.property.harRequesterBirthCountry.help= (Help HarRequesterBirthCountry)
har.property.harRequesterBirthCountry.validationError= HarRequesterBirthCountry validation error

har.property.harLessThan20RequesterGender.help= (Help HarLessThan20RequesterGender)
har.property.harLessThan20RequesterGender.validationError= HarLessThan20RequesterGender validation error


har.property.harLessThan20RequesterName.help= (Help HarLessThan20RequesterName)
har.property.harLessThan20RequesterName.validationError= HarLessThan20RequesterName validation error


har.property.harLessThan20RequesterFirstName.help= (Help HarLessThan20RequesterFirstName)
har.property.harLessThan20RequesterFirstName.validationError= HarLessThan20RequesterFirstName validation error


har.property.harLessThan20RequesterStreetName.help= (Help HarLessThan20RequesterStreetName)
har.property.harLessThan20RequesterStreetName.validationError= HarLessThan20RequesterStreetName validation error


har.property.harLessThan20RequesterPostalCode.help= (Help HarLessThan20RequesterPostalCode)
har.property.harLessThan20RequesterPostalCode.validationError= HarLessThan20RequesterPostalCode validation error


har.property.harLessThan20RequesterCity.help= (Help HarLessThan20RequesterCity)
har.property.harLessThan20RequesterCity.validationError= HarLessThan20RequesterCity validation error


har.property.harLessThan20RequesterPhone.help= (Help HarLessThan20RequesterPhone)
har.property.harLessThan20RequesterPhone.validationError= HarLessThan20RequesterPhone validation error


har.property.harLessThan20RequesterMobilePhone.help= (Help HarLessThan20RequesterMobilePhone)
har.property.harLessThan20RequesterMobilePhone.validationError= HarLessThan20RequesterMobilePhone validation error


har.property.harLessThan20RequesterEmail.help= (Help HarLessThan20RequesterEmail)
har.property.harLessThan20RequesterEmail.validationError= HarLessThan20RequesterEmail validation error


har.property.harLessThan20RequesterBirthDate.help= (Help HarLessThan20RequesterBirthDate)
har.property.harLessThan20RequesterBirthDate.validationError= HarLessThan20RequesterBirthDate validation error


har.property.harLessThan20RequesterBirthCity.help= (Help HarLessThan20RequesterBirthCity)
har.property.harLessThan20RequesterBirthCity.validationError= HarLessThan20RequesterBirthCity validation error


har.property.harLessThan20RequesterBirthCountry.defaultOption = Choose...
har.property.harLessThan20RequesterBirthCountry.help= (Help HarLessThan20RequesterBirthCountry)
har.property.harLessThan20RequesterBirthCountry.validationError= HarLessThan20RequesterBirthCountry validation error

har.property.harLessThan20RequesterParentName.help= (Help HarLessThan20RequesterParentName)
har.property.harLessThan20RequesterParentName.validationError= HarLessThan20RequesterParentName validation error


har.property.harLessThan20RequesterParentFirstName.help= (Help HarLessThan20RequesterParentFirstName)
har.property.harLessThan20RequesterParentFirstName.validationError= HarLessThan20RequesterParentFirstName validation error


har.property.harLessThan20RequesterParentStreetName.help= (Help HarLessThan20RequesterParentStreetName)
har.property.harLessThan20RequesterParentStreetName.validationError= HarLessThan20RequesterParentStreetName validation error


har.property.harLessThan20RequesterParentPostalCode.help= (Help HarLessThan20RequesterParentPostalCode)
har.property.harLessThan20RequesterParentPostalCode.validationError= HarLessThan20RequesterParentPostalCode validation error


har.property.harLessThan20RequesterParentCity.help= (Help HarLessThan20RequesterParentCity)
har.property.harLessThan20RequesterParentCity.validationError= HarLessThan20RequesterParentCity validation error


har.property.harLessThan20RequesterParentPhone.help= (Help HarLessThan20RequesterParentPhone)
har.property.harLessThan20RequesterParentPhone.validationError= HarLessThan20RequesterParentPhone validation error


har.property.harLessThan20RequesterParentMobilePhone.help= (Help HarLessThan20RequesterParentMobilePhone)
har.property.harLessThan20RequesterParentMobilePhone.validationError= HarLessThan20RequesterParentMobilePhone validation error


har.property.harLessThan20RequesterParentJob.help= (Help HarLessThan20RequesterParentJob)
har.property.harLessThan20RequesterParentJob.validationError= HarLessThan20RequesterParentJob validation error


har.property.harLessThan20RequesterRepresentativeActivityReduction.help= (Help HarLessThan20RequesterRepresentativeActivityReduction)
har.property.harLessThan20RequesterRepresentativeActivityReduction.validationError= HarLessThan20RequesterRepresentativeActivityReduction validation error


har.property.harLessThan20RequesterRepresentativeReductionRatio.help= (Help HarLessThan20RequesterRepresentativeReductionRatio)
har.property.harLessThan20RequesterRepresentativeReductionRatio.validationError= HarLessThan20RequesterRepresentativeReductionRatio validation error


har.property.harLessThan20RequesterParentName.help= (Help HarLessThan20RequesterParentName)
har.property.harLessThan20RequesterParentName.validationError= HarLessThan20RequesterParentName validation error


har.property.harLessThan20RequesterParentFirstName.help= (Help HarLessThan20RequesterParentFirstName)
har.property.harLessThan20RequesterParentFirstName.validationError= HarLessThan20RequesterParentFirstName validation error


har.property.harLessThan20RequesterParentStreetName.help= (Help HarLessThan20RequesterParentStreetName)
har.property.harLessThan20RequesterParentStreetName.validationError= HarLessThan20RequesterParentStreetName validation error


har.property.harLessThan20RequesterParentPostalCode.help= (Help HarLessThan20RequesterParentPostalCode)
har.property.harLessThan20RequesterParentPostalCode.validationError= HarLessThan20RequesterParentPostalCode validation error


har.property.harLessThan20RequesterParentCity.help= (Help HarLessThan20RequesterParentCity)
har.property.harLessThan20RequesterParentCity.validationError= HarLessThan20RequesterParentCity validation error


har.property.harLessThan20RequesterParentPhone.help= (Help HarLessThan20RequesterParentPhone)
har.property.harLessThan20RequesterParentPhone.validationError= HarLessThan20RequesterParentPhone validation error


har.property.harLessThan20RequesterParentMobilePhone.help= (Help HarLessThan20RequesterParentMobilePhone)
har.property.harLessThan20RequesterParentMobilePhone.validationError= HarLessThan20RequesterParentMobilePhone validation error


har.property.harLessThan20RequesterParentJob.help= (Help HarLessThan20RequesterParentJob)
har.property.harLessThan20RequesterParentJob.validationError= HarLessThan20RequesterParentJob validation error


har.property.harLessThan20RequesterRepresentativeActivityReduction.help= (Help HarLessThan20RequesterRepresentativeActivityReduction)
har.property.harLessThan20RequesterRepresentativeActivityReduction.validationError= HarLessThan20RequesterRepresentativeActivityReduction validation error


har.property.harLessThan20RequesterRepresentativeReductionRatio.help= (Help HarLessThan20RequesterRepresentativeReductionRatio)
har.property.harLessThan20RequesterRepresentativeReductionRatio.validationError= HarLessThan20RequesterRepresentativeReductionRatio validation error


har.property.harLessThan20RequesterRepresentativeName.help= (Help HarLessThan20RequesterRepresentativeName)
har.property.harLessThan20RequesterRepresentativeName.validationError= HarLessThan20RequesterRepresentativeName validation error


har.property.harLessThan20RequesterRepresentativeFirstName.help= (Help HarLessThan20RequesterRepresentativeFirstName)
har.property.harLessThan20RequesterRepresentativeFirstName.validationError= HarLessThan20RequesterRepresentativeFirstName validation error


har.property.harLessThan20RequesterRepresentativeStreetName.help= (Help HarLessThan20RequesterRepresentativeStreetName)
har.property.harLessThan20RequesterRepresentativeStreetName.validationError= HarLessThan20RequesterRepresentativeStreetName validation error


har.property.harLessThan20RequesterRepresentativePostalCode.help= (Help HarLessThan20RequesterRepresentativePostalCode)
har.property.harLessThan20RequesterRepresentativePostalCode.validationError= HarLessThan20RequesterRepresentativePostalCode validation error


har.property.harLessThan20RequesterRepresentativeCity.help= (Help HarLessThan20RequesterRepresentativeCity)
har.property.harLessThan20RequesterRepresentativeCity.validationError= HarLessThan20RequesterRepresentativeCity validation error


har.property.harLessThan20RequesterRepresentativePhone.help= (Help HarLessThan20RequesterRepresentativePhone)
har.property.harLessThan20RequesterRepresentativePhone.validationError= HarLessThan20RequesterRepresentativePhone validation error


har.property.harLessThan20RequesterRepresentativeMobilePhone.help= (Help HarLessThan20RequesterRepresentativeMobilePhone)
har.property.harLessThan20RequesterRepresentativeMobilePhone.validationError= HarLessThan20RequesterRepresentativeMobilePhone validation error


har.property.harLessThan20RequesterRepresentativeName.help= (Help HarLessThan20RequesterRepresentativeName)
har.property.harLessThan20RequesterRepresentativeName.validationError= HarLessThan20RequesterRepresentativeName validation error


har.property.harLessThan20RequesterRepresentativeDepartment.help= (Help HarLessThan20RequesterRepresentativeDepartment)
har.property.harLessThan20RequesterRepresentativeDepartment.validationError= HarLessThan20RequesterRepresentativeDepartment validation error


har.property.familyStatus.defaultOption = Choose...
har.property.familyStatus.help= (Help FamilyStatus)
har.property.familyStatus.validationError= FamilyStatus validation error

har.property.familyHasFamilyDependents.help= (Help FamilyHasFamilyDependents)
har.property.familyHasFamilyDependents.validationError= FamilyHasFamilyDependents validation error


har.property.harFamilyDependent.help= (Help HarFamilyDependent)
har.property.harFamilyDependent.validationError= HarFamilyDependent validation error
 

har.property.harDwellingKind.defaultOption = Choose...
har.property.harDwellingKind.help= (Help HarDwellingKind)
har.property.harDwellingKind.validationError= HarDwellingKind validation error

har.property.harDwellingPrecision.help= (Help HarDwellingPrecision)
har.property.harDwellingPrecision.validationError= HarDwellingPrecision validation error

har.property.harDwellingEstablishmentReception.help= (Help HarDwellingEstablishmentReception)
har.property.harDwellingEstablishmentReception.validationError= HarDwellingEstablishmentReception validation error

har.property.harDwellingReceptionType.defaultOption = Choose...
har.property.harDwellingReceptionType.help= (Help HarDwellingReceptionType)
har.property.harDwellingReceptionType.validationError= HarDwellingReceptionType validation error

har.property.dwellingReceptionNaming.help= (Help DwellingReceptionNaming)
har.property.dwellingReceptionNaming.validationError= DwellingReceptionNaming validation error

har.property.harDwellingReceptionAddress.help= (Help HarDwellingReceptionAddress)
har.property.harDwellingReceptionAddress.validationError= HarDwellingReceptionAddress validation error

har.property.harDwellingReceptionPostalCode.help= (Help HarDwellingReceptionPostalCode)
har.property.harDwellingReceptionPostalCode.validationError= HarDwellingReceptionPostalCode validation error

har.property.harDwellingReceptionCity.help= (Help HarDwellingReceptionCity)
har.property.harDwellingReceptionCity.validationError= HarDwellingReceptionCity validation error

har.property.harDwellingSocialReception.help= (Help HarDwellingSocialReception)
har.property.harDwellingSocialReception.validationError= HarDwellingSocialReception validation error

har.property.harDwellingSocialReceptionNaming.help= (Help HarDwellingSocialReceptionNaming)
har.property.harDwellingSocialReceptionNaming.validationError= HarDwellingSocialReceptionNaming validation error

har.property.harDwellingSocialReceptionAddress.help= (Help HarDwellingSocialReceptionAddress)
har.property.harDwellingSocialReceptionAddress.validationError= HarDwellingSocialReceptionAddress validation error

har.property.harDwellingSocialReceptionPostalCode.help= (Help HarDwellingSocialReceptionPostalCode)
har.property.harDwellingSocialReceptionPostalCode.validationError= HarDwellingSocialReceptionPostalCode validation error

har.property.harDwellingSocialReceptionCity.help= (Help HarDwellingSocialReceptionCity)
har.property.harDwellingSocialReceptionCity.validationError= HarDwellingSocialReceptionCity validation error
 

har.property.harSocialSecurityMemberShipKind.defaultOption = Choose...
har.property.harSocialSecurityMemberShipKind.help= (Help HarSocialSecurityMemberShipKind)
har.property.harSocialSecurityMemberShipKind.validationError= HarSocialSecurityMemberShipKind validation error

har.property.harSocialSecurityNumber.help= (Help HarSocialSecurityNumber)
har.property.harSocialSecurityNumber.validationError= HarSocialSecurityNumber validation error


har.property.harSocialSecurityAgencyName.help= (Help HarSocialSecurityAgencyName)
har.property.harSocialSecurityAgencyName.validationError= HarSocialSecurityAgencyName validation error


har.property.harSocialSecurityAgencyAddress.help= (Help HarSocialSecurityAgencyAddress)
har.property.harSocialSecurityAgencyAddress.validationError= HarSocialSecurityAgencyAddress validation error


har.property.harSocialSecurityAgencyPostalCode.help= (Help HarSocialSecurityAgencyPostalCode)
har.property.harSocialSecurityAgencyPostalCode.validationError= HarSocialSecurityAgencyPostalCode validation error


har.property.harSocialSecurityAgencyCity.help= (Help HarSocialSecurityAgencyCity)
har.property.harSocialSecurityAgencyCity.validationError= HarSocialSecurityAgencyCity validation error


har.property.harPaymentAgencyBeneficiary.defaultOption = Choose...
har.property.harPaymentAgencyBeneficiary.help= (Help HarPaymentAgencyBeneficiary)
har.property.harPaymentAgencyBeneficiary.validationError= HarPaymentAgencyBeneficiary validation error

har.property.harPaymentAgencyBeneficiaryNumber.help= (Help HarPaymentAgencyBeneficiaryNumber)
har.property.harPaymentAgencyBeneficiaryNumber.validationError= HarPaymentAgencyBeneficiaryNumber validation error


har.property.harPaymentAgencyName.help= (Help HarPaymentAgencyName)
har.property.harPaymentAgencyName.validationError= HarPaymentAgencyName validation error


har.property.harPaymentAgencyAddress.help= (Help HarPaymentAgencyAddress)
har.property.harPaymentAgencyAddress.validationError= HarPaymentAgencyAddress validation error


har.property.harPaymentAgencyPostalCode.help= (Help HarPaymentAgencyPostalCode)
har.property.harPaymentAgencyPostalCode.validationError= HarPaymentAgencyPostalCode validation error


har.property.harPaymentAgencyCity.help= (Help HarPaymentAgencyCity)
har.property.harPaymentAgencyCity.validationError= HarPaymentAgencyCity validation error

 

har.property.harSchoolingEnrolment.help= (Help HarSchoolingEnrolment)
har.property.harSchoolingEnrolment.validationError= HarSchoolingEnrolment validation error


har.property.harSchoolName.help= (Help HarSchoolName)
har.property.harSchoolName.validationError= HarSchoolName validation error


har.property.harSchoolAddress.help= (Help HarSchoolAddress)
har.property.harSchoolAddress.validationError= HarSchoolAddress validation error


har.property.harSchoolPostalCode.help= (Help HarSchoolPostalCode)
har.property.harSchoolPostalCode.validationError= HarSchoolPostalCode validation error


har.property.harSchoolCity.help= (Help HarSchoolCity)
har.property.harSchoolCity.validationError= HarSchoolCity validation error


har.property.harSendToSchool.help= (Help HarSendToSchool)
har.property.harSendToSchool.validationError= HarSendToSchool validation error


har.property.harAttendedGrade.help= (Help HarAttendedGrade)
har.property.harAttendedGrade.validationError= HarAttendedGrade validation error


har.property.harSpecializedGrade.help= (Help HarSpecializedGrade)
har.property.harSpecializedGrade.validationError= HarSpecializedGrade validation error


har.property.harSpecializedGradeDetails.help= (Help HarSpecializedGradeDetails)
har.property.harSpecializedGradeDetails.validationError= HarSpecializedGradeDetails validation error


har.property.harSchoolingKind.defaultOption = Choose...
har.property.harSchoolingKind.help= (Help HarSchoolingKind)
har.property.harSchoolingKind.validationError= HarSchoolingKind validation error

har.property.harSchoolingTime.help= (Help HarSchoolingTime)
har.property.harSchoolingTime.validationError= HarSchoolingTime validation error


har.property.harHomeSchooling.help= (Help HarHomeSchooling)
har.property.harHomeSchooling.validationError= HarHomeSchooling validation error


har.property.harPersonalizedSchoolingPlan.help= (Help HarPersonalizedSchoolingPlan)
har.property.harPersonalizedSchoolingPlan.validationError= HarPersonalizedSchoolingPlan validation error


har.property.harHomeSchoolingKind.defaultOption = Choose...
har.property.harHomeSchoolingKind.help= (Help HarHomeSchoolingKind)
har.property.harHomeSchoolingKind.validationError= HarHomeSchoolingKind validation error

har.property.harHomeSchoolingAccompanistLastName.help= (Help HarHomeSchoolingAccompanistLastName)
har.property.harHomeSchoolingAccompanistLastName.validationError= HarHomeSchoolingAccompanistLastName validation error


har.property.harHomeSchoolingAccompanistFirstName.help= (Help HarHomeSchoolingAccompanistFirstName)
har.property.harHomeSchoolingAccompanistFirstName.validationError= HarHomeSchoolingAccompanistFirstName validation error


har.property.harHomeSchoolingAccompanistAddress.help= (Help HarHomeSchoolingAccompanistAddress)
har.property.harHomeSchoolingAccompanistAddress.validationError= HarHomeSchoolingAccompanistAddress validation error


har.property.harHomeSchoolingAccompanistPostalCode.help= (Help HarHomeSchoolingAccompanistPostalCode)
har.property.harHomeSchoolingAccompanistPostalCode.validationError= HarHomeSchoolingAccompanistPostalCode validation error


har.property.harHomeSchoolingAccompanistCity.help= (Help HarHomeSchoolingAccompanistCity)
har.property.harHomeSchoolingAccompanistCity.validationError= HarHomeSchoolingAccompanistCity validation error


har.property.harExtraCurricular.help= (Help HarExtraCurricular)
har.property.harExtraCurricular.validationError= HarExtraCurricular validation error


har.property.harHighSchool.help= (Help HarHighSchool)
har.property.harHighSchool.validationError= HarHighSchool validation error


har.property.harHighSchoolGrade.help= (Help HarHighSchoolGrade)
har.property.harHighSchoolGrade.validationError= HarHighSchoolGrade validation error


har.property.harHighSchoolName.help= (Help HarHighSchoolName)
har.property.harHighSchoolName.validationError= HarHighSchoolName validation error


har.property.harHighSchoolAddress.help= (Help HarHighSchoolAddress)
har.property.harHighSchoolAddress.validationError= HarHighSchoolAddress validation error


har.property.harHighSchoolPostalCode.help= (Help HarHighSchoolPostalCode)
har.property.harHighSchoolPostalCode.validationError= HarHighSchoolPostalCode validation error


har.property.harHighSchoolCity.help= (Help HarHighSchoolCity)
har.property.harHighSchoolCity.validationError= HarHighSchoolCity validation error


har.property.harAssistanceUnderDisability.help= (Help HarAssistanceUnderDisability)
har.property.harAssistanceUnderDisability.validationError= HarAssistanceUnderDisability validation error


har.property.harAssistanceUnderDisabilityDetails.help= (Help HarAssistanceUnderDisabilityDetails)
har.property.harAssistanceUnderDisabilityDetails.validationError= HarAssistanceUnderDisabilityDetails validation error


har.property.harStudiesLevel.help= (Help HarStudiesLevel)
har.property.harStudiesLevel.validationError= HarStudiesLevel validation error


har.property.harDiploma.help= (Help HarDiploma)
har.property.harDiploma.validationError= HarDiploma validation error


har.property.harPreviousFormation.help= (Help HarPreviousFormation)
har.property.harPreviousFormation.validationError= HarPreviousFormation validation error


har.property.harCurrentFormation.help= (Help HarCurrentFormation)
har.property.harCurrentFormation.validationError= HarCurrentFormation validation error


har.property.harProfessionalStatusKind.defaultOption = Choose...
har.property.harProfessionalStatusKind.help= (Help HarProfessionalStatusKind)
har.property.harProfessionalStatusKind.validationError= HarProfessionalStatusKind validation error

har.property.harProfessionalStatusDate.help= (Help HarProfessionalStatusDate)
har.property.harProfessionalStatusDate.validationError= HarProfessionalStatusDate validation error


har.property.harProfessionalStatusEnvironment.defaultOption = Choose...
har.property.harProfessionalStatusEnvironment.help= (Help HarProfessionalStatusEnvironment)
har.property.harProfessionalStatusEnvironment.validationError= HarProfessionalStatusEnvironment validation error

har.property.harProfessionalStatusProfession.help= (Help HarProfessionalStatusProfession)
har.property.harProfessionalStatusProfession.validationError= HarProfessionalStatusProfession validation error


har.property.harProfessionalStatusAddress.help= (Help HarProfessionalStatusAddress)
har.property.harProfessionalStatusAddress.validationError= HarProfessionalStatusAddress validation error


har.property.harProfessionalStatusPostalCode.help= (Help HarProfessionalStatusPostalCode)
har.property.harProfessionalStatusPostalCode.validationError= HarProfessionalStatusPostalCode validation error


har.property.harProfessionalStatusCity.help= (Help HarProfessionalStatusCity)
har.property.harProfessionalStatusCity.validationError= HarProfessionalStatusCity validation error


har.property.harRegisterAsUnemployed.help= (Help HarRegisterAsUnemployed)
har.property.harRegisterAsUnemployed.validationError= HarRegisterAsUnemployed validation error


har.property.harRegisterAsUnemployedDate.help= (Help HarRegisterAsUnemployedDate)
har.property.harRegisterAsUnemployedDate.validationError= HarRegisterAsUnemployedDate validation error


har.property.harIndemnified.help= (Help HarIndemnified)
har.property.harIndemnified.validationError= HarIndemnified validation error


har.property.harIndemnifiedDate.help= (Help HarIndemnifiedDate)
har.property.harIndemnifiedDate.validationError= HarIndemnifiedDate validation error


har.property.harElectiveFunction.help= (Help HarElectiveFunction)
har.property.harElectiveFunction.validationError= HarElectiveFunction validation error


har.property.harElectiveFunctionDetails.help= (Help HarElectiveFunctionDetails)
har.property.harElectiveFunctionDetails.validationError= HarElectiveFunctionDetails validation error

 

har.property.harMDPHFile.help= (Help HarMDPHFile)
har.property.harMDPHFile.validationError= HarMDPHFile validation error


har.property.harMDPHNumber.help= (Help HarMDPHNumber)
har.property.harMDPHNumber.validationError= HarMDPHNumber validation error


har.property.harMDPHDepartment.help= (Help HarMDPHDepartment)
har.property.harMDPHDepartment.validationError= HarMDPHDepartment validation error


har.property.harCOTOREPFile.help= (Help HarCOTOREPFile)
har.property.harCOTOREPFile.validationError= HarCOTOREPFile validation error


har.property.harCOTOREPNumber.help= (Help HarCOTOREPNumber)
har.property.harCOTOREPNumber.validationError= HarCOTOREPNumber validation error


har.property.harCOTOREPDepartment.help= (Help HarCOTOREPDepartment)
har.property.harCOTOREPDepartment.validationError= HarCOTOREPDepartment validation error


har.property.harCDESFile.help= (Help HarCDESFile)
har.property.harCDESFile.validationError= HarCDESFile validation error


har.property.harCDESNumber.help= (Help HarCDESNumber)
har.property.harCDESNumber.validationError= HarCDESNumber validation error


har.property.harCDESDepartment.help= (Help HarCDESDepartment)
har.property.harCDESDepartment.validationError= HarCDESDepartment validation error


har.property.harOtherFiles.help= (Help HarOtherFiles)
har.property.harOtherFiles.validationError= HarOtherFiles validation error

har.property.harDisabilityRecognition.help= (Help HarDisabilityRecognition)
har.property.harDisabilityRecognition.validationError= HarDisabilityRecognition validation error


har.property.harDisabilityRatio.help= (Help HarDisabilityRatio)
har.property.harDisabilityRatio.validationError= HarDisabilityRatio validation error


har.property.harDisabilityCard.help= (Help HarDisabilityCard)
har.property.harDisabilityCard.validationError= HarDisabilityCard validation error


har.property.harPainfulStandingCard.help= (Help HarPainfulStandingCard)
har.property.harPainfulStandingCard.validationError= HarPainfulStandingCard validation error


har.property.harParkingCard.help= (Help HarParkingCard)
har.property.harParkingCard.validationError= HarParkingCard validation error


har.property.harDisabledWorkerRecognition.help= (Help HarDisabledWorkerRecognition)
har.property.harDisabledWorkerRecognition.validationError= HarDisabledWorkerRecognition validation error


har.property.harProfessionalOrientation.help= (Help HarProfessionalOrientation)
har.property.harProfessionalOrientation.validationError= HarProfessionalOrientation validation error


har.property.harProfessionalOrientationDetails.help= (Help HarProfessionalOrientationDetails)
har.property.harProfessionalOrientationDetails.validationError= HarProfessionalOrientationDetails validation error


har.property.harDisabledAdultAllocation.help= (Help HarDisabledAdultAllocation)
har.property.harDisabledAdultAllocation.validationError= HarDisabledAdultAllocation validation error


har.property.harIncreaseForIndependentLiving.help= (Help HarIncreaseForIndependentLiving)
har.property.harIncreaseForIndependentLiving.validationError= HarIncreaseForIndependentLiving validation error


har.property.harEducationAllocationOfDisabledChildren.help= (Help HarEducationAllocationOfDisabledChildren)
har.property.harEducationAllocationOfDisabledChildren.validationError= HarEducationAllocationOfDisabledChildren validation error


har.property.harAdditionalAllocationForEducationOfDisabledChildren.help= (Help HarAdditionalAllocationForEducationOfDisabledChildren)
har.property.harAdditionalAllocationForEducationOfDisabledChildren.validationError= HarAdditionalAllocationForEducationOfDisabledChildren validation error


har.property.harAdditionalAllocationForEducationOfDisabledChildrenDetails.help= (Help HarAdditionalAllocationForEducationOfDisabledChildrenDetails)
har.property.harAdditionalAllocationForEducationOfDisabledChildrenDetails.validationError= HarAdditionalAllocationForEducationOfDisabledChildrenDetails validation error


har.property.harSupplementForSingleParents.help= (Help HarSupplementForSingleParents)
har.property.harSupplementForSingleParents.validationError= HarSupplementForSingleParents validation error


har.property.harThridPersonCompensatoryAllowance.help= (Help HarThridPersonCompensatoryAllowance)
har.property.harThridPersonCompensatoryAllowance.validationError= HarThridPersonCompensatoryAllowance validation error


har.property.harThridPartyCompensatoryAllowance.help= (Help HarThridPartyCompensatoryAllowance)
har.property.harThridPartyCompensatoryAllowance.validationError= HarThridPartyCompensatoryAllowance validation error


har.property.harCompensatoryAllowanceForExpenses.help= (Help HarCompensatoryAllowanceForExpenses)
har.property.harCompensatoryAllowanceForExpenses.validationError= HarCompensatoryAllowanceForExpenses validation error


har.property.harDisabilityCompensation.help= (Help HarDisabilityCompensation)
har.property.harDisabilityCompensation.validationError= HarDisabilityCompensation validation error


har.property.harDisabilityPension.help= (Help HarDisabilityPension)
har.property.harDisabilityPension.validationError= HarDisabilityPension validation error


har.property.harDisabilityPensionCategory.help= (Help HarDisabilityPensionCategory)
har.property.harDisabilityPensionCategory.validationError= HarDisabilityPensionCategory validation error


har.property.harWorkAccidentAnnuity.help= (Help HarWorkAccidentAnnuity)
har.property.harWorkAccidentAnnuity.validationError= HarWorkAccidentAnnuity validation error


har.property.harWorkAccidentAnnuityRatio.help= (Help HarWorkAccidentAnnuityRatio)
har.property.harWorkAccidentAnnuityRatio.validationError= HarWorkAccidentAnnuityRatio validation error


har.property.harSocialWelfare.help= (Help HarSocialWelfare)
har.property.harSocialWelfare.validationError= HarSocialWelfare validation error


har.property.harUnemploymentBenefits.help= (Help HarUnemploymentBenefits)
har.property.harUnemploymentBenefits.validationError= HarUnemploymentBenefits validation error


har.property.harDailyAllowances.help= (Help HarDailyAllowances)
har.property.harDailyAllowances.validationError= HarDailyAllowances validation error


har.property.harThridPartySupplement.help= (Help HarThridPartySupplement)
har.property.harThridPartySupplement.validationError= HarThridPartySupplement validation error


har.property.harSupportedByAnInstitution.help= (Help HarSupportedByAnInstitution)
har.property.harSupportedByAnInstitution.validationError= HarSupportedByAnInstitution validation error


har.property.harSupportedByAnInstitutionDetails.help= (Help HarSupportedByAnInstitutionDetails)
har.property.harSupportedByAnInstitutionDetails.validationError= HarSupportedByAnInstitutionDetails validation error


har.property.harIsFamilyCarer.help= (Help HarIsFamilyCarer)
har.property.harIsFamilyCarer.validationError= HarIsFamilyCarer validation error

har.property.harFamilyCarer.help= (Help HarFamilyCarer)
har.property.harFamilyCarer.validationError= HarFamilyCarer validation error

har.property.harIsCarer.help= (Help HarIsCarer)
har.property.harIsCarer.validationError= HarIsCarer validation error

har.property.harCarer.help= (Help HarCarer)
har.property.harCarer.validationError= HarCarer validation error

har.property.harIsCareAssistant.help= (Help HarIsCareAssistant)
har.property.harIsCareAssistant.validationError= HarIsCareAssistant validation error

har.property.harCareAssistant.help= (Help HarCareAssistant)
har.property.harCareAssistant.validationError= HarCareAssistant validation error

har.property.harHousingFacilities.help= (Help HarHousingFacilities)
har.property.harHousingFacilities.validationError= HarHousingFacilities validation error


har.property.harHousingFacilitiesDetails.help= (Help HarHousingFacilitiesDetails)
har.property.harHousingFacilitiesDetails.validationError= HarHousingFacilitiesDetails validation error


har.property.harTechnicalAssistance.help= (Help HarTechnicalAssistance)
har.property.harTechnicalAssistance.validationError= HarTechnicalAssistance validation error


har.property.harTechnicalAssistanceDetails.help= (Help HarTechnicalAssistanceDetails)
har.property.harTechnicalAssistanceDetails.validationError= HarTechnicalAssistanceDetails validation error


har.property.harCustomCar.help= (Help HarCustomCar)
har.property.harCustomCar.validationError= HarCustomCar validation error


har.property.harCustomCarDetails.help= (Help HarCustomCarDetails)
har.property.harCustomCarDetails.validationError= HarCustomCarDetails validation error


har.property.harAnimalAid.help= (Help HarAnimalAid)
har.property.harAnimalAid.validationError= HarAnimalAid validation error


har.property.harAnimalAidDetails.help= (Help HarAnimalAidDetails)
har.property.harAnimalAidDetails.validationError= HarAnimalAidDetails validation error


har.property.harSpecializedTransport.help= (Help HarSpecializedTransport)
har.property.harSpecializedTransport.validationError= HarSpecializedTransport validation error


har.property.harSpecializedTransportDetails.help= (Help HarSpecializedTransportDetails)
har.property.harSpecializedTransportDetails.validationError= HarSpecializedTransportDetails validation error


har.property.harProfessionalEvaluation.help= (Help HarProfessionalEvaluation)
har.property.harProfessionalEvaluation.validationError= HarProfessionalEvaluation validation error

har.property.harProfessional.help= (Help HarProfessional)
har.property.harProfessional.validationError= HarProfessional validation error

har.property.harRequestDealWithSameProfessional.help= (Help HarRequestDealWithSameProfessional)
har.property.harRequestDealWithSameProfessional.validationError= HarRequestDealWithSameProfessional validation error

har.property.harFollowUp.help= (Help HarFollowUp)
har.property.harFollowUp.validationError= HarFollowUp validation error


har.property.harSocialProfessionalLastName.help= (Help HarSocialProfessionalLastName)
har.property.harSocialProfessionalLastName.validationError= HarSocialProfessionalLastName validation error


har.property.harSocialProfessionalAddress.help= (Help HarSocialProfessionalAddress)
har.property.harSocialProfessionalAddress.validationError= HarSocialProfessionalAddress validation error


har.property.harSocialProfessionalPostalCode.help= (Help HarSocialProfessionalPostalCode)
har.property.harSocialProfessionalPostalCode.validationError= HarSocialProfessionalPostalCode validation error


har.property.harSocialProfessionalCity.help= (Help HarSocialProfessionalCity)
har.property.harSocialProfessionalCity.validationError= HarSocialProfessionalCity validation error


har.property.harDisabilityRelatedCost.help= (Help HarDisabilityRelatedCost)
har.property.harDisabilityRelatedCost.validationError= HarDisabilityRelatedCost validation error
 

har.property.harFollowedByPhysician.help= (Help HarFollowedByPhysician)
har.property.harFollowedByPhysician.validationError= HarFollowedByPhysician validation error


har.property.harFollowedByPhysicianDetails.help= (Help HarFollowedByPhysicianDetails)
har.property.harFollowedByPhysicianDetails.validationError= HarFollowedByPhysicianDetails validation error


har.property.harFollowedByProfessional.help= (Help HarFollowedByProfessional)
har.property.harFollowedByProfessional.validationError= HarFollowedByProfessional validation error


har.property.harFollowedByProfessionalDetails.help= (Help HarFollowedByProfessionalDetails)
har.property.harFollowedByProfessionalDetails.validationError= HarFollowedByProfessionalDetails validation error


har.property.harFollowedByHospital.help= (Help HarFollowedByHospital)
har.property.harFollowedByHospital.validationError= HarFollowedByHospital validation error


har.property.harFollowedByHospitalDetails.help= (Help HarFollowedByHospitalDetails)
har.property.harFollowedByHospitalDetails.validationError= HarFollowedByHospitalDetails validation error

 

har.property.harDisabilityRecognitionRequest.help= (Help HarDisabilityRecognitionRequest)
har.property.harDisabilityRecognitionRequest.validationError= HarDisabilityRecognitionRequest validation error


har.property.harDisabilityCardRequest.help= (Help HarDisabilityCardRequest)
har.property.harDisabilityCardRequest.validationError= HarDisabilityCardRequest validation error


har.property.harDisabledPriorityCardRequest.help= (Help HarDisabledPriorityCardRequest)
har.property.harDisabledPriorityCardRequest.validationError= HarDisabledPriorityCardRequest validation error


har.property.harEuropeanParkingCardRequest.help= (Help HarEuropeanParkingCardRequest)
har.property.harEuropeanParkingCardRequest.validationError= HarEuropeanParkingCardRequest validation error


har.property.harDisabledAdultAllowanceRequest.help= (Help HarDisabledAdultAllowanceRequest)
har.property.harDisabledAdultAllowanceRequest.validationError= HarDisabledAdultAllowanceRequest validation error


har.property.harIncreaseForIndependentLivingRequest.help= (Help HarIncreaseForIndependentLivingRequest)
har.property.harIncreaseForIndependentLivingRequest.validationError= HarIncreaseForIndependentLivingRequest validation error


har.property.harEducationAllocationOfDisabledChildrenRequest.help= (Help HarEducationAllocationOfDisabledChildrenRequest)
har.property.harEducationAllocationOfDisabledChildrenRequest.validationError= HarEducationAllocationOfDisabledChildrenRequest validation error


har.property.harPTCARenewalRequest.help= (Help HarPTCARenewalRequest)
har.property.harPTCARenewalRequest.validationError= HarPTCARenewalRequest validation error


har.property.harThirdPartyHelpRequest.help= (Help HarThirdPartyHelpRequest)
har.property.harThirdPartyHelpRequest.validationError= HarThirdPartyHelpRequest validation error


har.property.harFreePensionMembershipRequest.help= (Help HarFreePensionMembershipRequest)
har.property.harFreePensionMembershipRequest.validationError= HarFreePensionMembershipRequest validation error


har.property.harTechnicalHelpRequest.help= (Help HarTechnicalHelpRequest)
har.property.harTechnicalHelpRequest.validationError= HarTechnicalHelpRequest validation error


har.property.harHousingFacilitiesRequest.help= (Help HarHousingFacilitiesRequest)
har.property.harHousingFacilitiesRequest.validationError= HarHousingFacilitiesRequest validation error


har.property.harCustomCarRequest.help= (Help HarCustomCarRequest)
har.property.harCustomCarRequest.validationError= HarCustomCarRequest validation error


har.property.harAssistanceRequest.help= (Help HarAssistanceRequest)
har.property.harAssistanceRequest.validationError= HarAssistanceRequest validation error


har.property.harTransportCostAllocationRequest.help= (Help HarTransportCostAllocationRequest)
har.property.harTransportCostAllocationRequest.validationError= HarTransportCostAllocationRequest validation error


har.property.harDisabilityCostAllocationRequest.help= (Help HarDisabilityCostAllocationRequest)
har.property.harDisabilityCostAllocationRequest.validationError= HarDisabilityCostAllocationRequest validation error


har.property.harDisabledWorkerRecognitionRequest.help= (Help HarDisabledWorkerRecognitionRequest)
har.property.harDisabledWorkerRecognitionRequest.validationError= HarDisabledWorkerRecognitionRequest validation error


har.property.harProfessionalOrientationRequest.help= (Help HarProfessionalOrientationRequest)
har.property.harProfessionalOrientationRequest.validationError= HarProfessionalOrientationRequest validation error


har.property.harOrdinaryworkingRequest.help= (Help HarOrdinaryworkingRequest)
har.property.harOrdinaryworkingRequest.validationError= HarOrdinaryworkingRequest validation error


har.property.harShelteredWorkRequest.help= (Help HarShelteredWorkRequest)
har.property.harShelteredWorkRequest.validationError= HarShelteredWorkRequest validation error


har.property.harVocationalTrainingRequest.help= (Help HarVocationalTrainingRequest)
har.property.harVocationalTrainingRequest.validationError= HarVocationalTrainingRequest validation error


har.property.harInstitutionSupportRequest.help= (Help HarInstitutionSupportRequest)
har.property.harInstitutionSupportRequest.validationError= HarInstitutionSupportRequest validation error


har.property.harOtherRequest.help= (Help HarOtherRequest)
har.property.harOtherRequest.validationError= HarOtherRequest validation error


har.property.harOtherRequestDetails.help= (Help HarOtherRequestDetails)
har.property.harOtherRequestDetails.validationError= HarOtherRequestDetails validation error


har.property.harProjectWish.help= (Help HarProjectWish)
har.property.harProjectWish.validationError= HarProjectWish validation error

har.property.harProjectNeeds.help= (Help HarProjectNeeds)
har.property.harProjectNeeds.validationError= HarProjectNeeds validation error

har.property.harProjectComments.help= (Help HarProjectComments)
har.property.harProjectComments.validationError= HarProjectComments validation error
 
 
 

// COMMON 
har.duration.label=Duration : 

// Navigation
har.step.navigation.next=Next &gt;&gt
har.step.navigation.previous=&lt;&lt; Previous
// Tags
har.step.tag.rejected=uncomplete
har.step.tag.validated=complete
har.step.tag.rejected.short=u
har.step.tag.validated.short=c

