package fr.cg95.cvq.service.social;

import fr.cg95.cvq.business.users.*;
import fr.cg95.cvq.business.authority.*;
import fr.cg95.cvq.business.social.*;
import fr.cg95.cvq.exception.*;
import fr.cg95.cvq.security.SecurityContext;
import fr.cg95.cvq.service.users.IDocumentService;
import fr.cg95.cvq.service.users.IRequestService;
import fr.cg95.cvq.service.social.IRemoteSupportRequestService;
import fr.cg95.cvq.util.Critere;

import fr.cg95.cvq.testtool.ServiceTestCase;
import fr.cg95.cvq.testtool.TestUtils;
import fr.cg95.cvq.testtool.BusinessObjectsFactory;

import fr.cg95.cvq.xml.social.RemoteSupportRequestDocument;

import org.apache.commons.lang.StringUtils;
import org.springframework.context.ConfigurableApplicationContext;

import junit.framework.Assert;

import java.util.*;
import java.io.File;
import java.io.FileOutputStream;
import java.math.BigInteger;

/**
 * Generated by Velocity if not present, can be edited safely !
 */
public class RemoteSupportRequestServiceTest extends ServiceTestCase {

    protected IRemoteSupportRequestService iRemoteSupportRequestService;

    protected void onSetUp() throws Exception {
    	super.onSetUp();
        ConfigurableApplicationContext cac = getContext(getConfigLocations());
        iRemoteSupportRequestService = 
            (IRemoteSupportRequestService) cac.getBean(StringUtils.uncapitalize("RemoteSupportRequest") + "Service");
    }

    protected RemoteSupportRequest fillMeARequest() throws CvqException {

        RemoteSupportRequest request = new RemoteSupportRequest();
            if ("TrusteeFirstName".length() > 38)
        request.setTrusteeFirstName("TrusteeFirstName".substring(0, 38));
      else
        request.setTrusteeFirstName("TrusteeFirstName");
                request.setTaxable(Boolean.valueOf(true));
            request.setFloor(BigInteger.valueOf(1));
              if ("ContactName".length() > 38)
        request.setContactName("ContactName".substring(0, 38));
      else
        request.setContactName("ContactName");
                request.setAppartmentNumber(BigInteger.valueOf(1));
              if ("ContactFirstName".length() > 38)
        request.setContactFirstName("ContactFirstName".substring(0, 38));
      else
        request.setContactFirstName("ContactFirstName");
                  request.setContact(RsrContactType.REQUESTER);
                  request.setDwelling(RsrDwellingType.APPARTMENT);
                request.setEmergency(Boolean.valueOf(true));
            request.setSeniorAssitanceBeneficiary(Boolean.valueOf(true));
              if ("TrusteeName".length() > 38)
        request.setTrusteeName("TrusteeName".substring(0, 38));
      else
        request.setTrusteeName("TrusteeName");
                  if ("TrusteePhone".length() > 10)
        request.setTrusteePhone("TrusteePhone".substring(0, 10));
      else
        request.setTrusteePhone("TrusteePhone");
                  request.setTrustee(TrusteeType.REQUESTER);
                  if ("ContactPhone".length() > 10)
        request.setContactPhone("ContactPhone".substring(0, 10));
      else
        request.setContactPhone("ContactPhone");
      
        // Means Of Contact
        MeansOfContact meansOfContact = iMeansOfContactService.getMeansOfContactByType(
                    MeansOfContactEnum.EMAIL);
        request.setMeansOfContact(meansOfContact);
        
        RemoteSupportRequestFeeder.feed(request);
        
        return request;
    }
        	
    protected void completeValidateAndDelete(RemoteSupportRequest request) 
    	throws CvqException, java.io.IOException {
    	
        // add a document to the request
        ///////////////////////////////

        Document doc = new Document();
        doc.setEcitizenNote("Ma carte d'identité !");
        doc.setDepositOrigin(DepositOrigin.ECITIZEN);
        doc.setDepositType(DepositType.PC);
        doc.setDocumentType(iDocumentService.getDocumentTypeById(IDocumentService.IDENTITY_RECEIPT_TYPE));
        Long documentId = iDocumentService.create(doc, request.getHomeFolder().getId(), 
        					  request.getRequester().getId());
        iRemoteSupportRequestService.addDocument(request.getId(), documentId);
        Set documentsSet =
            iRemoteSupportRequestService.getAssociatedDocuments(request.getId());
        Assert.assertEquals(documentsSet.size(), 1);

        // FIXME : test list of pending / in-progress registrations
        Critere testCrit = new Critere();
        testCrit.setAttribut(Request.SEARCH_BY_REQUESTER_LASTNAME);
        testCrit.setComparatif(Critere.EQUALS);
        testCrit.setValue(request.getRequester().getLastName());
        Set testCritSet = new HashSet();
        testCritSet.add(testCrit);
        Set allRequests = iRequestService.get(testCritSet, null, false);
        Assert.assertNotNull(allRequests);

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        SecurityContext.setCurrentSite(localAuthorityName,
                                        SecurityContext.BACK_OFFICE_CONTEXT);
        SecurityContext.setCurrentAgent(agentNameWithCategoriesRoles);
        iRemoteSupportRequestService.complete(request.getId());
        iRemoteSupportRequestService.validate(request.getId());

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        byte[] generatedCertificate = iRequestService.getCertificate(request.getId(),
                                                                     RequestState.PENDING);

        if (generatedCertificate == null)
            fail("No certificate found");
            
        //     Write tele-service xml data file
        File xmlFile = File.createTempFile("tmp" + request.getId(), ".xml");
        FileOutputStream xmlFos = new FileOutputStream(xmlFile);
        xmlFos.write(iRequestService.getById(request.getId()).modelToXmlString().getBytes());

        File file = File.createTempFile("tmp" + request.getId(), ".pdf");
        FileOutputStream fos = new FileOutputStream(file);
        fos.write(generatedCertificate);

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        // delete request
        iRemoteSupportRequestService.delete(request.getId());
    }


    public void testWithHomeFolderXml() throws CvqException,
			CvqObjectNotFoundException, java.io.FileNotFoundException,
			java.io.IOException {

        startTransaction();
        
	SecurityContext.setCurrentSite(localAuthorityName,
					SecurityContext.FRONT_OFFICE_CONTEXT);

	// create a vo card request (to create home folder and associates)
	CreationBean cb = gimmeAnHomeFolder();

	Long voCardRequestId = cb.getRequestId();
	String proposedLogin = cb.getLogin();

        // close current session and re-open a new one
        continueWithNewTransaction();
        
	SecurityContext.setCurrentEcitizen(proposedLogin);

	// get the home folder id
	HomeFolder homeFolder = iHomeFolderService.getByRequestId(voCardRequestId);
	Assert.assertNotNull(homeFolder);
	Long homeFolderId = homeFolder.getId();
	Assert.assertNotNull(homeFolderId);

	// fill and create the request
	// ////////////////////////////

	RemoteSupportRequest request = fillMeARequest();
	request.setRequester(homeFolder.getHomeFolderResponsible());
        RemoteSupportRequestFeeder.setSubject(request, homeFolder);

        Set authorizedSubjects = iRemoteSupportRequestService.getAuthorizedSubjects(homeFolderId).keySet();

	RemoteSupportRequestDocument requestDoc =
		(RemoteSupportRequestDocument) request.modelToXml();
	Long requestId = iRemoteSupportRequestService.create(requestDoc.getDomNode());

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        Map newAuthorizedSubjectsMap = iRemoteSupportRequestService.getAuthorizedSubjects(homeFolderId);
        if (newAuthorizedSubjectsMap == null) 
            Assert.assertEquals(authorizedSubjects.size(), 1);
        else
            Assert.assertEquals(newAuthorizedSubjectsMap.size(), authorizedSubjects.size() - 1);

	RemoteSupportRequest requestFromDb = 
		(RemoteSupportRequest) iRemoteSupportRequestService.getById(requestId);
	Assert.assertEquals(requestId, requestFromDb.getId());
	Adult requester = requestFromDb.getRequester();
	Assert.assertNotNull(requester);
	Assert.assertNotNull(requestFromDb.getMeansOfContact());
    Assert.assertEquals(requestFromDb.getMeansOfContact().getType(), MeansOfContactEnum.EMAIL);

        // close current session and re-open a new one
        continueWithNewTransaction();
        
	completeValidateAndDelete(requestFromDb);

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        HomeFolder homeFolderAfterDelete = iHomeFolderService.getById(homeFolderId);
        Assert.assertNotNull(homeFolderAfterDelete);
        Assert.assertNotNull(homeFolderAfterDelete.getHomeFolderResponsible());
    }

    public void testWithoutHomeFolder()
        throws CvqException, CvqObjectNotFoundException,
               java.io.FileNotFoundException, java.io.IOException {

	if (!iRemoteSupportRequestService.supportUnregisteredCreation())
	    return;

	startTransaction();
	
        SecurityContext.setCurrentSite(localAuthorityName,
                                        SecurityContext.FRONT_OFFICE_CONTEXT);
        
        RemoteSupportRequest request = fillMeARequest();

        Address address = BusinessObjectsFactory.gimmeAdress("12", "Rue d'Aligre", "Paris", "75012");
        Adult requester =
            BusinessObjectsFactory.gimmeAdult(TitleType.MISTER, "LASTNAME", "requester", address,
                                              FamilyStatusType.MARRIED);
        requester.setPassword("requester");
        request.setRequester(requester);
        requester.setAdress(address);
        RemoteSupportRequestFeeder.setSubject(request, null);

        RemoteSupportRequestDocument requestDoc = 
            (RemoteSupportRequestDocument) request.modelToXml();
        Long requestId =
             iRemoteSupportRequestService.create(requestDoc.getDomNode());
        
        // close current session and re-open a new one
        continueWithNewTransaction();
        
        // start testing request creation
        /////////////////////////////////

        RemoteSupportRequest requestFromDb =
            (RemoteSupportRequest) iRemoteSupportRequestService.getById(requestId);
        Assert.assertEquals(requestId, requestFromDb.getId());
        requester = requestFromDb.getRequester();
        Assert.assertNotNull(requester);
        
        Long homeFolderId = requestFromDb.getHomeFolder().getId();
        Long requesterId = requestFromDb.getRequester().getId();

        // close current session and re-open a new one
        continueWithNewTransaction();
        
        completeValidateAndDelete(requestFromDb);
        
        // close current session and re-open a new one
        continueWithNewTransaction();
        
        try {
            iHomeFolderService.getById(homeFolderId);
            fail("should not have found home folder");
        } catch (CvqObjectNotFoundException confe) {
            // great, that was expected
        }
        try {
            iAdultService.getById(requesterId);
            fail("should not have found requester");
        } catch (CvqObjectNotFoundException confe) {
            // great, that was expected
        }

        SecurityContext.resetCurrentSite();
        
        commitTransaction();
    }
}
